-- الأمن السيبراني · S3 أمن الأنظمة · L5 السجلات والمراقبة
-- 90 سؤالاً · وُلِّد آلياً بعد اجتياز فحوصات عقد الجودة كاملة:
--   توزيع الأنواع 30/10×6 · مواضع الإجابة 8/8/7/7 · صفر فجوة طول ≥7
--   صفر تكرار داخل الدفعة وعبر المسار · كل الأنواع مكتملة البنية
-- التشغيل: لوحة Supabase ← SQL Editor ← الصق ونفّذ.

begin;

insert into public.questions
  (track_id, section_id, level, topic, difficulty, question, options, correct_answer, correct_answers, explanation, type, code_snippet, pairs, expected_answers, prompt_label, time_limit, is_active)
values
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'ما الذي يجيب عنه سجل النظام دون غيره؟', '["ما الذي جرى ومتى وبأي هوية","ما الذي يجب تقويته في النظام","ما الثغرات القائمة في البرمجيات","ما الصلاحيات الممنوحة للحسابات"]'::jsonb, 0, NULL, 'الضوابط الأخرى تصف الحال، والسجل وحده يحفظ ما وقع فعلاً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'ما الذي يميّز سجل التدقيق عن سجل التطبيق؟', '["يسجّل أخطاء البرنامج وقت وقوعها","يسجّل الأحداث الأمنية للنظام","يسجّل استهلاك الموارد لحظياً","يسجّل رسائل المستخدم للدعم"]'::jsonb, 1, NULL, 'الأول يخدم المساءلة، والثاني يخدم تشخيص عطل البرنامج.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'لماذا لا يكفي تسجيل الدخول الناجح وحده؟', '["الناجح يستهلك مساحة أكبر بكثير","الناجح لا يحمل طابعاً زمنياً دقيقاً","الفشل المتكرر يكشف محاولة تخمين","الفشل يُسجَّل تلقائياً في كل نظام"]'::jsonb, 2, NULL, 'خمسون فشلاً ثم نجاح واحد نمط لا يظهر إن سُجِّل الناجح فقط.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'ما الذي يجب تسجيله عند تغيير صلاحية حساب؟', '["اسم الحساب المتأثر بالتغيير فقط","وقت التغيير دون هوية من نفّذه","القيمة الجديدة دون ما سبقها","من غيّرها ومتى وما القيمة السابقة"]'::jsonb, 3, NULL, 'بلا القيمة السابقة وهوية المنفّذ لا يُعرَف ما تغيّر ولا من غيّره.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'لماذا يُوحَّد التوقيت بين كل الأنظمة؟', '["لترتيب الأحداث عبر الأجهزة معاً","لتقليل حجم ملفات السجل كثيراً","لتسريع كتابة السجل على القرص","لمنع تكرار السطر نفسه مرتين"]'::jsonb, 0, NULL, 'اختلاف الساعات دقيقتين يقلب ترتيب سلسلة الأحداث كلها.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'ما الذي يفقده التسجيل المفرط في التفصيل؟', '["يمنع النظام من الإقلاع لاحقاً","يغرق المهم في كمّ لا يُقرأ","يوقف كتابة السجلات الأمنية","يمنع توحيد التوقيت بين الأجهزة"]'::jsonb, 1, NULL, 'سجل يكتب كل شيء يساوي سجلاً لا يقرؤه أحد.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'hard', 'ما الذي يحدد مدة الاحتفاظ بالسجلات؟', '["المساحة المتاحة على الخادم","عدد المستخدمين في النظام","متوسط زمن اكتشاف الاختراق","عدد الأحداث في اليوم الواحد"]'::jsonb, 2, NULL, 'مدة أقصر من زمن الاكتشاف تعني ضياع دليل الحادثة قبل بدء البحث.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'لماذا تُجمَع السجلات على خادم منفصل؟', '["لتقليل استهلاك القرص المحلي","لتسريع البحث في السجل المحلي","لتوحيد صيغة السجل بين الأنظمة","لتبقى بعد سقوط الجهاز أو العبث به"]'::jsonb, 3, NULL, 'أول ما يفعله المهاجم مسح سجل الجهاز الذي دخله.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'hard', 'ما الذي لا يجوز أن يظهر في السجل إطلاقاً؟', '["كلمة المرور التي حاول بها","اسم الحساب الذي حاول الدخول","عنوان الجهاز مصدر المحاولة","وقت المحاولة ونتيجتها"]'::jsonb, 0, NULL, 'السجل يُقرأ على نطاق أوسع من قاعدة البيانات، فتسريبه يكشف الاعتماد.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'ما الذي يكشفه غياب حدث متوقّع من السجل؟', '["أن الحدث لم يقع في النظام قطعاً","احتمال تعطيل التسجيل أو حذفه","أن السجل ممتلئ ولا يقبل كتابة","أن التوقيت غير موحّد بين الأجهزة"]'::jsonb, 1, NULL, 'الفجوة في سجل يعمل دليل بذاتها، ولذلك يُراقَب انقطاع التسجيل.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'لماذا يُمنع مسؤول النظام من تعديل سجل التدقيق؟', '["ليقل حجم السجل على القرص","ليتمكن من قراءته بسرعة أكبر","ليصلح السجل دليلاً على فعله هو","ليوحَّد شكله بين كل الأنظمة"]'::jsonb, 2, NULL, 'سجل يستطيع المراقَب تعديله لا يُثبِت شيئاً ضده.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'ما الذي يجعل السجل قابلاً للإضافة دون التعديل؟', '["تشفير الملف بمفتاح المسؤول","ضغط الملف بعد كل كتابة","نسخه دورياً إلى قرص آخر","صلاحية كتابة بلا صلاحية تغيير"]'::jsonb, 3, NULL, 'الإضافة فقط تمنع محو سطر سابق وإن بقيت الكتابة ممكنة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'hard', 'كيف تُكشَف محاولة تعديل سطر في سجل محفوظ؟', '["ببصمة تُحسب على المحتوى وتُقارَن","بمقارنة حجم الملف بحجمه أمس","بعدّ الأسطر في نهاية كل يوم","بمراجعة وقت آخر تعديل للملف"]'::jsonb, 0, NULL, 'تغيير حرف واحد يقلب البصمة، بخلاف الحجم ووقت التعديل فيسهل تزويرهما.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'ما الذي يمنع المهاجم من محو أثره بعد الدخول؟', '["زيادة حجم ملف السجل المحلي","نقل السجل فور كتابته لخادم آخر","تشفير السجل على الجهاز نفسه","تقليل عدد الأحداث المسجّلة"]'::jsonb, 1, NULL, 'ما غادر الجهاز لا يبلغه من سيطر عليه بعد ذلك.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'ما خطر امتلاء مساحة السجل على الجهاز؟', '["يُعاد ترتيب الأحداث القديمة","تتغيّر صيغة الأسطر المكتوبة","تتوقف كتابة الأحداث الجديدة","يفقد السجل طابعه الزمني"]'::jsonb, 2, NULL, 'ولذلك يُراقَب امتلاء المساحة كحدث أمني لا كمسألة تشغيلية.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'لماذا تُراقَب عملية إيقاف خدمة التسجيل نفسها؟', '["إيقافها يوفّر موارد على الجهاز","إيقافها يسرّع إقلاع النظام","إيقافها يمنع امتلاء القرص","إيقافها يسبق إخفاء بقية النشاط"]'::jsonb, 3, NULL, 'من أراد ألا يُرى يطفئ العين أولاً، فالإطفاء نفسه حدث يستحق تنبيهاً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'ما وظيفة تدوير ملفات السجل؟', '["يغلق الملف دورياً ويبدأ غيره","يحذف الأحداث الأقل أهمية","يعيد ترتيب الأسطر بالتوقيت","يدمج سجلات الأجهزة في ملف"]'::jsonb, 0, NULL, 'الملف المغلق أسهل أرشفة وتوقيعاً وأقل عرضة للتلف عند الامتلاء.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'من يجب أن يملك صلاحية قراءة سجل التدقيق؟', '["كل من يملك حساباً على النظام","من يحتاجه لمهمته لا كل إداري","مسؤول النظام وحده دون سواه","المستخدمون المذكورون فيه فقط"]'::jsonb, 1, NULL, 'السجل يحوي أسماء وعناوين وأنماط عمل، فقراءته تخضع لأقل صلاحية أيضاً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'ما الذي يفقده السجل إن لم يُحفَظ خارج متناول من يراقبه؟', '["قابليته للبحث السريع","توحيد صيغته بين الأنظمة","قيمته كدليل عند النزاع","دقة طابعه الزمني"]'::jsonb, 2, NULL, 'الدليل الذي يملك المتهم تعديله لا يصلح إثباتاً في أي مراجعة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'hard', 'لماذا يُوقَّع أرشيف السجل بعد إغلاقه؟', '["ليصغر حجمه قبل التخزين","ليُقرأ بأدوات التحليل مباشرة","ليُفهرَس بحسب نوع الحدث","ليثبت أنه لم يتغيّر بعد ذلك"]'::jsonb, 3, NULL, 'التوقيع يربط المحتوى بلحظة إغلاقه فيكشف أي تعديل لاحق.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'medium', 'ما الفرق بين حدث في السجل وتنبيه؟', '["التنبيه حدث استوجب نظراً بشرياً","التنبيه يُكتب في ملف منفصل","التنبيه لا يُحفَظ بعد قراءته","التنبيه يخص الشبكة دون النظام"]'::jsonb, 0, NULL, 'كل تنبيه حدث، وليس كل حدث يستحق أن يُوقظ أحداً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'medium', 'ما الذي يجعل قاعدة التنبيه صالحة للعمل؟', '["أن تغطي أكبر عدد من الأحداث","أن يترتب على كل تنبيه فعل ممكن","أن تعمل بلا حاجة لخط أساس","أن تُطلق تنبيهاً لكل خطأ دخول"]'::jsonb, 1, NULL, 'تنبيه لا يعرف قارئه ما يفعل به يُغلَق بلا نظر بعد أسبوع.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'لماذا تُضبَط عتبة التنبيه من خط أساس النظام؟', '["العتبة الثابتة أدق في كل الحالات","خط الأساس يقلّل حجم السجل","الطبيعي يختلف من نظام لآخر","العتبة تُشتق من حجم القرص"]'::jsonb, 2, NULL, 'خمسون فشل دخول عادية على بوابة، وشاذة تماماً على خادم إداري.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'medium', 'ما أثر كثرة التنبيهات الكاذبة على الفريق؟', '["يزيد دقة الفرز مع التكرار","يقلّل حجم السجلات المخزّنة","يرفع أولوية التنبيهات الحقيقية","يعتاد الإغلاق فيمر الحقيقي بينها"]'::jsonb, 3, NULL, 'العلاج ضبط القاعدة لا زيادة عدد من يقرؤها.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'medium', 'ما الذي يكشفه ربط حدثين من سجلين مختلفين؟', '["نمطاً لا يظهر في أيهما وحده","خطأ في توقيت أحد الجهازين","تكرار الحدث نفسه مرتين","امتلاء مساحة أحد السجلين"]'::jsonb, 0, NULL, 'إنشاء حساب ثم منحه صلاحية إدارية بعد دقيقة: كل حدث وحده عادي.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'medium', 'لماذا يُنبَّه عند إنشاء حساب إداري جديد؟', '["لأنه يستهلك ترخيصاً إضافياً","لأنه إجراء نادر عالي الأثر","لأنه يبطئ خادم الدليل","لأنه يغيّر صيغة السجل"]'::jsonb, 1, NULL, 'القاعدة الجيدة تنبّه على النادر عالي الأثر لا على المتكرر العادي.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'ما الذي يميّز الكشف بخط الأساس عن الكشف بالقاعدة؟', '["ينتج إنذارات كاذبة أقل بكثير","لا يحتاج فترة تعلّم مسبقة","يكشف الشاذ الذي لا قاعدة له","يعمل على سجل واحد فقط"]'::jsonb, 2, NULL, 'القاعدة تمسك المعروف بدقة، وخط الأساس يمسك الجديد بضجيج أكثر.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'medium', 'ما خطر بناء خط الأساس في فترة اختراق قائم؟', '["يزيد حجم السجل المخزّن كثيراً","يمنع تشغيل قواعد التنبيه","يوقف جمع السجلات مؤقتاً","يصير نشاط المهاجم هو الطبيعي"]'::jsonb, 3, NULL, 'فلا يُنبَّه عنه أبداً لأنه صار جزءاً من المعتاد المسجَّل.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'medium', 'ما الذي يقيس فاعلية المراقبة فعلاً؟', '["زمن كشف الحادثة الحقيقية","عدد التنبيهات المعالَجة يومياً","حجم السجلات المجموعة شهرياً","عدد القواعد المفعّلة في النظام"]'::jsonb, 0, NULL, 'ألف تنبيه مغلق يومياً قد يعني غرقاً في الضجيج لا أماناً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'ما الذي يجب فعله بقاعدة تنبيه لم تُطلق شيئاً منذ سنة؟', '["حذفها فوراً لعدم فائدتها","اختبارها للتأكد أنها تعمل","خفض عتبتها إلى أدنى قيمة","نسخها على بقية الأنظمة"]'::jsonb, 1, NULL, 'الصمت قد يعني سلامة البيئة وقد يعني قاعدة معطّلة، ولا يُعرَف إلا باختبارها.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'ما النمط الذي يكشفه هذا المقطع من السجل؟', '["تخمين متتابع انتهى بنجاح","دخول عادي بعد خطأ طباعي","انقطاع شبكة أعاد المحاولة","خطأ في توحيد التوقيت"]'::jsonb, 0, NULL, 'ثلاث محاولات في ثوانٍ ثم نجاح نمط تخمين لا خطأ إدخال.', 'code', '10:02:11 auth failure user=admin
10:02:12 auth failure user=admin
10:02:14 auth failure user=admin
10:02:19 auth success user=admin', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'ما الخلل في سطر السجل هذا؟', '["السطر يفتقر للطابع الزمني","السطر يسجّل كلمة المرور نصاً","السطر لا يذكر نتيجة المحاولة","السطر لا يحدد اسم الحساب"]'::jsonb, 1, NULL, 'من يقرأ السجل يحصل على اعتماد صالح لحساب آخر ربما.', 'code', 'login attempt user=sara pass=Summer2024! result=failed', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'hard', 'ما الذي يمنع ترتيب هذي الأحداث بثقة؟', '["السجلان بصيغتين مختلفتين","أحد السطرين بلا هوية مستخدم","اختلاف الساعات يقلب التسلسل","الحدثان من نوعين مختلفين"]'::jsonb, 2, NULL, 'بتصحيح الفارق يصير الوصول للملف بعد فتح الجلسة لا قبلها.', 'code', 'srv-a  09:15:03  session opened
srv-b  09:13:47  file accessed
ملاحظة: ساعة srv-b متأخرة دقيقتين', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'hard', 'ما الذي تكشفه هذي الفجوة في السجل؟', '["انقطاع الشبكة عن خادم السجل","امتلاء القرص ثم تفريغه","تغيّر التوقيت الصيفي للنظام","توقف التسجيل مدة طويلة ثم عاد"]'::jsonb, 3, NULL, 'الفجوة مع إعادة تشغيل الخدمة نمط إخفاء أثر لا عطل عابر.', 'code', '02:10:00 heartbeat ok
02:11:00 heartbeat ok
04:47:00 heartbeat ok
logging service: restarted 04:46:59', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'hard', 'ما الذي يثبته اختلاف البصمة هنا؟', '["محتوى الأرشيف تغيّر بعد إغلاقه","الأرشيف نُسخ إلى موقع آخر","الأرشيف ضُغِط بخوارزمية جديدة","الأرشيف قُرئ بأداة مختلفة"]'::jsonb, 0, NULL, 'القراءة والنسخ لا يغيّران البصمة، والتعديل وحده يقلبها.', 'code', 'archive: auth-2026-08.log
بصمة عند الإغلاق: a91f...
بصمة اليوم:        c47d...', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'ما الخلل في أذونات ملف السجل هذا؟', '["الجذر وحده يقرأ الملف","كل مستخدم يستطيع تعديله","الملف بلا صلاحية قراءة","المجموعة تقرأ ولا تكتب"]'::jsonb, 1, NULL, 'سجل يعدّله أي مستخدم لا يصلح دليلاً على أحد.', 'code', '-rw-rw-rw-  1 root root  /var/log/auth.log', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'ما الذي يستوجب تنبيهاً في هذا التسلسل؟', '["موظف الموارد البشرية سجّل دخوله","الدخول جاء من شبكة داخلية","حساب جديد نال صلاحية إدارية فوراً","الأحداث الثلاثة في دقائق متتابعة"]'::jsonb, 2, NULL, 'كل حدث وحده عادي، واجتماعها في دقيقتين نمط تصعيد صلاحية.', 'code', '11:20 user=hr01 created account=tmp_svc
11:21 user=hr01 added tmp_svc to domain-admins
11:23 user=tmp_svc login from 10.0.4.9', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'أي قاعدة تنبيه أنفع بحسب هذا الوصف؟', '["خفض العتبة لخمس حالات فشل","إلغاء التنبيه على الفشل نهائياً","نقل القاعدة لخادم آخر كما هي","رفع العتبة بحسب معتاد البوابة"]'::jsonb, 3, NULL, 'عتبة أدنى من المعتاد تنتج ضجيجاً يومياً يُغلق بلا نظر.', 'code', 'البيئة: بوابة عامة
المعتاد: ٤٠٠ فشل دخول يومياً
القاعدة الحالية: نبّه عند ١٠ حالات فشل', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'medium', 'ما الذي يميّز هذي المحاولة عن فشل عادي؟', '["مصدر واحد يجرّب حسابات مختلفة","حساب واحد يفشل من مصادر عدة","المحاولات في وقت الدوام الرسمي","الحسابات الثلاثة غير موجودة"]'::jsonb, 0, NULL, 'تعداد الحسابات من مصدر واحد استطلاع لا خطأ مستخدم.', 'code', '03:14 failed login user=admin  src=203.0.113.9
03:14 failed login user=root   src=203.0.113.9
03:14 failed login user=oracle src=203.0.113.9', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'hard', 'ما الناقص في هذا السطر لسجل تدقيق؟', '["وقت التغيير بالدقيقة والثانية","هوية من نفّذ التغيير وما سبقه","اسم الملف الذي جرى تغييره","نوع العملية التي جرت عليه"]'::jsonb, 1, NULL, 'بلا الفاعل والقيمة السابقة لا يفيد السطر في مساءلة ولا تحقيق.', 'code', 'permission changed on /etc/shadow at 14:02', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'تسجيل محاولات الدخول الفاشلة يكشف أنماطاً لا يكشفها الناجح وحده.', '["صح","خطأ"]'::jsonb, 0, NULL, 'خمسون فشلاً ثم نجاح واحد نمط تخمين ظاهر.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'كلما زاد تفصيل السجل زادت قدرة الفريق على الكشف.', '["صح","خطأ"]'::jsonb, 1, NULL, 'التفصيل المفرط يغرق المهم في كمّ لا يُقرأ.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'مدة احتفاظ أقصر من زمن اكتشاف الاختراق تضيّع دليل الحادثة.', '["صح","خطأ"]'::jsonb, 0, NULL, 'يبدأ البحث بعد أن يكون السجل قد حُذِف بالفعل.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'سجل يستطيع مسؤول النظام تعديله يصلح دليلاً على فعله.', '["صح","خطأ"]'::jsonb, 1, NULL, 'الدليل الذي يملك المتهم تغييره لا يثبت شيئاً ضده.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'نقل السجل فور كتابته لخادم منفصل يحدّ من قدرة المهاجم على محو أثره.', '["صح","خطأ"]'::jsonb, 0, NULL, 'ما غادر الجهاز لا يبلغه من سيطر عليه بعد ذلك.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'hard', 'مقارنة حجم ملف السجل بحجمه أمس تكفي لكشف التعديل.', '["صح","خطأ"]'::jsonb, 1, NULL, 'استبدال سطر بآخر بالطول نفسه لا يغيّر الحجم، والبصمة وحدها تكشفه.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'إيقاف خدمة التسجيل حدث أمني يستحق تنبيهاً بذاته.', '["صح","خطأ"]'::jsonb, 0, NULL, 'من أراد ألا يُرى يطفئ العين أولاً.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'عتبة تنبيه ثابتة تصلح لكل الأنظمة ما دامت محسوبة بدقة.', '["صح","خطأ"]'::jsonb, 1, NULL, 'الطبيعي يختلف بين بوابة عامة وخادم إداري، فتُشتق العتبة من خط الأساس.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'medium', 'خط أساس بُني أثناء اختراق قائم يجعل نشاط المهاجم طبيعياً.', '["صح","خطأ"]'::jsonb, 0, NULL, 'فلا يُنبَّه عنه لأنه صار جزءاً من المعتاد المسجَّل.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'medium', 'عدد التنبيهات المعالَجة يومياً مقياس صادق لفاعلية المراقبة.', '["صح","خطأ"]'::jsonb, 1, NULL, 'كثرتها قد تعني ضجيجاً، والمقياس زمن كشف الحادثة الحقيقية.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'صل كل سجل بما يجيب عنه', NULL, NULL, NULL, 'التحقيق يبدأ باختيار السجل الذي يجيب سؤالك لا بقراءة الكل.', 'matching', NULL, '[{"left":"سجل التدقيق","right":"من فعل ماذا ومتى"},{"left":"سجل التطبيق","right":"أين أخفق البرنامج"},{"left":"سجل النظام","right":"ما حدث في الخدمات"},{"left":"سجل الوصول","right":"من بلغ أي مورد"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'صل كل عنصر في سطر السجل بدوره', NULL, NULL, NULL, 'سقوط أي عنصر يفقد السطر قيمته في المساءلة.', 'matching', NULL, '[{"left":"الطابع الزمني","right":"ترتيب الحدث في السلسلة"},{"left":"هوية الفاعل","right":"نسبة الفعل إلى صاحبه"},{"left":"نوع العملية","right":"ما الذي جرى فعلاً"},{"left":"القيمة السابقة","right":"ما الذي تغيّر عمّا كان"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'hard', 'صل كل ضابط سلامة بما يمنعه', NULL, NULL, NULL, 'الأربعة تحمي أبعاداً مختلفة، والسلامة تحتاجها مجتمعة.', 'matching', NULL, '[{"left":"الإضافة دون التعديل","right":"محو سطر سابق"},{"left":"البصمة على الأرشيف","right":"تغيير خفي بعد الإغلاق"},{"left":"النقل الفوري للخادم","right":"مسح السجل بعد السيطرة"},{"left":"تقييد صلاحية القراءة","right":"اطلاع لا تقتضيه المهمة"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'صل كل مؤشر بما يرجّحه', NULL, NULL, NULL, 'ثلاثة منها تُقرأ كنشاط مقصود لا كعطل تشغيلي.', 'matching', NULL, '[{"left":"فجوة زمنية في السجل","right":"تعطيل التسجيل أو حذفه"},{"left":"بصمة أرشيف مختلفة","right":"تعديل بعد الإغلاق"},{"left":"إعادة تشغيل خدمة السجل","right":"محاولة إخفاء نشاط"},{"left":"امتلاء مساحة السجل","right":"توقف تسجيل الجديد"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'medium', 'صل كل حدث بأولوية التنبيه المناسبة', NULL, NULL, NULL, 'التنبيه للنادر عالي الأثر، والباقي يُسجَّل ولا يُوقظ أحداً.', 'matching', NULL, '[{"left":"إنشاء حساب إداري","right":"تنبيه فوري عالي الأولوية"},{"left":"فشل دخول واحد","right":"تسجيل بلا تنبيه"},{"left":"إيقاف خدمة التسجيل","right":"تنبيه فوري عالي الأولوية"},{"left":"تسجيل خروج معتاد","right":"تسجيل بلا تنبيه"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'صل كل أسلوب كشف في السجلات بحدّه', NULL, NULL, NULL, 'لكل أسلوب ثمنه، ولذلك تُستخدم مجتمعة لا بديلاً عن بعضها.', 'matching', NULL, '[{"left":"الكشف بالقاعدة","right":"يعجز عن الجديد بلا قاعدة"},{"left":"الكشف بخط الأساس","right":"ينتج إنذارات كاذبة أكثر"},{"left":"الربط بين السجلات","right":"يحتاج توقيتاً موحّداً"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'صل كل مقياس بما يقيسه فعلاً', NULL, NULL, NULL, 'أول اثنين يُحكَم بهما، والثالث مضلّل وحده.', 'matching', NULL, '[{"left":"زمن الكشف","right":"من الاختراق إلى ملاحظته"},{"left":"زمن الفرز","right":"من التنبيه إلى القرار"},{"left":"عدد التنبيهات","right":"حجم الضجيج غالباً"},{"left":"نسبة الكاذب","right":"جودة ضبط القواعد"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'صل كل قرار تسجيل بمبرره', NULL, NULL, NULL, 'كل قرار يعالج خطراً بعينه في دورة حياة السجل.', 'matching', NULL, '[{"left":"توحيد التوقيت","right":"ترتيب الأحداث عبر الأجهزة"},{"left":"الجمع المركزي","right":"بقاء السجل بعد سقوط الجهاز"},{"left":"تحديد مدة الاحتفاظ","right":"تجاوز زمن اكتشاف الاختراق"},{"left":"حجب الاعتماد","right":"منع تسريبه عبر السجل"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'صل كل مرحلة من عمر السجل بضابطها', NULL, NULL, NULL, 'السلامة تُحفظ في كل مرحلة أو تسقط في أضعفها.', 'matching', NULL, '[{"left":"الكتابة","right":"إضافة دون تعديل"},{"left":"النقل","right":"قناة مؤمَّنة فور الكتابة"},{"left":"الأرشفة","right":"توقيع يثبت عدم التغيّر"},{"left":"الإتلاف","right":"بعد انتهاء مدة الاحتفاظ"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'صل كل نمط في السجل بدلالته', NULL, NULL, NULL, 'كل نمط يجتمع من أحداث كل واحد منها عادي وحده.', 'matching', NULL, '[{"left":"فشل متكرر ثم نجاح","right":"تخمين انتهى ببلوغ الحساب"},{"left":"مصدر واحد وحسابات كثيرة","right":"تعداد حسابات واستطلاع"},{"left":"إنشاء حساب ثم رفع صلاحيته","right":"تصعيد صلاحية مقصود"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'اكتب اسم الإجراء الذي يوحّد ساعات الأنظمة ليصح ترتيب الأحداث', NULL, NULL, NULL, 'اختلاف دقيقتين يقلب تسلسل سلسلة الأحداث كلها.', 'terminal', NULL, NULL, '["توحيد التوقيت","مزامنة الوقت","time synchronization","مزامنة الساعة","توحيد الساعة"]'::jsonb, 'الإجراء', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'اكتب المعيار الذي تُقاس به مدة الاحتفاظ بالسجلات', NULL, NULL, NULL, 'مدة أقصر منه تعني ضياع الدليل قبل بدء البحث.', 'terminal', NULL, NULL, '["زمن اكتشاف الاختراق","زمن الكشف","متوسط زمن الاكتشاف","مدة اكتشاف الاختراق","زمن الكشف عن الاختراق"]'::jsonb, 'المعيار', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'hard', 'اكتب اسم ممارسة جمع سجلات الأجهزة على خادم منفصل', NULL, NULL, NULL, 'أول ما يفعله المهاجم مسح سجل الجهاز الذي دخله.', 'terminal', NULL, NULL, '["الجمع المركزي","التجميع المركزي","central logging","centralized logging","السجل المركزي","المركزية"]'::jsonb, 'الممارسة', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'اكتب اسم الخاصية التي تسمح بالكتابة في السجل وتمنع تعديل ما كُتِب', NULL, NULL, NULL, 'تمنع محو سطر سابق وإن بقيت الكتابة ممكنة.', 'terminal', NULL, NULL, '["الإضافة فقط","append only","append-only","الإلحاق فقط","الكتابة بالإضافة فقط"]'::jsonb, 'الخاصية', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'hard', 'اكتب اسم القيمة التي تُحسب على محتوى الأرشيف لكشف أي تعديل لاحق', NULL, NULL, NULL, 'تغيير حرف واحد يقلبها، بخلاف الحجم ووقت التعديل.', 'terminal', NULL, NULL, '["البصمة","بصمة التلبيد","hash","قيمة التلبيد","البصمة الرقمية"]'::jsonb, 'الأداة', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'اكتب اسم العملية التي تغلق ملف السجل دورياً وتبدأ غيره', NULL, NULL, NULL, 'الملف المغلق أسهل أرشفة وتوقيعاً وأقل عرضة للتلف.', 'terminal', NULL, NULL, '["تدوير السجلات","التدوير","log rotation","تدوير ملفات السجل","دوران السجلات"]'::jsonb, 'العملية', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'اكتب اسم المرجع الذي تُشتق منه عتبة التنبيه في كل نظام', NULL, NULL, NULL, 'الطبيعي يختلف بين بوابة عامة وخادم إداري.', 'terminal', NULL, NULL, '["خط الأساس","الخط الأساسي","baseline","خط أساس النظام","المعتاد"]'::jsonb, 'المرجع', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'اكتب اسم الظاهرة التي يعتاد فيها الفريق إغلاق التنبيهات بلا نظر', NULL, NULL, NULL, 'العلاج ضبط القواعد لا زيادة عدد من يقرؤها.', 'terminal', NULL, NULL, '["إرهاق التنبيهات","إرهاق الإنذارات","alert fatigue","تعب التنبيهات","إجهاد التنبيهات"]'::jsonb, 'الظاهرة', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'اكتب اسم العملية التي تجمع حدثين من سجلين لتكشف نمطاً واحداً', NULL, NULL, NULL, 'إنشاء حساب ثم رفع صلاحيته: كل حدث وحده عادي.', 'terminal', NULL, NULL, '["الربط","ربط الأحداث","correlation","الارتباط","ربط السجلات"]'::jsonb, 'العملية', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'medium', 'اكتب اسم المقياس الذي يحكم فاعلية المراقبة لا عدد التنبيهات', NULL, NULL, NULL, 'ألف تنبيه مغلق يومياً قد يعني غرقاً في الضجيج لا أماناً.', 'terminal', NULL, NULL, '["زمن الكشف","زمن كشف الحادثة","time to detect","مدة الكشف","زمن الاكتشاف"]'::jsonb, 'المقياس', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'hard', 'أي مما يلي يجب أن يحمله سطر سجل التدقيق؟', '["هوية من نفّذ العملية","الطابع الزمني الموحّد","كلمة المرور المستخدمة","حجم ملف السجل الحالي"]'::jsonb, NULL, '[0,1]'::jsonb, 'الاعتماد لا يُسجَّل إطلاقاً، وحجم الملف ليس خاصية للحدث.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'hard', 'أي مما يلي يبرّر الجمع المركزي للسجلات؟', '["تقليل مساحة القرص المحلي فقط","إلغاء الحاجة لتوحيد التوقيت","بقاء السجل بعد العبث بالجهاز","إتاحة الربط بين أجهزة مختلفة"]'::jsonb, NULL, '[2,3]'::jsonb, 'المركزية تزيد الحاجة لتوحيد التوقيت ولا تلغيها.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'hard', 'أي مما يلي يحفظ سلامة السجل؟', '["الكتابة بالإضافة دون تعديل","منح كل إداري صلاحية تحريره","توقيع الأرشيف بعد إغلاقه","حذف الأسطر القديمة أسبوعياً"]'::jsonb, NULL, '[0,2]'::jsonb, 'التحرير والحذف يهدمان قيمة السجل كدليل.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'hard', 'أي مما يلي يُقرأ كمؤشر على إخفاء أثر؟', '["تدوير السجل في موعده المعتاد","فجوة زمنية في سجل يعمل","أرشفة السجل الشهري المعتادة","إعادة تشغيل خدمة التسجيل فجأة"]'::jsonb, NULL, '[1,3]'::jsonb, 'التدوير والأرشفة إجراءان مجدولان، والفجوة والإطفاء ليسا كذلك.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'أي مما يلي يستحق تنبيهاً فورياً؟', '["إنشاء حساب إداري جديد","تسجيل خروج مستخدم عادي","قراءة ملف عام مشترك","إيقاف خدمة التسجيل"]'::jsonb, NULL, '[0,3]'::jsonb, 'التنبيه للنادر عالي الأثر لا للمتكرر العادي.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'أي مما يلي صحيح عن الإنذارات الكاذبة؟', '["وجودها دليل على دقة الكشف","تُعالَج بضبط القواعد","كثرتها تُمرِّر التنبيه الحقيقي","تُعالَج بزيادة عدد المحللين"]'::jsonb, NULL, '[1,2]'::jsonb, 'زيادة القارئين تؤجّل المشكلة ولا تحلّها.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'أي مما يلي يقيس فاعلية المراقبة؟', '["زمن كشف الحادثة","زمن الفرز حتى القرار","حجم السجلات المخزّنة","عدد القواعد المفعّلة"]'::jsonb, NULL, '[0,1]'::jsonb, 'الحجم وعدد القواعد يصفان الجهد لا النتيجة.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'أي مما يلي يجب تسجيله عند تغيير صلاحية؟', '["سرعة تنفيذ العملية","حجم قاعدة الحسابات","هوية من نفّذ التغيير","القيمة قبل التغيير"]'::jsonb, NULL, '[2,3]'::jsonb, 'بلا الفاعل والقيمة السابقة لا يفيد السطر في مساءلة.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'أي مما يلي خطر في ترك السجل على الجهاز وحده؟', '["يمحوه من سيطر على الجهاز","يصعب توحيد صيغته لاحقاً","يضيع بسقوط قرص الجهاز","يستهلك ذاكرة الجهاز كلها"]'::jsonb, NULL, '[0,2]'::jsonb, 'الخطران يمسّان بقاء الدليل نفسه لا شكله ولا أداء الجهاز.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'أي مما يلي شرط في قاعدة تنبيه صالحة؟', '["تغطية أكبر عدد من الأحداث","عتبة مشتقة من خط الأساس","تنبيه على كل خطأ دخول","فعل ممكن يترتب على التنبيه"]'::jsonb, NULL, '[1,3]'::jsonb, 'التغطية الشاملة والتنبيه على كل خطأ ينتجان ضجيجاً يُغلَق بلا نظر.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'medium', 'رتّب مراحل دورة حياة السجل', '["كتابة الحدث على المضيف","نقله للخادم المركزي","أرشفته بعد إغلاق الملف","إتلافه بعد مدة الاحتفاظ"]'::jsonb, NULL, NULL, 'الإتلاف مرحلة مخطَّطة لا إهمال، وتسبقها الأرشفة الموقَّعة.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'hard', 'رتّب خطوات إعداد التسجيل على نظام جديد', '["تحديد الأحداث الواجب تسجيلها","توحيد توقيت النظام","توجيه السجل للخادم المركزي","تحديد مدة الاحتفاظ"]'::jsonb, NULL, NULL, 'توحيد التوقيت قبل التوجيه وإلا وصلت الأحداث بترتيب خاطئ.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'hard', 'رتّب خطوات التحقق من سلامة أرشيف سجل', '["جلب البصمة المحفوظة عند الإغلاق","حساب بصمة الأرشيف الحالي","مقارنة القيمتين","التحقيق عند اختلافهما"]'::jsonb, NULL, NULL, 'البصمة المحفوظة تُجلب أولاً لأنها المرجع الذي يُقاس عليه.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'hard', 'رتّب خطوات التعامل مع فجوة مكتشفة في السجل', '["تحديد بداية الفجوة ونهايتها","مراجعة حالة خدمة التسجيل","البحث عن مصدر بديل للفترة","توثيق الفجوة في التقرير"]'::jsonb, NULL, NULL, 'المصدر البديل يعوّض ما ضاع، والتوثيق يثبت حدود ما لا يُعوَّض.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'رتّب خطوات بناء قاعدة تنبيه جديدة', '["تحديد السلوك المراد كشفه","قياس معتاده من خط الأساس","ضبط العتبة والاختبار","تفعيلها مع فعل مترتب عليها"]'::jsonb, NULL, NULL, 'التفعيل قبل قياس المعتاد ينتج ضجيجاً يومياً بلا فائدة.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'رتّب خطوات معالجة تنبيه وارد', '["قراءة التنبيه وسياقه","مراجعة الأحداث المرتبطة به","تحديد كاذب أم حقيقي","التصعيد أو الإغلاق بالتوثيق"]'::jsonb, NULL, NULL, 'الإغلاق يُوثَّق أيضاً، وإلا تكرر التنبيه بلا تعلّم.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'medium', 'رتّب خطوات علاج كثرة الإنذارات الكاذبة', '["حصر القواعد الأكثر ضجيجاً","مراجعة سبب إطلاقها","ضبط عتبتها أو شرطها","قياس الأثر بعد الضبط"]'::jsonb, NULL, NULL, 'القياس بعد الضبط يمنع أن يخفي التحسين قاعدة صارت لا تعمل.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Sources', 'hard', 'رتّب خطوات ترتيب حدث عبر عدة أجهزة', '["التحقق من توحيد ساعاتها","تصحيح الفوارق المعروفة","دمج الأحداث في خط زمني","قراءة التسلسل الناتج"]'::jsonb, NULL, NULL, 'الدمج قبل تصحيح الفوارق ينتج تسلسلاً مقلوباً يبدو سليماً.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Log Integrity', 'medium', 'رتّب خطوات تأمين سجل على مضيف', '["تقييد أذونات ملف السجل","جعله قابلاً للإضافة فقط","توجيهه لخادم منفصل","التنبيه عند إيقاف خدمته"]'::jsonb, NULL, NULL, 'التنبيه آخراً لأنه يحرس الضوابط الثلاثة التي سبقته.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 5, 'Detection and Alerting', 'hard', 'رتّب خطوات التحقق من قاعدة صامتة منذ مدة', '["مراجعة أنها ما زالت مفعّلة","توليد الحدث الذي تكشفه عمداً","التحقق من وصول التنبيه","إصلاحها أو توثيق صحتها"]'::jsonb, NULL, NULL, 'الصمت قد يعني سلامة البيئة وقد يعني قاعدة معطّلة.', 'ordering', NULL, NULL, NULL, NULL, 60, true);

-- تحقق فوري بعد الإدخال
select level, type, count(*)
from public.questions
where track_id = 'CyberSecurity'
  and section_id = 'System and Operating System Security'
  and level = 5
  and is_active
group by level, type
order by type;

commit;
