-- الأمن السيبراني · S3 أمن الأنظمة · L3 الصلاحيات والهوية
-- 90 سؤالاً · وُلِّد آلياً بعد اجتياز فحوصات عقد الجودة كاملة:
--   توزيع الأنواع 30/10×6 · مواضع الإجابة 8/8/7/7 · صفر فجوة طول ≥7
--   صفر تكرار داخل الدفعة وعبر المسار · كل الأنواع مكتملة البنية
-- التشغيل: لوحة Supabase ← SQL Editor ← الصق ونفّذ.

begin;

insert into public.questions
  (track_id, section_id, level, topic, difficulty, question, options, correct_answer, correct_answers, explanation, type, code_snippet, pairs, expected_answers, prompt_label, time_limit, is_active)
values
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'easy', 'ما الذي يميّز التحكم التقديري؟', '["مالك المورد هو من يمنح الوصول","النظام يفرض تصنيفاً يحكم الوصول","الصلاحية تُربط بالدور لا بالشخص","القرار يُبنى على سمات الطلب وسياقه"]'::jsonb, 0, NULL, 'التقدير للمالك، ولذلك يوصف بأنه أمرن النماذج وأقلها ضبطاً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'ما الذي يميّز التحكم الإلزامي في الوصول؟', '["المالك يمنح ويمنع كما يرى","سياسة النظام تعلو على رغبة المالك","الوصول يتبع دور الموظف الوظيفي","الوصول يُقرَّر من وقت الطلب وموقعه"]'::jsonb, 1, NULL, 'الإلزام يعني أن المالك نفسه لا يستطيع مشاركة ما صنّفه النظام.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'easy', 'على أي أساس يُمنح الوصول في نموذج الأدوار؟', '["على ملكية الموظف للمورد","على تصنيف أمني يفرضه النظام","على الدور الوظيفي الذي يشغله","على سمات الجهاز ووقت الاتصال"]'::jsonb, 2, NULL, 'الصلاحية تُعلَّق على الدور، والموظف يرثها بانضمامه إليه.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'ما الذي يميّز النموذج القائم على السمات؟', '["يمنح المالك حرية المشاركة","يعتمد تصنيفاً إلزامياً للموارد","يوزّع الصلاحيات على أدوار ثابتة","يقرر من سمات المستخدم والسياق"]'::jsonb, 3, NULL, 'السمات تسمح بشرط مركّب كالوقت والموقع وحالة الجهاز معاً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'لماذا يُفضَّل نموذج الأدوار في المؤسسات الكبيرة؟', '["يضبط الوصول بعدد أدوار محدود","يلغي الحاجة لمراجعة الصلاحيات","يمنع تصعيد الصلاحيات نهائياً","يجعل كل مستخدم مالكاً لموارده"]'::jsonb, 0, NULL, 'إدارة عشرة أدوار أيسر من إدارة آلاف الحسابات فرداً فرداً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'hard', 'ما الخلل الذي يصيب نموذج الأدوار مع الزمن؟', '["يفقد النظام قدرته على التسجيل","تتضخم الأدوار حتى تفقد معناها","تصير السمات بديلاً عن الهوية","يمنع إنشاء الأدوار الجديدة تماماً"]'::jsonb, 1, NULL, 'إنشاء دور لكل استثناء ينتهي بأدوار بعدد الموظفين، وهو انفجار الأدوار.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'ما مبدأ أقل صلاحية؟', '["منح كل مستخدم صلاحية القراءة","منع الوصول حتى يطلبه المستخدم","منح ما تقتضيه المهمة لا أكثر","حصر الصلاحيات في فريق واحد"]'::jsonb, 2, NULL, 'المعيار حاجة المهمة، فما زاد عنها مساحة ضرر بلا فائدة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'hard', 'ما الفرق بين أقل صلاحية والحاجة إلى المعرفة؟', '["الأول للأنظمة والثاني للشبكات","الأول مؤقت والثاني دائم دوماً","الأول تقني والثاني إجراء ورقي","الأول يحد الفعل والثاني يحد الاطلاع"]'::jsonb, 3, NULL, 'قد تملك صلاحية القراءة تقنياً ولا يخصّك الملف، فيمنعك المبدأ الثاني.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'لماذا يكون المنع هو القاعدة الافتراضية؟', '["ليُسمح بالمعروف ويُمنع سواه","ليقل عدد القواعد المكتوبة","ليمر ما لم يُصنَّف خطراً بعد","ليصير التسجيل غير ضروري"]'::jsonb, 0, NULL, 'السماح افتراضياً يمرر كل خطر لم يُكتشف بعد، والمنع يعكس العبء.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'ما الذي تسجّله قائمة التحكم في الوصول؟', '["ما تملكه هذي الهوية من موارد","من يملك الوصول لهذا المورد","ترتيب تنفيذ العمليات على المورد","سجل محاولات الوصول الفاشلة"]'::jsonb, 1, NULL, 'القائمة معلَّقة على المورد وتعدّد من يصل إليه، لا العكس.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'easy', 'ما المقصود بالتصعيد الرأسي للصلاحيات؟', '["الوصول لبيانات مستخدم مماثل","نقل الجلسة إلى جهاز آخر","الانتقال لصلاحية أعلى من الممنوحة","تشغيل البرنامج في بيئة معزولة"]'::jsonb, 2, NULL, 'الرأسي يصعد في المستوى، والأفقي يتحرك في المستوى نفسه.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'ما المقصود بالتصعيد الأفقي للصلاحيات؟', '["بلوغ صلاحيات مدير النظام","رفع صلاحية العملية أثناء عملها","تجاوز طلب التأكيد الإداري","الوصول لحساب في المستوى نفسه"]'::jsonb, 3, NULL, 'قراءة ملفات زميل بمستواك اختراق خصوصية وإن لم ترتفع صلاحيتك.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'ما الخطر في ملف تنفيذي يحمل بت التنفيذ بهوية المالك؟', '["يعمل بصلاحية مالكه لا مشغّله","يمنع المستخدم من تشغيله","يمنح المالك ملكية كل الملفات","يخفي الملف عن قوائم المجلد"]'::jsonb, 0, NULL, 'لو كان المالك الجذر، صار كل خلل في البرنامج طريقاً لصلاحيته.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'hard', 'لماذا تخطر قاعدة سماح تنتهي بحرف بدل؟', '["تبطئ تنفيذ الأمر المسموح به","تجعل الأمر يقبل وسائط لم تُقصد","تلغي تسجيل الأمر في السجلات","تمنع الأمر من العمل أصلاً"]'::jsonb, 1, NULL, 'الحرف البديل يقبل وسائط لم يتوقعها الكاتب فينفَّذ أمر آخر بصلاحيته.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'hard', 'لماذا يخطر السماح بأمر يفتح محرراً بصلاحية عالية؟', '["المحرر يستهلك ذاكرة كبيرة","المحرر يعطّل تسجيل الأحداث","المحرر يشغّل أوامر من داخله","المحرر يغيّر مالك الملفات كلها"]'::jsonb, 2, NULL, 'كثير من المحررات تنفّذ أوامر نظام، فترث تلك الأوامر صلاحية المحرر.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'ما خطر حساب خدمة يعمل بصلاحية إدارية؟', '["يستهلك ترخيصاً إضافياً للنظام","يمنع تشغيل الخدمة عند الإقلاع","يبطئ استجابة الخدمة للطلبات","يورّث الخدمة المخترقة صلاحيته"]'::jsonb, 3, NULL, 'الخدمة بابٌ للشبكة، فمنحها صلاحية إدارية يجعل اختراقها اختراقاً للنظام.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'لماذا يُعد مسار قابل للكتابة خطراً على التنفيذ؟', '["يسمح بزرع ملف يُنفَّذ بدل الأصلي","يبطئ البحث عن الملف المطلوب","يمنع النظام من العثور على الأمر","يعطّل صلاحيات المجلد الأصلية"]'::jsonb, 0, NULL, 'إن سبق المجلد المكتوب غيره في الترتيب، نُفِّذ المزروع أولاً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'ما الغرض من طلب التأكيد قبل العمليات الإدارية؟', '["تشفير الملفات قبل تعديلها","منع رفع الصلاحية بلا علم صاحبها","إلغاء الحاجة لحساب إداري","تسجيل كل أمر في ملف منفصل"]'::jsonb, 1, NULL, 'الغرض ألا ترتفع الصلاحية صامتة، لا أن يكون حاجزاً لا يُخترق.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'hard', 'ما الذي يمنحه انتحال رمز جلسة مستخدم آخر؟', '["كلمة مرور ذلك المستخدم نصاً","نسخة من ملفاته على القرص","تنفيذ العمليات بهويته وصلاحياته","حق تغيير سياسة النظام كاملة"]'::jsonb, 2, NULL, 'الرمز يمثّل الهوية أثناء الجلسة، فمن حمله تصرّف بها بلا كلمة مرور.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'ما أنفع إجراء يقلّل مساحة التصعيد؟', '["زيادة طول كلمات المرور الإدارية","تشغيل الخدمات كلها بحساب واحد","إلغاء تسجيل الأوامر الإدارية","حذف الصلاحيات الزائدة عن الحاجة"]'::jsonb, 3, NULL, 'التصعيد يستغل صلاحية موجودة، فتقليلها يقلّص ما يمكن استغلاله.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'easy', 'ما الفرق بين التعريف والتوثيق؟', '["الأول ادعاء هوية والثاني إثباتها","الأول للأجهزة والثاني للأشخاص","الأول يمنح الوصول والثاني يمنعه","الأول مؤقت والثاني دائم للحساب"]'::jsonb, 0, NULL, 'اسم المستخدم ادعاء، وكلمة المرور أو العامل الثاني إثبات.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'ما الذي يجيب عنه التخويل بعد التوثيق؟', '["من يدّعي هذي الهوية الآن","ما الذي يُسمح لهذي الهوية به","هل أثبت المستخدم هويته فعلاً","متى انتهت صلاحية كلمة المرور"]'::jsonb, 1, NULL, 'التوثيق يثبت من أنت، والتخويل يحدد ما تستطيع فعله.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'لماذا تخطر الحسابات اليتيمة بعد مغادرة الموظف؟', '["تستهلك مساحة على خادم الدليل","تمنع إنشاء حساب للموظف الجديد","تبقى صالحة بلا صاحب يراقبها","تعطّل مزامنة كلمات المرور"]'::jsonb, 2, NULL, 'حساب حيّ لا يلاحظ أحد استخدامه هو أفضل ما يبحث عنه المهاجم.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'ما الغرض من مراجعة الصلاحيات الدورية؟', '["توحيد كلمات المرور بين الأنظمة","زيادة صلاحيات الموظف الأقدم","إلغاء الحاجة للتحقق متعدد العوامل","سحب ما لم تعد المهمة تقتضيه"]'::jsonb, 3, NULL, 'الصلاحيات تتراكم مع تنقّل الموظف، والمراجعة تعيدها لحاجته الحالية.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'hard', 'ما الذي يسمّى تراكم الصلاحيات مع تنقّل الموظف؟', '["زحف الامتيازات عبر المناصب","توسّع نطاق التصنيف الأمني","انفجار عدد الأدوار الوظيفية","ازدواج الهوية بين الأنظمة"]'::jsonb, 0, NULL, 'ينتقل الموظف فيأخذ صلاحيات الوظيفة الجديدة ويحتفظ بالقديمة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'لماذا تُمنع الحسابات المشتركة بين عدة موظفين؟', '["تستهلك عدد التراخيص أسرع","تُسقط نسبة الفعل إلى فاعله","تُبطئ عملية التوثيق للجميع","تمنع تطبيق سياسة كلمات المرور"]'::jsonb, 1, NULL, 'بلا نسبة الفعل لفاعل بعينه يسقط التتبّع والمساءلة معاً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'لماذا تُخزَّن كلمات المرور مُلبَّدة لا مشفّرة؟', '["التلبيد أسرع في التحقق منها","التشفير يحتاج مساحة أكبر بكثير","التلبيد لا يُعكس لاستخراج الأصل","التلبيد يمنع تكرار كلمة المرور"]'::jsonb, 2, NULL, 'النظام لا يحتاج استرجاع الكلمة أصلاً، وإنما مطابقة بصمتها.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'hard', 'ما الذي تضيفه الملّاحة إلى تلبيد كلمات المرور؟', '["تقصّر زمن التحقق من الكلمة","تسمح باسترجاع الكلمة عند النسيان","تمنع إدخال كلمة مرور ضعيفة","تجعل بصمة الكلمة المكررة مختلفة"]'::jsonb, 3, NULL, 'بلا ملّاحة يعطي المستخدمان بالكلمة نفسها بصمة واحدة تكشفهما معاً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'ما الغرض من فصل المهام بين شخصين؟', '["اشتراط تواطؤ اثنين لا قرار واحد","تسريع إنجاز العملية الحساسة","توزيع كلمة المرور على طرفين","إلغاء الحاجة لسجل العمليات"]'::jsonb, 0, NULL, 'ما يحتاج شخصين أصعب بكثير مما يقرره واحد بمفرده.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'hard', 'ما شرط حساب الطوارئ الإداري ليبقى مقبولاً؟', '["أن يُوزَّع على فريق الدعم كاملاً","أن يُراقَب ويُنبَّه عند كل استخدام","أن يُستخدم في المهام اليومية أيضاً","أن تُعطَّل عنه سياسة كلمات المرور"]'::jsonb, 1, NULL, 'وجوده ضرورة تشغيلية، وسلامته في أن استخدامه لا يمر صامتاً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'ما الذي يكشفه بت الصلاحية في هذا الملف؟', '["يعمل بصلاحية الجذر لأي مشغّل","لا يستطيع تشغيله إلا الجذر","يمنع تعديله من أي مستخدم","ينسخ صلاحياته للملفات الناتجة"]'::jsonb, 0, NULL, 'حرف s مكان x في حقل المالك يعني التنفيذ بهوية المالك وهو الجذر.', 'code', '-rwsr-xr-x  1 root root  54280  /usr/local/bin/backup', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'hard', 'ما الخلل في قاعدة السماح هذي؟', '["تمنع المستخدم من تشغيل الأمر","تتيح تنفيذ أي أمر عبر خيار فيه","تحصر الأمر في مجلد واحد فقط","تسجّل الأمر مرتين في السجل"]'::jsonb, 1, NULL, 'الأمر يقبل خياراً ينفّذ أوامر أخرى، فترث صلاحية الجذر بلا كلمة مرور.', 'code', 'dev  ALL=(ALL) NOPASSWD: /usr/bin/find', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'ما الذي تعنيه هذي الأذونات على مجلد سجلات؟', '["الجذر وحده يكتب في المجلد","الكل يقرأ ولا أحد يكتب فيه","الكل يقرأ ويكتب ويحذف فيه","المجموعة تقرأ والباقي ممنوع"]'::jsonb, 2, NULL, 'ثلاث مجموعات كاملة الصلاحيات تعني أن أي مستخدم يعدّل السجل أو يمحوه.', 'code', 'drwxrwxrwx  2 root root  4096  /var/log/app', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'ما الذي يدل عليه سطر الحساب هذا؟', '["حساب إداري بصلاحيات كاملة","حساب موظف انتهى عقده أخيراً","حساب ضيف بصلاحية قراءة فقط","حساب خدمة بلا دخول تفاعلي"]'::jsonb, 3, NULL, 'صدفة nologin تمنع الجلسة التفاعلية، وهي ضبط سليم لحساب خدمة.', 'code', 'svc_backup:x:998:998:Backup Service:/var/lib/backup:/usr/sbin/nologin', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'hard', 'ما الامتياز الخطر في هذا المخرج؟', '["صلاحية انتحال هوية عميل آخر","صلاحية تتبّع تغيّر المجلدات","صلاحية إيقاف النظام عن بُعد","صلاحية قراءة سجل الأحداث"]'::jsonb, 0, NULL, 'الانتحال يتيح تقمّص رمز حساب أعلى فيصير طريقاً لتصعيد الصلاحية.', 'code', 'PRIVILEGES INFORMATION
SeImpersonatePrivilege        Enabled
SeChangeNotifyPrivilege       Enabled', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'ما الذي تصفه قاعدة الوصول هذي؟', '["نموذج تقديري يملكه صاحب المورد","نموذج سمات يجمع أكثر من شرط","نموذج إلزامي بتصنيف ثابت","نموذج أدوار بلا شروط إضافية"]'::jsonb, 1, NULL, 'اجتماع الدور وحالة الجهاز والوقت في قرار واحد هو جوهر نموذج السمات.', 'code', 'allow: role=finance AND device=managed AND time=08:00-17:00', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'ما الذي يشير إليه هذا السجل عن حساب؟', '["حساب طوارئ مضبوط بشكل سليم","حساب جديد لم يُفعَّل بعد","حساب خامل بصلاحية إدارية حيّة","حساب خدمة يعمل بلا انقطاع"]'::jsonb, 2, NULL, 'خمول طويل مع صلاحية إدارية مفعّلة أخطر تركيبة في الدليل.', 'code', 'last login: 412 days ago
status: enabled
groups: domain-admins', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'لماذا يخطر ترتيب المسارات هذا؟', '["يمنع العثور على الأوامر النظامية","يبطئ تنفيذ كل أمر في النظام","يلغي صلاحيات المجلدات التالية","يبحث في مجلد يكتب فيه الجميع أولاً"]'::jsonb, 3, NULL, 'مجلد مؤقت مفتوح للكتابة في مقدمة الترتيب يعني تنفيذ أمر مزروع.', 'code', 'PATH=/tmp:/usr/local/bin:/usr/bin:/bin', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'hard', 'ما العيب في تخزين كلمة المرور هكذا؟', '["التخزين بلا ملّاحة فالمكرر يتطابق","البصمة قصيرة فتُحسب بسرعة","الخوارزمية تعيد النص الأصلي","الحقل يقبل كلمة مرور فارغة"]'::jsonb, 0, NULL, 'بصمة بلا ملّاحة تعطي القيمة نفسها لكل من اختار الكلمة نفسها.', 'code', 'user: sara
stored: 5f4dcc3b5aa765d61d8327deb882cf99', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'ما الذي يمنعه هذا الترتيب في قائمة القواعد؟', '["يمنع المتدرب من الوصول تماماً","لا يمنع المتدرب إن كان في القسم","يمنع القسم كله من الوصول","يوقف تطبيق القاعدتين معاً"]'::jsonb, 1, NULL, 'أول قاعدة تنطبق تُطبَّق، فالسماح العام يسبق المنع الخاص فيبطله.', 'code', '1) allow all from finance
2) deny user=intern01', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'easy', 'في النموذج الإلزامي لا يستطيع مالك الملف مشاركته كما يشاء.', '["صح","خطأ"]'::jsonb, 0, NULL, 'السياسة تعلو على المالك، وهذا ما يميّز الإلزامي عن التقديري.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'نموذج الأدوار يغني عن مراجعة الصلاحيات الدورية.', '["صح","خطأ"]'::jsonb, 1, NULL, 'الأدوار نفسها تتضخم وتتراكم، فالمراجعة تبقى لازمة.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'التصعيد الأفقي لا يرفع مستوى الصلاحية لكنه اختراق فعلي.', '["صح","خطأ"]'::jsonb, 0, NULL, 'الوصول لبيانات مستخدم آخر خرق للسرية وإن تساوى المستويان.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'كل ملف يحمل بت التنفيذ بهوية المالك يعد ثغرة بذاته.', '["صح","خطأ"]'::jsonb, 1, NULL, 'بعضها ضروري لعمل النظام، والخطر في الزائد عن الحاجة وفي خلله.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'hard', 'طلب التأكيد الإداري في ويندوز حاجز أمني لا يمكن تجاوزه.', '["صح","خطأ"]'::jsonb, 1, NULL, 'غرضه منع الرفع الصامت للصلاحية، وله طرق تجاوز معروفة.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'easy', 'التوثيق يثبت الهوية والتخويل يحدد المسموح لها.', '["صح","خطأ"]'::jsonb, 0, NULL, 'الأول يجيب من أنت، والثاني يجيب ما الذي تستطيعه.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'الحساب المشترك مقبول ما دامت كلمة مروره قوية.', '["صح","خطأ"]'::jsonb, 1, NULL, 'القوة لا تعالج سقوط المساءلة، فلا يُعرف من فعل ماذا.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'تعطيل حساب المغادر فوراً أهم من حذفه في اليوم نفسه.', '["صح","خطأ"]'::jsonb, 0, NULL, 'التعطيل يقطع الوصول حالاً ويبقي الأثر اللازم للتحقيق لاحقاً.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'hard', 'التلبيد بلا ملّاحة يكفي لحماية كلمات المرور المخزّنة.', '["صح","خطأ"]'::jsonb, 1, NULL, 'الجداول الجاهزة تكسر البصمات غير المملّحة بسرعة عالية.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'المنع الافتراضي يعني السماح بما عُرِف ومنع ما سواه.', '["صح","خطأ"]'::jsonb, 0, NULL, 'وبذلك لا يمر الخطر الذي لم يُكتشف بعد بلا اعتراض.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'صل كل نموذج تحكم بأساس قراره', NULL, NULL, NULL, 'أساس القرار هو ما يفرّق النماذج، لا شدّتها.', 'matching', NULL, '[{"left":"التقديري","right":"قرار مالك المورد"},{"left":"الإلزامي","right":"تصنيف يفرضه النظام"},{"left":"الأدوار","right":"الدور الوظيفي للمستخدم"},{"left":"السمات","right":"سمات الطلب وسياقه"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'صل كل مبدأ بما يقيّده', NULL, NULL, NULL, 'كل مبدأ يقيّد بعداً مختلفاً، ولذلك تُطبَّق مجتمعة.', 'matching', NULL, '[{"left":"أقل صلاحية","right":"ما يستطيع المستخدم فعله"},{"left":"الحاجة إلى المعرفة","right":"ما يحق له الاطلاع عليه"},{"left":"فصل المهام","right":"ما ينفرد به شخص واحد"},{"left":"المنع الافتراضي","right":"ما لم يُسمح به صراحة"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'صل كل طريق تصعيد بما يستغله', NULL, NULL, NULL, 'كل طريق يستغل ثقة قائمة في النظام لا خللاً في التشفير.', 'matching', NULL, '[{"left":"بت هوية المالك","right":"تنفيذ بصلاحية مالك الملف"},{"left":"قاعدة سماح واسعة","right":"أمر يشغّل أوامر أخرى"},{"left":"مسار قابل للكتابة","right":"ملف مزروع يسبق الأصلي"},{"left":"انتحال الرمز","right":"تقمّص هوية جلسة قائمة"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'easy', 'صل كل مرحلة من مراحل الوصول بسؤالها', NULL, NULL, NULL, 'الأربع متتابعة، وسقوط واحدة يفقد ما بعدها معناه.', 'matching', NULL, '[{"left":"التعريف","right":"من تدّعي أنك؟"},{"left":"التوثيق","right":"كيف تثبت ذلك؟"},{"left":"التخويل","right":"ما المسموح لك؟"},{"left":"المحاسبة","right":"ما الذي فعلته؟"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'صل كل حالة حساب بخطرها', NULL, NULL, NULL, 'الخطر في كلها أن الصلاحية باقية والرقابة غائبة.', 'matching', NULL, '[{"left":"حساب يتيم","right":"صالح بلا صاحب يراقبه"},{"left":"حساب مشترك","right":"فعل بلا فاعل معروف"},{"left":"حساب خامل إداري","right":"صلاحية عالية بلا استخدام"},{"left":"حساب خدمة إداري","right":"خدمة تورّث صلاحيتها"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'hard', 'صل كل خلل بنموذج الوصول الذي يصيبه', NULL, NULL, NULL, 'لكل نموذج عيب يقابل ميزته، والاختيار مقايضة لا تفضيل مطلق.', 'matching', NULL, '[{"left":"انفجار الأدوار","right":"نموذج الأدوار"},{"left":"مشاركة المالك بلا ضابط","right":"النموذج التقديري"},{"left":"جمود التصنيف","right":"النموذج الإلزامي"},{"left":"تعقيد كتابة الشروط","right":"نموذج السمات"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'صل كل إجراء وقائي بما يعالجه', NULL, NULL, NULL, 'كل إجراء يغلق طريقاً بعينه، ولا يغني عن غيره.', 'matching', NULL, '[{"left":"حصر قواعد السماح","right":"أوامر تنفّذ أوامر أخرى"},{"left":"مراجعة ملفات هوية المالك","right":"تنفيذ بصلاحية أعلى"},{"left":"تثبيت مسارات البحث","right":"ملف مزروع يُنفَّذ أولاً"},{"left":"فصل حسابات الخدمات","right":"وراثة صلاحية إدارية"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'صل كل مصطلح تخزين بمعناه', NULL, NULL, NULL, 'الثلاثة الأولى تتكامل، والرابع خطأ لا يُبرَّر.', 'matching', NULL, '[{"left":"التلبيد","right":"بصمة لا تُعكس للأصل"},{"left":"الملّاحة","right":"قيمة تميّز المتكرر"},{"left":"التمديد","right":"إبطاء الحساب عمداً"},{"left":"النص الصريح","right":"تخزين مرفوض تماماً"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'hard', 'صل كل مرحلة في دورة حياة الهوية بإجرائها', NULL, NULL, NULL, 'أكثر ما يُهمل مرحلة التنقّل، ومنها يبدأ زحف الصلاحيات.', 'matching', NULL, '[{"left":"الالتحاق","right":"إنشاء الحساب بأقل صلاحية"},{"left":"التنقّل","right":"سحب صلاحيات الوظيفة السابقة"},{"left":"المراجعة","right":"إقرار الحاجة أو الإلغاء"},{"left":"المغادرة","right":"تعطيل فوري ثم أرشفة"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'صل كل بنية بما تجيب عنه', NULL, NULL, NULL, 'الأولى معلَّقة على المورد والثانية على الهوية والثالثة تجمعهما.', 'matching', NULL, '[{"left":"قائمة التحكم","right":"من يصل لهذا المورد"},{"left":"قائمة القدرات","right":"ما تصل إليه هذي الهوية"},{"left":"مصفوفة الوصول","right":"العلاقة الكاملة بينهما"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'easy', 'اكتب اسم المبدأ الذي يمنح المستخدم ما تقتضيه مهمته فقط', NULL, NULL, NULL, 'ما زاد عن حاجة المهمة مساحة ضرر بلا فائدة.', 'terminal', NULL, NULL, '["أقل صلاحية","مبدأ أقل صلاحية","least privilege","الحد الأدنى من الصلاحيات","أقل امتياز"]'::jsonb, 'المبدأ', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'اكتب اسم نموذج التحكم الذي تُربط فيه الصلاحية بالوظيفة لا بالشخص', NULL, NULL, NULL, 'المستخدم يرث صلاحية الدور بانضمامه إليه.', 'terminal', NULL, NULL, '["نموذج الأدوار","التحكم بالأدوار","RBAC","الأدوار","التحكم في الوصول المبني على الأدوار"]'::jsonb, 'النموذج', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'اكتب المصطلح الذي يصف انتقال المهاجم لصلاحية أعلى مما مُنح', NULL, NULL, NULL, 'الرأسي يصعد في المستوى، والأفقي يتحرك في المستوى نفسه.', 'terminal', NULL, NULL, '["تصعيد الصلاحيات","تصعيد الامتيازات","privilege escalation","رفع الصلاحيات","التصعيد الرأسي"]'::jsonb, 'المصطلح', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'hard', 'اكتب وصف الملف الذي يُنفَّذ بصلاحية مالكه لا بصلاحية مشغّله', NULL, NULL, NULL, 'لو كان المالك الجذر صار كل خلل فيه طريقاً لصلاحيته.', 'terminal', NULL, NULL, '["SUID","بت هوية المالك","setuid","ملف SUID","بت SUID"]'::jsonb, 'الوصف', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'easy', 'اكتب اسم المرحلة التي تحدد ما يُسمح للهوية به بعد إثباتها', NULL, NULL, NULL, 'التوثيق يجيب من أنت، والتخويل يجيب ما تستطيعه.', 'terminal', NULL, NULL, '["التخويل","التفويض","authorization","الصلاحيات","منح الصلاحية"]'::jsonb, 'المرحلة', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'اكتب وصف الحساب الذي بقي فعّالاً بعد مغادرة صاحبه', NULL, NULL, NULL, 'حساب حيّ لا يراقبه أحد أفضل ما يبحث عنه المهاجم.', 'terminal', NULL, NULL, '["حساب يتيم","الحسابات اليتيمة","orphan account","حساب مهجور","حساب بلا صاحب"]'::jsonb, 'الوصف', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'اكتب المصطلح الذي يصف تراكم الصلاحيات مع تنقّل الموظف', NULL, NULL, NULL, 'يأخذ صلاحيات المنصب الجديد ويحتفظ بصلاحيات القديم.', 'terminal', NULL, NULL, '["زحف الصلاحيات","تراكم الصلاحيات","privilege creep","زحف الامتيازات","تضخم الصلاحيات"]'::jsonb, 'المصطلح', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'اكتب اسم القيمة التي تُضاف لكلمة المرور قبل تلبيدها لتمييز المتكرر', NULL, NULL, NULL, 'بدونها يعطي المستخدمان بالكلمة نفسها بصمة واحدة.', 'terminal', NULL, NULL, '["الملّاحة","الملح","salt","ملح التلبيد","قيمة الملح"]'::jsonb, 'القيمة', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'اكتب اسم القاعدة التي تمنع كل ما لم يُسمح به صراحة', NULL, NULL, NULL, 'تعكس عبء الإثبات فلا يمر خطر لم يُكتشف بعد.', 'terminal', NULL, NULL, '["المنع الافتراضي","الرفض الافتراضي","default deny","المنع الضمني","منع افتراضي"]'::jsonb, 'القاعدة', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'hard', 'اكتب اسم الإجراء الذي يشترط شخصين لإتمام عملية حساسة', NULL, NULL, NULL, 'ما يحتاج اثنين أصعب بكثير مما يقرره واحد بمفرده.', 'terminal', NULL, NULL, '["فصل المهام","الفصل بين المهام","separation of duties","التحكم المزدوج","فصل الواجبات"]'::jsonb, 'الإجراء', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'أي مما يلي من تطبيقات مبدأ أقل صلاحية؟', '["منح القراءة دون الكتابة عند الاكتفاء بها","إعطاء الجميع صلاحية إدارية للتسهيل","تشغيل الخدمة بحساب محدود الصلاحية","توحيد كل الموظفين في دور واحد"]'::jsonb, NULL, '[0,2]'::jsonb, 'التوسعة والتوحيد نقيض المبدأ لا تطبيق له.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'أي مما يلي طرق لتصعيد الصلاحيات؟', '["قراءة صفحة الموقع العامة","تغيير لغة واجهة النظام","استغلال ملف يُنفَّذ بهوية مالكه","استغلال قاعدة سماح واسعة"]'::jsonb, NULL, '[2,3]'::jsonb, 'الاثنان الآخران لا يمسّان الصلاحية أصلاً.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'أي مما يلي يضعف المساءلة في النظام؟', '["حساب باسم كل موظف على حدة","حساب مشترك بين عدة موظفين","تنبيه عند كل استخدام إداري","استخدام حساب الطوارئ يومياً"]'::jsonb, NULL, '[1,3]'::jsonb, 'ما يخفي هوية الفاعل يسقط المساءلة، وما يميّزه يدعمها.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'hard', 'أي مما يلي من ممارسات تخزين كلمات المرور السليمة؟', '["تلبيدها بخوارزمية بطيئة عمداً","حفظها مشفّرة قابلة لفك التشفير","إضافة ملّاحة فريدة لكل حساب","حفظ آخر كلمة مرور نصاً للدعم"]'::jsonb, NULL, '[0,2]'::jsonb, 'النظام يطابق البصمة ولا يحتاج استرجاع الكلمة إطلاقاً.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'أي مما يلي صحيح عن نموذج الأدوار؟', '["يمنع تصعيد الصلاحيات بشكل تام","يسهّل إدارة الوصول في المؤسسات الكبيرة","يجعل كل مستخدم مالكاً لموارده","يحتاج مراجعة دورية لتفادي التضخم"]'::jsonb, NULL, '[1,3]'::jsonb, 'النموذج ينظّم المنح ولا يحصّن من الاستغلال ولا يلغي المراجعة.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'أي مما يلي يقلّل مساحة تصعيد الصلاحيات؟', '["مراجعة الملفات ذات هوية المالك","تحديد قواعد السماح بأوامر بعينها","تشغيل كل الخدمات بحساب إداري","إضافة مجلد مؤقت لمقدمة المسار"]'::jsonb, NULL, '[0,1]'::jsonb, 'الخياران الآخران يوسّعان الطرق بدل أن يغلقاها.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'أي مما يلي يجب عند مغادرة موظف؟', '["إبقاء الحساب فعّالاً شهراً احتياطاً","تعطيل الحساب فور انتهاء العمل","سحب عضوياته من المجموعات","مشاركة كلمة مروره مع بديله"]'::jsonb, NULL, '[1,2]'::jsonb, 'الإبقاء والمشاركة يصنعان حساباً يتيماً بلا مساءلة.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'hard', 'أي مما يلي يصف نموذج السمات بدقة؟', '["يقرر من سمات المستخدم والمورد والسياق","يسمح بشروط كالوقت وحالة الجهاز","يقتصر على الدور الوظيفي وحده","يمنح المالك حرية المنح والمنع"]'::jsonb, NULL, '[0,1]'::jsonb, 'قدرته على جمع الشروط هي ميزته، وثمنها تعقيد كتابتها.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'أي مما يلي من علامات الحساب الخطر في الدليل؟', '["تسجيل دخول يومي من جهاز مُدار","انتهاء صلاحية كلمة المرور دورياً","خمول طويل مع صلاحية إدارية","صلاحيات لا يفسّرها منصب صاحبها"]'::jsonb, NULL, '[2,3]'::jsonb, 'الخطر في صلاحية قائمة بلا استخدام أو بلا مبرر وظيفي.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'hard', 'أي مما يلي صحيح عن انتحال رمز الجلسة؟', '["يمنح التصرّف بهوية صاحب الرمز","لا يحتاج معرفة كلمة المرور","يكشف كلمة مرور صاحب الرمز","يعمل بعد انتهاء الجلسة دائماً"]'::jsonb, NULL, '[0,1]'::jsonb, 'الرمز يمثّل الجلسة لا الكلمة، وينتهي بانتهائها.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'easy', 'رتّب مراحل التعامل مع الهوية بالترتيب الصحيح', '["التعريف","التوثيق","التخويل","المحاسبة"]'::jsonb, NULL, NULL, 'كل مرحلة تفترض تمام ما قبلها.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'رتّب مراحل دورة حياة حساب الموظف', '["إنشاء الحساب بأقل صلاحية","منح صلاحيات الوظيفة","مراجعة الصلاحيات دورياً","تعطيل الحساب عند المغادرة"]'::jsonb, NULL, NULL, 'المراجعة بين المنح والمغادرة هي ما يمنع زحف الصلاحيات.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'medium', 'رتّب خطوات المهاجم في تصعيد الصلاحيات', '["الحصول على وصول محدود","حصر الصلاحيات المتاحة","استغلال ضبط خاطئ","التصرّف بصلاحية أعلى"]'::jsonb, NULL, NULL, 'التصعيد يلي وصولاً قائماً ولا يبدأ منه.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'رتّب خطوات معالجة طلب وصول جديد', '["استلام الطلب ومبرره","التحقق من حاجة المهمة","اعتماد المسؤول المباشر","منح الصلاحية وتوثيقها"]'::jsonb, NULL, NULL, 'التوثيق آخر خطوة لأنه يسجّل ما اعتُمد فعلاً.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'medium', 'رتّب نماذج التحكم من الأمرن إلى الأشد ضبطاً', '["التقديري","الأدوار","السمات","الإلزامي"]'::jsonb, NULL, NULL, 'المرونة تقل كلما انتقل القرار من المالك إلى سياسة النظام.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'رتّب خطوات التحقق من كلمة المرور المخزّنة', '["استلام الكلمة المُدخَلة","جلب ملّاحة الحساب","تلبيد الكلمة مع الملّاحة","مقارنة الناتج بالمخزّن"]'::jsonb, NULL, NULL, 'المقارنة تقع على البصمتين لا على الكلمتين.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Privilege Escalation', 'hard', 'رتّب خطوات معالجة ملف يُنفَّذ بهوية مالكه بلا حاجة', '["حصر الملفات ذات البت","تحديد ما لا تحتاجه الخدمة","إزالة البت من الزائد","التحقق من بقاء الخدمة عاملة"]'::jsonb, NULL, NULL, 'التحقق بعد الإزالة يمنع تعطيل خدمة تعتمد عليها فعلاً.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'رتّب خطوات مراجعة الصلاحيات الدورية', '["استخراج الصلاحيات القائمة","مطابقتها بالمهام الحالية","إقرار اللازم وتحديد الزائد","سحب الزائد وتوثيق السحب"]'::jsonb, NULL, NULL, 'المطابقة بالمهام هي جوهر المراجعة لا مجرد عرض القوائم.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Identity Management', 'medium', 'رتّب خطوات التعامل مع حساب يتيم مكتشف', '["تعطيل الحساب فوراً","مراجعة نشاطه السابق","تحديد سبب بقائه","إصلاح إجراء المغادرة"]'::jsonb, NULL, NULL, 'إصلاح الإجراء يمنع تكرار الحالة لا معالجتها وحدها.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 3, 'Access Control Models', 'hard', 'رتّب قواعد الوصول من الأخص إلى الأعم', '["منع مستخدم بعينه","منع مجموعة فرعية","السماح لقسم كامل","المنع الافتراضي للجميع"]'::jsonb, NULL, NULL, 'الأخص أولاً لأن أول قاعدة تنطبق هي التي تُطبَّق.', 'ordering', NULL, NULL, NULL, NULL, 60, true);

-- تحقق فوري بعد الإدخال
select level, type, count(*)
from public.questions
where track_id = 'CyberSecurity'
  and section_id = 'System and Operating System Security'
  and level = 3
  and is_active
group by level, type
order by type;

commit;
