-- الأمن السيبراني · S4 أمن التطبيقات · L3 المصادقة والصلاحيات
-- 90 سؤالاً · وُلِّد آلياً بعد اجتياز فحوصات عقد الجودة كاملة:
--   توزيع الأنواع 30/10×6 · مواضع الإجابة 8/8/7/7 · صفر فجوة طول ≥7
--   صفر تكرار داخل الدفعة وعبر المسار · كل الأنواع مكتملة البنية
-- التشغيل: لوحة Supabase ← SQL Editor ← الصق ونفّذ.

begin;

insert into public.questions
  (track_id, section_id, level, topic, difficulty, question, options, correct_answer, correct_answers, explanation, type, code_snippet, pairs, expected_answers, prompt_label, time_limit, is_active)
values
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'easy', 'ما الذي يثبته عامل التحقق الثاني؟', '["امتلاك شيء لا معرفته فقط","قوة كلمة المرور المختارة","صلاحية الحساب على المورد","حداثة آخر تغيير للكلمة"]'::jsonb, 0, NULL, 'من سرق الكلمة لا يملك الجهاز، فيسقط عنده العامل الثاني.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'لماذا يُعد التحقق عبر الرسائل النصية أضعف العوامل؟', '["يحتاج اتصالاً بالإنترنت دائماً","يمكن تحويل الرقم لشريحة أخرى","يصل متأخراً في أوقات الذروة","يعمل على الهواتف الحديثة فقط"]'::jsonb, 1, NULL, 'انتحال الشريحة ينقل العامل الثاني للمهاجم بلا لمس الجهاز.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'ما الذي تكشفه رسالة «هذا الحساب غير موجود»؟', '["كلمة المرور المستخدمة في المحاولة","صلاحيات الحساب في التطبيق","وجود الحسابات من عدمه للمهاجم","وقت آخر دخول ناجح للحساب"]'::jsonb, 2, NULL, 'الرسالة الموحّدة تمنع بناء قائمة حسابات صالحة قبل التخمين.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'ما عيب قفل الحساب بعد محاولات فاشلة؟', '["يمنع المستخدم من تغيير كلمته","يكشف كلمة المرور الصحيحة","يلغي أثر التحقق متعدد العوامل","يتيح تعطيل حسابات الآخرين عمداً"]'::jsonb, 3, NULL, 'يكفي المهاجم أن يفشل عمداً ليقفل حساب غيره، ولذلك يُفضَّل التمهيل المتدرّج.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'ما الذي يميّز حشو الاعتماد عن التخمين؟', '["يجرّب اعتماداً صحيحاً مسرّباً من غيرك","يجرّب كلمات مرور شائعة بالترتيب","يستغل ثغرة في صفحة الدخول","يعترض الاتصال بين الطرفين"]'::jsonb, 0, NULL, 'الاعتماد صحيح فعلاً في موقع آخر، فينجح إن كرّر المستخدم كلمته.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'ما شرط رمز إعادة تعيين كلمة المرور؟', '["أن يبقى صالحاً حتى يُستخدم","أن ينتهي بمدة قصيرة ويُستخدم مرة","أن يُرسل بالبريد وبالرسائل معاً","أن يحوي اسم الحساب المرتبط به"]'::jsonb, 1, NULL, 'رمز دائم أو متعدد الاستخدام يصير مفتاحاً بديلاً للحساب.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'لماذا لا يُبنى رمز الاسترجاع على قيم معروفة؟', '["يستهلك موارد أكبر عند التوليد","يمنع إرساله عبر البريد الإلكتروني","يصير متوقّعاً لمن يعرف لحظة الطلب","يفقد صلاحيته قبل وصوله للمستخدم"]'::jsonb, 2, NULL, 'ما يُشتق من قيمة معروفة يُخمَّن، فيُولَّد من مصدر عشوائي معتمد.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'ما الذي يجب أن يحدث لكل جلسات المستخدم عند تغيير كلمته؟', '["تمديدها لتفادي إزعاج المستخدم","نقلها لرمز جديد دون تحقق","إبقاء الجلسة الحالية دون غيرها","إنهاؤها ليُعاد التحقق من الجميع"]'::jsonb, 3, NULL, 'لو كان مهاجم داخل جلسة قائمة، بقيت له بعد تغيير الكلمة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'ما الذي يكشفه اختلاف زمن الرد بين حساب موجود وآخر لا؟', '["وجود الحساب رغم توحيد الرسالة","طول كلمة المرور المخزّنة","نوع الخوارزمية المستخدمة","عدد محاولات الدخول السابقة"]'::jsonb, 0, NULL, 'الفرق الزمني قناة جانبية تُبطِل أثر توحيد نص الرسالة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'أين يقع التحقق من الاعتماد دائماً؟', '["في المتصفح لتخفيف الحمل","في الخادم مهما فحص العميل","في الطرفين بالتساوي تماماً","في العميل ثم يؤكده الخادم"]'::jsonb, 1, NULL, 'كل ما يجري في المتصفح يمكن تعديله، ففحصه راحة للمستخدم لا ضمانة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'ما الذي تمنعه خاصية منع الوصول بالسكربت للكعكة؟', '["إرسال الكعكة عبر اتصال غير مشفّر","إرسالها مع طلب من موقع آخر","قراءة الجلسة عبر سكربت محقون","بقاءها بعد إغلاق المتصفح"]'::jsonb, 2, NULL, 'تقطع أشهر طرق استغلال ثغرة السكربت: سرقة معرّف الجلسة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'ما الذي تضمنه خاصية إرسال الكعكة عبر المشفّر فقط؟', '["ألا يقرأها سكربت في الصفحة","ألا تُرسل مع طلبات المواقع الأخرى","ألا تبقى بعد انتهاء الجلسة","ألا تُرسل عبر اتصال غير مشفّر"]'::jsonb, 3, NULL, 'تمنع تسرّبها في أول طلب يقع على قناة غير مؤمَّنة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'ما الذي تعالجه خاصية تقييد إرسال الكعكة لمواقع أخرى؟', '["طلباً يرسله موقع خبيث باسمك","سكربتاً يقرأ محتوى الكعكة","اعتراض الكعكة على الشبكة","بقاء الجلسة بعد الخروج"]'::jsonb, 0, NULL, 'هي الضابط الأساسي ضد تزوير الطلب عبر المواقع.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'ما تثبيت الجلسة؟', '["أن تبقى الجلسة صالحة بلا انتهاء","أن يفرض المهاجم معرّفاً يعرفه قبل الدخول","أن يُنسخ المعرّف من ذاكرة المتصفح","أن يُخمَّن المعرّف بالمحاولة المتكررة"]'::jsonb, 1, NULL, 'فيصير المعرّف الذي يعرفه هو نفسه معرّف الجلسة بعد نجاح الدخول.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'ما الذي يبطل تثبيت الجلسة؟', '["إطالة مدة صلاحية المعرّف","تخزين المعرّف في ذاكرة المتصفح","تجديد المعرّف عند نجاح الدخول","إرسال المعرّف في مسار الرابط"]'::jsonb, 2, NULL, 'المعرّف القديم يسقط عند الدخول، فلا ينفع ما زرعه المهاجم.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'لماذا يخطر تمرير معرّف الجلسة في الرابط؟', '["يمنع المتصفح من حفظ الصفحة","يبطل عمل الكعكات في الموقع","يزيد حجم الطلب على الخادم","يظهر في السجلات وسجل التصفّح"]'::jsonb, 3, NULL, 'يتسرّب عبر ترويسة المصدر ومشاركة الرابط دون علم صاحبه.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'ما الذي يجب أن يفعله الخادم عند تسجيل الخروج؟', '["إبطال الجلسة عنده لا حذف الكعكة فقط","حذف الكعكة من المتصفح فقط","تغيير كلمة مرور الحساب","إنهاء الاتصال بقاعدة البيانات"]'::jsonb, 0, NULL, 'كعكة محذوفة من المتصفح تبقى صالحة إن كانت نسختها قائمة عند الخادم.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'ما عيب حفظ رمز الجلسة في مخزن المتصفح المحلي؟', '["يُرسل مع كل طلب لموقع آخر","يقرؤه أي سكربت في الصفحة","يُحذف عند إغلاق التبويب","لا يعمل إلا على اتصال مشفّر"]'::jsonb, 1, NULL, 'بخلاف الكعكة الممنوعة على السكربت، المخزن المحلي مقروء بالكامل.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'ما الغرض من مهلة الخمول للجلسة؟', '["منع الدخول خارج ساعات العمل","تقليل حجم الجلسات على الخادم","إنهاء جلسة تُرِكت مفتوحة بلا استخدام","إجبار المستخدم على تغيير كلمته"]'::jsonb, 2, NULL, 'الجهاز المتروك مفتوحاً في مكان عام أشيع مما يُظن.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'hard', 'ما الذي يميّز الرمز الموقّع عن الجلسة المحفوظة في الخادم؟', '["يمنع قراءة محتواه بلا مفتاح","يعمل دون الحاجة لاتصال مشفّر","يتجدد تلقائياً عند كل طلب","يصعب إبطاله قبل انتهاء مدته"]'::jsonb, 3, NULL, 'الخادم لا يحفظ حالته، فسحبه يحتاج قائمة إبطال أو مدة قصيرة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'ما المرجع المباشر غير الآمن للكائن؟', '["بلوغ سجل غيرك بتغيير معرّفه","حقن أمر في حقل إدخال","قراءة ملف إعداد الخادم","اعتراض الطلب على الشبكة"]'::jsonb, 0, NULL, 'الطلب سليم شكلاً، والخلل أن الخادم لم يسأل: هل هذا السجل لك؟', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'لماذا لا يكفي إخفاء زر الإدارة من الواجهة؟', '["الزر يظهر في نسخة الطباعة","الطلب يُرسل مباشرة دون الواجهة","الإخفاء يبطئ تحميل الصفحة","الواجهة تُخزَّن مؤقتاً في المتصفح"]'::jsonb, 1, NULL, 'الإخفاء تجربة استخدام، والمنع لا يقع إلا في الخادم.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'ما التصفّح القسري؟', '["إجبار المستخدم على صفحة معيّنة","فتح الموقع في وضع التصفّح الخفي","بلوغ صفحة بكتابة رابطها مباشرة","تحميل الصفحة قبل اكتمال التحقق"]'::jsonb, 2, NULL, 'غياب الرابط من القائمة ليس منعاً، والمنع فحص في الخادم.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'أين يجب أن يقع فحص الصلاحية في التطبيق؟', '["في صفحة الدخول مرة واحدة","في الواجهة قبل إظهار الخيار","في بوابة الشبكة أمام التطبيق","في كل نقطة تنفّذ العملية"]'::jsonb, 3, NULL, 'واجهة برمجية تُنسى بلا فحص تفتح الباب الذي أُغلق في الصفحة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'ما تزوير الطلب عبر المواقع؟', '["استغلال جلستك لتنفيذ فعل لم تقصده","حقن سكربت يعمل في صفحتك","سرقة كعكة الجلسة من المتصفح","اعتراض الطلب وتعديل محتواه"]'::jsonb, 0, NULL, 'المتصفح يرفق كعكتك تلقائياً، فيصل الطلب موثّقاً باسمك.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'hard', 'لماذا يفشل رمز مكافحة التزوير إن قُرِئ بسكربت؟', '["الرمز يفقد صلاحيته عند القراءة","المهاجم يقرؤه ثم يرسله مع طلبه","الخادم يرفض الطلبات المقروءة","الرمز يصير أطول من المسموح"]'::jsonb, 1, NULL, 'ثغرة السكربت تسبق الضابط وتبطله، فالضابطان يلزمان معاً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'ما القاعدة الافتراضية الصحيحة في التحكم بالوصول؟', '["السماح حتى يُمنع صراحة","السماح للمسجّلين دخولهم","المنع حتى يُسمح صراحة للدور","المنع لغير المسؤولين فقط"]'::jsonb, 2, NULL, 'مسار جديد يُنشر بلا قاعدة يكون مغلقاً لا مفتوحاً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'ما خطر الاعتماد على معرّف متسلسل في الروابط؟', '["يزيد حجم قاعدة البيانات","يبطئ استعلام السجل الواحد","يمنع أرشفة السجلات القديمة","يسهّل تعداد سجلات المستخدمين"]'::jsonb, 3, NULL, 'المعرّف غير المتوقّع يقلّل الأثر ولا يغني عن فحص الملكية.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'ما الذي يجب فحصه في طلب تعديل بيانات مستخدم؟', '["ملكية السجل لا الجلسة وحدها","صحة صيغة الحقول المرسلة","حجم الطلب ووقت وصوله","نوع المتصفح المستخدم"]'::jsonb, 0, NULL, 'جلسة صالحة تثبت من أنت لا أن هذا السجل يخصّك.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'ما الذي يميّز الوصول الأفقي عن الرأسي في التطبيق؟', '["بلوغ لوحة الإدارة من حساب عادي","بلوغ بيانات مستخدم بالمستوى نفسه","تجاوز التحقق متعدد العوامل","تعديل الصلاحيات في قاعدة البيانات"]'::jsonb, 1, NULL, 'الأفقي لا يرفع الدور، ويبقى خرقاً كاملاً لخصوصية غيرك.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'ما الخاصية الناقصة في هذي الكعكة؟', '["منع قراءتها بالسكربت","إرسالها عبر المشفّر فقط","تقييد إرسالها لمواقع أخرى","تحديد مسار صلاحيتها"]'::jsonb, 0, NULL, 'بلا هذي الخاصية يقرأ أي سكربت محقون معرّف الجلسة مباشرة.', 'code', 'Set-Cookie: session=a91f2c; Path=/; Secure; SameSite=Lax', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'hard', 'ما الخلل في تسلسل الدخول هذا؟', '["المعرّف قصير جداً فيسهل تخمينه","المعرّف لم يتغيّر بعد نجاح الدخول","الكعكة أُرسلت قبل التحقق منها","الطلب الأخير بلا رمز مكافحة تزوير"]'::jsonb, 1, NULL, 'بقاء المعرّف يتيح تثبيت الجلسة بمعرّف زرعه المهاجم سلفاً.', 'code', 'GET /login        → Set-Cookie: session=abc123
POST /login (نجح) → (بلا Set-Cookie جديدة)
GET /account      → Cookie: session=abc123', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'hard', 'ما الثغرة في هذا المسار؟', '["لا يتحقق أن المستخدم مسجّل دخوله","لا يتحقق من صيغة رقم الفاتورة","لا يتحقق أن الفاتورة تخص صاحب الجلسة","لا يتحقق من نوع الطلب المرسل"]'::jsonb, 2, NULL, 'الجلسة تثبت الهوية، ولا شيء هنا يربط الفاتورة بصاحبها.', 'code', 'GET /api/invoices/1042
الجلسة: user_id=77
الخادم: يعيد الفاتورة إن وُجِدت', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'hard', 'ما الخلل في هذا الفحص؟', '["الدور يُقارَن بنص لا برقم","الفحص يقع بعد فتح اللوحة","الشرط لا يتعامل مع القيمة الفارغة","الدور يأتي من الطلب لا من الخادم"]'::jsonb, 3, NULL, 'ما يرسله العميل يعدّله العميل، فالدور يُقرأ من الجلسة عند الخادم.', 'code', 'if (request.body.role === "admin") {
  allowAdminPanel();
}', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'ما الذي يكشفه هذا النمط في السجل؟', '["تعداد سجلات لا تخص صاحب الجلسة","محاولة تخمين كلمة مرور","حقن استعلام في مسار الطلب","إعادة إرسال الطلب نفسه مراراً"]'::jsonb, 0, NULL, 'نجاح متتابع لمعرّفات متسلسلة يعني غياب فحص الملكية.', 'code', 'user=22 GET /orders/501 → 200
user=22 GET /orders/502 → 200
user=22 GET /orders/503 → 200', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'hard', 'ما الخلل في رسالتي الخطأ هاتين؟', '["تكشفان طول كلمة المرور","تكشفان وجود الحساب من عدمه","تمنعان إعادة المحاولة","تعطّلان التحقق متعدد العوامل"]'::jsonb, 1, NULL, 'تُوحَّد الرسالة ليتعذّر بناء قائمة حسابات صالحة.', 'code', 'حساب غير مسجّل → "لا يوجد حساب بهذا البريد"
كلمة خاطئة    → "كلمة المرور غير صحيحة"', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'hard', 'ما العيب في توليد رمز الاسترجاع هذا؟', '["الرمز أطول من اللازم بكثير","الرمز لا يُرسل إلا بالبريد","مكوّناته معروفة فيصير متوقّعاً","الرمز ينتهي بسرعة كبيرة"]'::jsonb, 2, NULL, 'البريد معروف واللحظة تُخمَّن، فيُولَّد من مصدر عشوائي معتمد.', 'code', 'token = md5(email + timestamp)', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'ما الناقص في سياسة الدخول هذي؟', '["لا شيء يمنع تكرار كلمة المرور","لا شيء يوحّد رسائل الخطأ","لا شيء يشفّر كلمة المرور","لا شيء يبطئ التخمين المتكرر"]'::jsonb, 3, NULL, 'بلا تمهيل ولا حد يجرّب المهاجم آلاف الكلمات بلا اعتراض.', 'code', 'محاولات فاشلة: بلا حد
مهلة بين المحاولات: لا يوجد
تحقق ثانٍ: اختياري', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'hard', 'ما الخلل في هذا الرمز الموقّع؟', '["مدة صلاحية طويلة يصعب إبطالها","الحمولة غير مشفّرة فتُقرأ","الرمز لا يحمل هوية المستخدم","التوقيع لا يمنع تعديل الحمولة"]'::jsonb, 0, NULL, 'الرمز الموقّع لا يُسحَب من الخادم، فالمدة الطويلة تعني وصولاً باقياً.', 'code', '{ "sub": "77", "role": "user", "exp": 1893456000 }
التوقيع: صالح · المدة: ثلاث سنوات', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'ما الخطأ في معالجة تسجيل الخروج هذي؟', '["الكعكة لم تُحذف من المتصفح","الجلسة لم تُبطَل عند الخادم","التحويل يقع قبل الحذف","الدالة لا تعيد أي قيمة"]'::jsonb, 1, NULL, 'من نسخ المعرّف قبل الخروج يبقى داخل الجلسة لأنها حيّة عند الخادم.', 'code', 'function logout() {
  document.cookie = "session=; Max-Age=0";
  redirect("/");
}', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'easy', 'العامل الثاني يثبت امتلاك شيء لا معرفة كلمة المرور وحدها.', '["صح","خطأ"]'::jsonb, 0, NULL, 'من سرق الكلمة لا يملك الجهاز فيسقط عنده العامل الثاني.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'قفل الحساب بعد محاولات فاشلة إجراء بلا أثر جانبي.', '["صح","خطأ"]'::jsonb, 1, NULL, 'يتيح تعطيل حساب غيرك بالفشل عمداً، فيُفضَّل التمهيل المتدرّج.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'توحيد رسالة الخطأ يمنع بناء قائمة حسابات صالحة.', '["صح","خطأ"]'::jsonb, 0, NULL, 'بشرط توحيد زمن الرد أيضاً وإلا كشفه الفارق الزمني.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'رمز إعادة التعيين يجوز أن يبقى صالحاً حتى يستخدمه صاحبه.', '["صح","خطأ"]'::jsonb, 1, NULL, 'رمز بلا انتهاء يصير مفتاحاً بديلاً دائماً للحساب.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'حذف الكعكة من المتصفح وحده لا ينهي الجلسة عند الخادم.', '["صح","خطأ"]'::jsonb, 0, NULL, 'من نسخ المعرّف قبل الحذف يبقى داخل الجلسة.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'تجديد معرّف الجلسة بعد الدخول يبطل تثبيت الجلسة.', '["صح","خطأ"]'::jsonb, 0, NULL, 'المعرّف الذي زرعه المهاجم يسقط قبل أن يصير موثّقاً.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'حفظ رمز الجلسة في مخزن المتصفح أأمن من الكعكة المحميّة.', '["صح","خطأ"]'::jsonb, 1, NULL, 'المخزن مقروء بالسكربت، والكعكة المحميّة ليست كذلك.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'إخفاء الزر من الواجهة يعد ضابط تحكم في الوصول.', '["صح","خطأ"]'::jsonb, 1, NULL, 'الطلب يُرسل مباشرة دون الواجهة، والمنع في الخادم وحده.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'المعرّف غير المتوقّع يقلّل أثر الثغرة ولا يغني عن فحص الملكية.', '["صح","خطأ"]'::jsonb, 0, NULL, 'إخفاء المعرّف يصعّب التعداد ولا يمنع من عرف معرّفاً بعينه.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'hard', 'رمز مكافحة التزوير يحمي حتى مع وجود ثغرة سكربت في الصفحة.', '["صح","خطأ"]'::jsonb, 1, NULL, 'السكربت يقرأ الرمز ويرسله، فالضابطان يلزمان معاً.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'صل كل خاصية للكعكة بما تمنعه', NULL, NULL, NULL, 'كل خاصية تغلق طريقاً مختلفاً، فتُضبَط الأربع معاً.', 'matching', NULL, '[{"left":"منع قراءتها بالسكربت","right":"سرقة المعرّف بثغرة سكربت"},{"left":"الإرسال عبر المشفّر فقط","right":"تسرّبها على قناة مكشوفة"},{"left":"تقييد إرسالها للمواقع","right":"تزوير الطلب عبر المواقع"},{"left":"تحديد مدة انتهائها","right":"بقاءها صالحة بلا أجل"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'صل كل هجوم على الجلسة بعلاجه', NULL, NULL, NULL, 'الأربعة تصيب الجلسة نفسها بطرق مختلفة تماماً.', 'matching', NULL, '[{"left":"تثبيت الجلسة","right":"تجديد المعرّف عند الدخول"},{"left":"سرقة المعرّف بسكربت","right":"منع قراءة الكعكة بالسكربت"},{"left":"اعتراض المعرّف","right":"الإرسال عبر المشفّر فقط"},{"left":"جلسة متروكة مفتوحة","right":"مهلة خمول تنهيها"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'صل كل خلل وصول بوصفه', NULL, NULL, NULL, 'أربعتها تشترك في أن الخادم لم يسأل السؤال الصحيح.', 'matching', NULL, '[{"left":"مرجع مباشر غير آمن","right":"بلوغ سجل غيرك بتغيير معرّفه"},{"left":"التصفّح القسري","right":"بلوغ صفحة بكتابة رابطها"},{"left":"فحص في الواجهة فقط","right":"منع يسقط بإرسال الطلب مباشرة"},{"left":"دور يأتي من العميل","right":"المستخدم يعلن صلاحيته بنفسه"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'صل كل هجوم على المصادقة بما يستغله', NULL, NULL, NULL, 'كل واحد يستغل قراراً تصميمياً لا ثغرة برمجية.', 'matching', NULL, '[{"left":"حشو الاعتماد","right":"تكرار الكلمة بين المواقع"},{"left":"تخمين الكلمة","right":"غياب التمهيل والحد"},{"left":"تعداد الحسابات","right":"اختلاف رسالة الخطأ"},{"left":"انتحال الشريحة","right":"التحقق برسالة نصية"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'صل كل شرط في رمز الاسترجاع بمبرره', NULL, NULL, NULL, 'الشروط الأربعة تُطبَّق مجتمعة أو ينهار الرمز عند أضعفها.', 'matching', NULL, '[{"left":"مصدر عشوائي معتمد","right":"ألا يُخمَّن من قيم معروفة"},{"left":"استخدام مرة واحدة","right":"ألا يُعاد استعماله لاحقاً"},{"left":"مدة قصيرة","right":"ألا يبقى مفتاحاً دائماً"},{"left":"رد موحّد للطلب","right":"ألا يكشف وجود الحساب"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'hard', 'صل كل أسلوب لحفظ الحالة بحدّه', NULL, NULL, NULL, 'الاختيار مقايضة بين سهولة التوسّع وسرعة السحب.', 'matching', NULL, '[{"left":"جلسة محفوظة في الخادم","right":"تحتاج تخزيناً ومزامنة"},{"left":"رمز موقّع بلا حالة","right":"يصعب إبطاله قبل مدته"},{"left":"مخزن المتصفح المحلي","right":"مقروء بأي سكربت"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'صل كل سؤال يطرحه الخادم بما يثبته', NULL, NULL, NULL, 'الإجابة عن الأولين دون الثالث هي أشهر انهيار وصول.', 'matching', NULL, '[{"left":"هل الجلسة صالحة؟","right":"من المستخدم"},{"left":"هل الدور يسمح بالعملية؟","right":"ما يستطيعه عموماً"},{"left":"هل السجل يخصّه؟","right":"حقه في هذا السجل"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'صل كل ضابط بموضع تطبيقه', NULL, NULL, NULL, 'ما يقع في الواجهة تحسين، وما يقع في الخادم ضمانة.', 'matching', NULL, '[{"left":"إخفاء الخيار","right":"الواجهة لتحسين التجربة"},{"left":"فحص الدور","right":"الخادم عند كل عملية"},{"left":"فحص الملكية","right":"الخادم عند كل سجل"},{"left":"رمز مكافحة التزوير","right":"الطلبات المغيّرة للحالة"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'صل كل عامل تحقق بنوعه', NULL, NULL, NULL, 'التعدد الحقيقي يجمع نوعين مختلفين لا عاملين من نوع واحد.', 'matching', NULL, '[{"left":"كلمة المرور","right":"شيء تعرفه"},{"left":"مفتاح مادي","right":"شيء تملكه"},{"left":"البصمة","right":"شيء أنت عليه"},{"left":"رمز التطبيق المؤقت","right":"شيء تملكه"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'hard', 'صل كل حدث بما يجب أن يقع للجلسات', NULL, NULL, NULL, 'كل تغيّر في الثقة يستوجب تغيّراً في معرّف الجلسة.', 'matching', NULL, '[{"left":"تغيير كلمة المرور","right":"إنهاء كل الجلسات القائمة"},{"left":"نجاح الدخول","right":"توليد معرّف جديد"},{"left":"تسجيل الخروج","right":"إبطالها عند الخادم"},{"left":"ارتفاع الصلاحية","right":"تجديد المعرّف مجدداً"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'اكتب اسم الهجوم الذي يفرض فيه المهاجم معرّف جلسة يعرفه قبل دخول الضحية', NULL, NULL, NULL, 'يبطله توليد معرّف جديد عند نجاح الدخول.', 'terminal', NULL, NULL, '["تثبيت الجلسة","session fixation","تثبيت المعرّف","تثبيت جلسة"]'::jsonb, 'الهجوم', 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'اكتب اسم خاصية الكعكة التي تمنع قراءتها بسكربت الصفحة', NULL, NULL, NULL, 'تقطع أشهر استغلال لثغرة السكربت: سرقة معرّف الجلسة.', 'terminal', NULL, NULL, '["HttpOnly","httponly","منع الوصول بالسكربت","خاصية HttpOnly"]'::jsonb, 'الخاصية', 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'اكتب اسم خاصية الكعكة التي تقيّد إرسالها مع طلبات المواقع الأخرى', NULL, NULL, NULL, 'هي الضابط الأساسي ضد تزوير الطلب عبر المواقع.', 'terminal', NULL, NULL, '["SameSite","samesite","خاصية SameSite","تقييد الموقع نفسه"]'::jsonb, 'الخاصية', 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'اكتب اسم الثغرة التي تُبلَغ فيها سجلات غيرك بتغيير المعرّف في الرابط', NULL, NULL, NULL, 'الطلب سليم شكلاً والخادم لم يسأل: هل هذا السجل لك؟', 'terminal', NULL, NULL, '["المرجع المباشر غير الآمن","IDOR","مرجع مباشر غير آمن","الوصول المباشر للكائن","insecure direct object reference"]'::jsonb, 'الثغرة', 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'اكتب اسم الهجوم الذي يستغل جلستك لتنفيذ فعل لم تقصده', NULL, NULL, NULL, 'المتصفح يرفق كعكتك تلقائياً فيصل الطلب موثّقاً باسمك.', 'terminal', NULL, NULL, '["تزوير الطلب عبر المواقع","CSRF","تزوير الطلب","csrf","تزوير طلب عبر المواقع"]'::jsonb, 'الهجوم', 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'hard', 'اكتب اسم بلوغ صفحة إدارية بكتابة رابطها مباشرة دون ظهورها في القائمة', NULL, NULL, NULL, 'غياب الرابط من القائمة ليس منعاً، والمنع فحص في الخادم.', 'terminal', NULL, NULL, '["التصفّح القسري","forced browsing","التصفح القسري","الوصول المباشر للرابط"]'::jsonb, 'الممارسة', 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'اكتب اسم الهجوم الذي يجرّب اعتماداً صحيحاً مسرّباً من موقع آخر', NULL, NULL, NULL, 'ينجح إن كرّر المستخدم كلمة المرور نفسها بين المواقع.', 'terminal', NULL, NULL, '["حشو الاعتماد","credential stuffing","حشو بيانات الاعتماد","حشو الاعتمادات"]'::jsonb, 'الهجوم', 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'hard', 'اكتب اسم البديل عن قفل الحساب الذي يبطئ المحاولات دون تعطيله', NULL, NULL, NULL, 'يمنع التخمين ولا يتيح تعطيل حساب غيرك بالفشل عمداً.', 'terminal', NULL, NULL, '["التمهيل المتدرّج","التمهيل","throttling","تحديد المعدل","rate limiting","التأخير المتدرج"]'::jsonb, 'الأسلوب', 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'اكتب اسم كشف وجود الحسابات من اختلاف رسائل الخطأ', NULL, NULL, NULL, 'يُعالَج بتوحيد الرسالة وزمن الرد معاً.', 'terminal', NULL, NULL, '["تعداد الحسابات","user enumeration","تعداد المستخدمين","حصر الحسابات","كشف الحسابات"]'::jsonb, 'الممارسة', 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'اكتب ما يجب أن يفعله الخادم بالجلسات القائمة عند تغيير كلمة المرور', NULL, NULL, NULL, 'لو كان مهاجم داخل جلسة قائمة بقيت له بعد تغيير الكلمة.', 'terminal', NULL, NULL, '["إنهاؤها","إبطالها","إنهاء كل الجلسات","إبطال الجلسات","session invalidation","إلغاؤها"]'::jsonb, 'الإجراء', 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'أي مما يلي يجب ضبطه في كعكة الجلسة؟', '["منع قراءتها بالسكربت","إتاحتها لكل النطاقات","الإرسال عبر المشفّر فقط","إطالة مدتها بلا أجل"]'::jsonb, NULL, '[0,2]'::jsonb, 'التوسعة والإطالة تفتحان ما أغلقته الخاصيتان الأخريان.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'hard', 'أي مما يلي يعالج تثبيت الجلسة؟', '["إطالة مدة صلاحية المعرّف","تمرير المعرّف في الرابط","تجديد المعرّف عند الدخول","تجديده عند ارتفاع الصلاحية"]'::jsonb, NULL, '[2,3]'::jsonb, 'الأولان يزيدان الخطر بدل أن يعالجاه.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'أي مما يلي يجب فحصه عند طلب تعديل سجل؟', '["صلاحية الجلسة القائمة","نوع متصفح المستخدم","ملكية السجل لصاحب الجلسة","حجم البيانات المرسلة"]'::jsonb, NULL, '[0,2]'::jsonb, 'الجلسة تثبت من أنت، والملكية تثبت حقك في هذا السجل.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'hard', 'أي مما يلي من صور انهيار التحكم في الوصول؟', '["قراءة الدور من الطلب المرسل","توحيد رسائل الخطأ","بلوغ صفحة بكتابة رابطها","تشفير الاتصال بالخادم"]'::jsonb, NULL, '[0,2]'::jsonb, 'الاثنان الآخران ضابطان سليمان لا خللاً.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'أي مما يلي يقلّل نجاح تخمين كلمات المرور؟', '["التمهيل المتدرّج بين المحاولات","إظهار سبب فشل المحاولة","اشتراط عامل تحقق ثانٍ","إطالة مدة الجلسة الناجحة"]'::jsonb, NULL, '[0,2]'::jsonb, 'إظهار السبب يعين المهاجم، وإطالة الجلسة لا تمسّ التخمين.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'hard', 'أي مما يلي شرط في رمز إعادة التعيين؟', '["أن يُولَّد من مصدر عشوائي معتمد","أن يُشتق من البريد والوقت","أن يبقى صالحاً حتى يُستخدم","أن ينتهي بمدة قصيرة محددة"]'::jsonb, NULL, '[0,3]'::jsonb, 'الاشتقاق من قيم معروفة يجعله متوقّعاً، والبقاء بلا أجل يجعله مفتاحاً دائماً.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'hard', 'أي مما يلي صحيح عن الرمز الموقّع بلا حالة؟', '["يصعب إبطاله قبل انتهاء مدته","محتواه مشفّر لا يُقرأ","يعفي الخادم من حفظ الجلسة","يتجدد تلقائياً عند كل طلب"]'::jsonb, NULL, '[0,2]'::jsonb, 'التوقيع يمنع التعديل ولا يمنع القراءة، فلا يوضع فيه سر.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'hard', 'أي مما يلي لا يكفي وحده كضابط وصول؟', '["إخفاء الخيار من الواجهة","فحص الملكية في الخادم","اعتماد معرّف غير متوقّع","فحص الدور عند كل عملية"]'::jsonb, NULL, '[0,2]'::jsonb, 'الإخفاء والإخفاء بالمعرّف يصعّبان الاكتشاف ولا يمنعان من عرف.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'أي مما يلي يعد تحققاً متعدد العوامل حقيقياً؟', '["كلمة مرور ومفتاح مادي","كلمة مرور وسؤال سري","بصمة ورمز تطبيق مؤقت","كلمتا مرور مختلفتان"]'::jsonb, NULL, '[0,2]'::jsonb, 'التعدد يجمع نوعين مختلفين، والسؤال السري والكلمة كلاهما مما تعرفه.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'hard', 'أي مما يلي يستوجب تجديد معرّف الجلسة؟', '["نجاح تسجيل الدخول","تحديث صفحة عادية","ارتفاع صلاحية المستخدم","تصفّح قائمة المنتجات"]'::jsonb, NULL, '[0,2]'::jsonb, 'كل تغيّر في مستوى الثقة يستوجب معرّفاً جديداً.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'رتّب خطوات دخول آمن للتطبيق', '["استلام الاعتماد عبر قناة مشفّرة","التحقق منه في الخادم","طلب العامل الثاني","توليد معرّف جلسة جديد"]'::jsonb, NULL, NULL, 'المعرّف الجديد بعد اكتمال التحقق لا قبله.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'رتّب خطوات إعادة تعيين كلمة المرور بأمان', '["استلام الطلب برد موحّد","توليد رمز عشوائي قصير الأجل","إرساله لقناة صاحب الحساب","إبطاله وإنهاء الجلسات بعد التغيير"]'::jsonb, NULL, NULL, 'الرد الموحّد أولاً لئلا يكشف الطلب وجود الحساب.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'medium', 'رتّب مراحل حياة الجلسة', '["إنشاؤها عند نجاح الدخول","التحقق منها في كل طلب","تجديدها عند ارتفاع الصلاحية","إبطالها عند الخروج"]'::jsonb, NULL, NULL, 'الإبطال عند الخادم لا حذف الكعكة وحدها.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'hard', 'رتّب خطوات معالجة تسريب معرّف جلسة', '["إبطال الجلسة المتأثرة","إنهاء بقية جلسات الحساب","مراجعة ما جرى خلالها","إغلاق الطريق الذي سرّبها"]'::jsonb, NULL, NULL, 'الإبطال أولاً لأنه يقطع الوصول القائم في ساعته.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'رتّب فحوص الخادم لطلب على سجل', '["هل الجلسة صالحة؟","هل الدور يسمح بالعملية؟","هل السجل يخص صاحب الجلسة؟","تنفيذ العملية وتسجيلها"]'::jsonb, NULL, NULL, 'سقوط الفحص الثالث هو أشهر انهيار وصول في التطبيقات.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'hard', 'رتّب خطوات معالجة ثغرة مرجع مباشر غير آمن', '["حصر المسارات التي تقبل معرّفاً","إضافة فحص الملكية لكل مسار","مراجعة السجلات بحثاً عن استغلال","اختبار المسارات بحساب آخر"]'::jsonb, NULL, NULL, 'الاختبار بحساب آخر هو ما يثبت أن الفحص يعمل فعلاً.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'hard', 'رتّب طبقات الحماية من تزوير الطلب عبر المواقع', '["تقييد إرسال الكعكة للمواقع","رمز مكافحة تزوير في الطلب","التحقق منه في الخادم","إعادة التحقق للعمليات الحساسة"]'::jsonb, NULL, NULL, 'الطبقات تتراكم لأن أعلاها يسقط بثغرة سكربت في الصفحة.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Authentication Design', 'medium', 'رتّب خطوات معالجة محاولات دخول مشبوهة', '["رصد تكرار الفشل من مصدر","تمهيل المحاولات تدريجياً","طلب تحقق إضافي","تنبيه صاحب الحساب"]'::jsonb, NULL, NULL, 'التمهيل قبل التنبيه لأنه يوقف المحاولة في ساعتها.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Session Security', 'hard', 'رتّب خطوات تسجيل خروج سليم', '["إبطال الجلسة في الخادم","حذف الكعكة من المتصفح","تحويل المستخدم لصفحة عامة","تسجيل الحدث في السجل"]'::jsonb, NULL, NULL, 'الإبطال في الخادم أولاً وإلا بقي المعرّف المنسوخ صالحاً.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 3, 'Broken Access Control', 'medium', 'رتّب خطوات إضافة مسار إداري جديد بأمان', '["تعريفه بقاعدة منع افتراضية","تحديد الأدوار المسموح لها","إضافة فحص الدور في الخادم","اختباره بحساب غير مصرّح"]'::jsonb, NULL, NULL, 'الاختبار بحساب غير مصرّح يثبت أن المنع يعمل لا أن السماح يعمل.', 'ordering', NULL, NULL, NULL, NULL, 60, true);

-- تحقق فوري بعد الإدخال
select level, type, count(*)
from public.questions
where track_id = 'CyberSecurity'
  and section_id = 'Application and Web Security'
  and level = 3
  and is_active
group by level, type
order by type;

commit;
