-- الأمن السيبراني · S5 L5 · ما بعد الاستغلال والتقارير
-- 90 سؤالاً · وُلِّد آلياً بعد اجتياز فحوصات عقد الجودة كاملة:
--   توزيع الأنواع 30/10×6 · مواضع الإجابة 8/8/7/7 · صفر فجوة طول ≥7
--   صفر تكرار داخل الدفعة وعبر المسار · كل الأنواع مكتملة البنية
-- التشغيل: لوحة Supabase ← SQL Editor ← الصق ونفّذ.

begin;

insert into public.questions
  (track_id, section_id, level, topic, difficulty, question, options, correct_answer, correct_answers, explanation, type, code_snippet, pairs, expected_answers, prompt_label, time_limit, is_active)
values
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'medium', 'ما غاية ما بعد الاستغلال في اختبار مأذون؟', '["قياس أثر الوصول على العمل","توسيع الوصول قدر الإمكان","إخفاء الأثر عن فريق الأمن","جمع أكبر قدر من الاعتماد"]'::jsonb, 0, NULL, 'العميل يشتري فهماً لما يترتب على العيب، لا برهاناً على مهارة الفاحص.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'hard', 'ما الذي يحدد جواز الحركة إلى نظام ثانٍ؟', '["قدرة الفاحص التقنية على بلوغه","بند مكتوب يسمح بها في الاتفاق","وجود ثغرة قائمة في ذلك النظام","كون النظام في الشبكة نفسها"]'::jsonb, 1, NULL, 'الاستطاعة ليست إذناً، وهذا أكثر ما يُتجاوَز فيه الحد بحسن نيّة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'medium', 'ما الثبات في سياق ما بعد الاستغلال؟', '["بقاء الخدمة عاملة تحت الحمل","بقاء السجلات بعد التدوير","بقاء الوصول بعد إعادة التشغيل","بقاء الجلسة مفتوحة ساعة"]'::jsonb, 2, NULL, 'وهو ما يحوّل وصولاً عابراً إلى باب دائم، فلا يُفعَل إلا بإذن خاص.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'hard', 'متى يجوز تثبيت وصول في اختبار مأذون؟', '["حين يقصر وقت النافذة عن العمل","حين يرصد فريق الأمن الفاحص","حين تكون الثغرة عالية الدرجة","بإذن مكتوب وبأثر يُزال بعده"]'::jsonb, 3, NULL, 'ضيق الوقت لا يبيح ترك باب خلفي، والإذن وحده يبيحه بشرط إزالته.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'medium', 'ما الذي يثبت أثر الوصول على العمل؟', '["بلوغه نظاماً أو بياناً حسّاساً","عدد الأوامر التي نُفِّذت عليه","زمن بقاء الجلسة مفتوحة","اسم الأداة التي فتحت الوصول"]'::jsonb, 0, NULL, 'الأثر يُقاس بما بلغه لا بكم فعل، فأمر واحد قد يبلغ أخطر ما في الشبكة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'hard', 'لماذا يُوثَّق كل نظام يُبلَغ لحظة بلوغه؟', '["لتُقاس سرعة الفاحص في الشبكة","ليُعرَف مدى الانتشار بدقة لاحقاً","لترتفع درجة الثغرة في التقرير","ليُختصر زمن الاختبار القادم"]'::jsonb, 1, NULL, 'بعد أسبوع لا يتذكر أحد أي نظام بُلِغ ومتى، والتقرير يقوم على هذا.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'medium', 'ما الذي لا يُنقَل من الأنظمة المبلوغة؟', '["أسماء الأنظمة وعناوينها","إصدارات الخدمات العاملة","بيانات الناس واعتماد الحسابات","أوقات بلوغ كل نظام"]'::jsonb, 2, NULL, 'الثلاثة الأخرى تصف الشبكة، والأول ينقل منها ما جاء الفاحص ليحميه.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'hard', 'ما خطر التوسع بلا حدود مكتوبة؟', '["يطول زمن كتابة التقرير كثيراً","ترتفع كلفة الاختبار على العميل","تكثر النتائج المكررة في التقرير","يبلغ الفاحص ما لا إذن له فيه"]'::jsonb, 3, NULL, 'وعندها يصير الفاحص نفسه حادثة أمنية لا كاشفاً لها.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'medium', 'ما الذي يفصل ما بعد الاستغلال عن الاختراق؟', '["حد مكتوب وأثر يُزال ويُوثَّق","أدوات أحدث وأدق في عملها","سرعة أعلى في بلوغ الأنظمة","إخفاء أفضل عن فريق الأمن"]'::jsonb, 0, NULL, 'الفعل قد يتطابق، والفارق في الإذن والحد وما يبقى بعده.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'hard', 'ما الذي يستوجب التوقف فوراً في هذي المرحلة؟', '["بلوغ نظام يحمل ثغرة عالية","بلوغ نظام خارج ما أُذِن به","بلوغ نظام لم يظهر في الفحص","بلوغ نظام يعمل بإصدار قديم"]'::jsonb, 1, NULL, 'الثلاثة الأخرى تُوثَّق ويُمضى، والخروج عن الإذن يوقف كل شيء.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'لمن يُكتب الملخص التنفيذي؟', '["لمن يصلح الثغرة في الكود","لمن يشغّل أدوات الفحص","لمن يقرّر ولا يقرأ التفصيل","لمن يراجع الاتفاق قانونياً"]'::jsonb, 2, NULL, 'صفحة واحدة بلغة العمل، فمن يوقّع الميزانية لا يقرأ أربعين صفحة تقنية.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'hard', 'ما الذي يجعل نتيجة قابلة للإصلاح؟', '["درجة خطورتها القياسية المعلنة","اسم الأداة التي كشفتها أولاً","عدد الأنظمة التي ظهرت فيها","خطوات إعادة إنتاجها كما وقعت"]'::jsonb, 3, NULL, 'ما لا يستطيع المطوّر تكراره لا يستطيع التحقق من إصلاحه.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'بمَ يُوصف أثر الثغرة في التقرير؟', '["بما يخسره العمل لو استُغِلّت","بدرجتها في التصنيف القياسي","بعدد الأوامر التي لزمت لها","بزمن الفاحص حتى بلغها"]'::jsonb, 0, NULL, 'الإدارة تفهم «تسريب بيانات العملاء» ولا تفهم رقماً من عشرة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'hard', 'ما عيب توصية «رقّع الخدمة»؟', '["لا تذكر درجة الخطورة القياسية","لا تقول أي نسخة ولا أي مضيف","لا تحدد من كشف الثغرة أولاً","لا تشرح كيف عملت الأداة"]'::jsonb, 1, NULL, 'التوصية تُقاس بقابليتها للتنفيذ صباح غدٍ بلا سؤال إضافي.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'ما الذي يُرفَق مع كل نتيجة كدليل؟', '["نسخة من البيانات المبلوغة","اعتماد الحساب المستعمل","الأمر ورده ووقت تنفيذه","سجل الشبكة كاملاً"]'::jsonb, 2, NULL, 'يثبت الواقعة كاملة ولا يخرج من الأنظمة ما لا يلزم إخراجه.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'hard', 'لماذا تُرتَّب النتائج بأثر العمل لا بالدرجة؟', '["الدرجة تتغيّر بعد كل إصدار","الدرجة لا تصدر لكل الثغرات","الدرجة تختلف بين الأدوات","الدرجة لا تعرف قيمة ما تحميه"]'::jsonb, 3, NULL, 'ثغرة ٩ على نظام مختبري أدنى إلحاحاً من ٦ على بوابة الدفع.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'ما الذي يُذكَر عن الثغرات التي لم تُستغَل؟', '["أنها لم تُجرَّب وسبب ذلك","أنها غير قائمة في الأنظمة","أنها أُصلِحت أثناء الاختبار","أنها خارج نطاق الاتفاق دائماً"]'::jsonb, 0, NULL, 'صمت التقرير عنها يُقرأ سلامةً، وهي لم تُفحَص أصلاً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'hard', 'ما الذي يجعل التقرير قابلاً للتحقق لاحقاً؟', '["كتابته بلغة العميل الأم","ربط كل نتيجة بوقتها ونظامها","إرفاق أسماء أدوات الفحص","تقسيمه إلى فصول مرقّمة"]'::jsonb, 1, NULL, 'بلا وقت ونظام لا يستطيع العميل مطابقة النتيجة بسجلاته.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'ما الذي يُحذَف من التقرير قبل تسليمه؟', '["خطوات إعادة إنتاج النتائج","أوقات تنفيذ كل خطوة","الاعتماد والبيانات الحقيقية","حدود ما بلغه الفاحص"]'::jsonb, 2, NULL, 'التقرير يُنسخ ويُتداوَل، فما فيه يصل أوسع مما يُظن.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'hard', 'ما الذي يعنيه غياب نتيجة من التقرير؟', '["أنها أُصلِحت قبل انتهاء الاختبار","أنها خارج النطاق المتفق عليه","أنها أدنى من عتبة الخطورة","أنها لم تُكتشَف لا أنها غير قائمة"]'::jsonb, 3, NULL, 'ولذلك يُصرَّح بحدود ما فُحِص، وإلا قُرِئ التقرير شهادة سلامة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'ما أول ما يُفعَل قبل إغلاق الاختبار؟', '["إزالة كل ما زُرِع والتحقق منه","إرسال الفاتورة النهائية للعميل","حذف سجلات الفاحص من الأنظمة","إغلاق تذاكر النتائج كلها"]'::jsonb, 0, NULL, 'ما يبقى عاملاً على الأنظمة يصير ثغرة أدخلها من جاء يكشفها.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'لماذا يُمنع حذف سجلات الأنظمة بعد الاختبار؟', '["الحذف يحتاج صلاحية إدارية عالية","السجل دليل العميل لا أثر الفاحص","الحذف يبطئ الأنظمة بعد الاختبار","السجل يُدوَّر تلقائياً بعد مدة"]'::jsonb, 1, NULL, 'أثر الفاحص في السجل مطلوب: به يفرّق العميل نشاطه عن نشاط غيره.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'ما الذي يُسلَّم للعميل مع التقرير؟', '["حسابات الفحص كما هي","أدوات الفاحص المستعملة","الأدلة عبر قناة مؤمَّنة","نسخة من الأنظمة المبلوغة"]'::jsonb, 2, NULL, 'الأدلة تصف طريقاً صالحاً للدخول، فقناة تسليمها جزء من حمايتها.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'ما الذي يفعله الفاحص بأدلته بعد التسليم؟', '["يحتفظ بها لاختبار العميل القادم","ينشرها بعد إصلاح الثغرات","ينقلها لجهازه الشخصي للأرشفة","يتلفها بعد المدة المتفق عليها"]'::jsonb, 3, NULL, 'كل يوم تبقى فيه نسخة عنده هو يوم خطر إضافي يتحمّله العميل بلا فائدة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'ما الغرض من إعادة الاختبار؟', '["التأكد أن الإصلاح أزال الثغرة","اكتشاف ثغرات جديدة ظهرت بعده","قياس سرعة فريق الإصلاح","تحديث درجة الخطورة القياسية"]'::jsonb, 0, NULL, 'كثير من الإصلاحات تعالج ظاهر المشكلة ويبقى الطريق سالكاً بصيغة أخرى.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'ما الذي يثبت أن الإصلاح نجح؟', '["إغلاق التذكرة من فريق التطوير","فشل ما كان ينجح قبله بعينه","ارتفاع نسخة الخدمة المعلنة","اختفاء النتيجة من أداة الفحص"]'::jsonb, 1, NULL, 'اختفاء النتيجة من الأداة قد يعني ضبطاً تغيّر لا عيباً زال.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'ما الذي يُوثَّق عن ثغرة لم تُصلَح؟', '["حذفها من التقرير النهائي","خفض درجتها إلى منخفضة","قبول مخاطرتها بمالك ومدة","تأجيلها بلا موعد محدد"]'::jsonb, 2, NULL, 'قرار عدم الإصلاح مشروع، وبلا مالك ولا أجل يصير نسياناً موثّقاً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'ما الذي يميّز اختباراً نافعاً عن اختبار شكلي؟', '["عدد النتائج التي ظهرت فيه","عدد الأنظمة التي شملها","زمن العمل الذي استغرقه","ما تغيّر في الأنظمة بعده"]'::jsonb, 3, NULL, 'تقرير بأربعين نتيجة لم يُصلَح منها شيء يساوي اختباراً لم يقع.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'ما الذي يُراجَع في جلسة الدروس المستفادة؟', '["ما مكّن الثغرة من الظهور أصلاً","أي أداة كشفت أكثر النتائج","كم استغرق الاختبار من أيام","من أصلح أسرع من زملائه"]'::jsonb, 0, NULL, 'إصلاح ثغرة يغلق باباً، ومعرفة سبب ظهورها تغلق أبواباً لم تُفتَح بعد.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'ما الذي يبقى بعد إغلاق الاختبار كله؟', '["حساب الفحص معطّلاً لا محذوفاً","التقرير والأدلة عند العميل","أداة الفاحص على مضيف واحد","وصول احتياطي لإعادة الاختبار"]'::jsonb, 1, NULL, 'لا يبقى على الأنظمة شيء، وما يبقى يبقى عند صاحبها لا عند الفاحص.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'hard', 'ما الذي يخالف الاتفاق هنا؟', '["بلوغ نظام خارج ما أُذِن به","بلوغ نظام يحمل ثغرة عالية","بلوغ نظام لم يظهر في الفحص","بلوغ نظام بإصدار قديم"]'::jsonb, 0, NULL, 'إمكان الوصول من خادم الويب لا يوسّع النطاق، والحد مكتوب لا مستنتج.', 'code', 'النطاق المتفق : خوادم الويب فقط
المنفَّذ      : بلوغ خادم قواعد البيانات
الإذن الإضافي : لم يُطلَب', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'ما الناقص في هذي النتيجة؟', '["درجة الخطورة القياسية ومعرّفها","خطوات إعادة الإنتاج وتوصية محددة","اسم الأداة التي كشفتها أولاً","وقت اكتشاف الثغرة بالدقيقة"]'::jsonb, 1, NULL, 'من يقرؤها لا يعرف كيف يكررها ولا ما يكتبه في الكود غداً.', 'code', 'العنوان : ثغرة حقن في نموذج الدخول
الخطورة: عالية
التوصية: أصلح الثغرة', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'hard', 'ما الخلل في ترتيب النتائج هنا؟', '["رُتِّبت بأثر العمل لا بالدرجة","رُتِّبت بوقت الاكتشاف لا غير","رُتِّبت بالدرجة لا بأثر العمل","رُتِّبت باسم النظام أبجدياً"]'::jsonb, 2, NULL, 'العميل يبدأ من أعلى القائمة، فالترتيب الخاطئ يؤجّل ما يمسّ أمواله.', 'code', '١ · درجة ٩٫١ · نظام مختبري معزول
٢ · درجة ٦٫٢ · بوابة الدفع المنشورة
الترتيب في التقرير: ١ ثم ٢', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'hard', 'ما الذي يجب حذفه قبل التسليم؟', '["الأمر لأنه يكشف الثغرة","رقم النتيجة لأنه داخلي","الدليل كله لأنه لا يلزم","الرد لأنه يحمل بيان شخص"]'::jsonb, 3, NULL, 'يُستبدَل بوصف البنية وعدد الصفوف، فيثبت الوصول بلا نقل بيان أحد.', 'code', 'دليل النتيجة رقم ٧:
الأمر: عرض صف من جدول العملاء
الرد : "سارة | 05xxxxxxx | 1098xxxxxx"', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'ما الذي يثبته هذا الفارق؟', '["أن الإصلاح أغلق هذا الطريق","أن الثغرة زالت من كل الأنظمة","أن الخدمة توقفت عن العمل","أن النسخة تغيّرت رقمها فقط"]'::jsonb, 0, NULL, 'يثبت إغلاق ما جُرِّب بعينه، وبقية الأنظمة تحتاج إعادة اختبار مثله.', 'code', 'قبل الإصلاح: الاستغلال نجح · وصول مثبت
بعد الإصلاح: الاستغلال نفسه فشل', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'ما الخلل في إغلاق الاختبار هذا؟', '["إزالة الأدوات كانت سابقة لأوانها","حذف السجل يتلف دليل العميل","التقرير سُلِّم قبل إعادة الاختبار","الأدوات كان يجب أن تبقى معطّلة"]'::jsonb, 1, NULL, 'إخفاء الأثر فعل مهاجم لا فاحص، وأثر الفاحص في السجل مطلوب لا مذموم.', 'code', 'أُزيلت الأدوات المزروعة ✓
حُذِفت سجلات الأنظمة لإخفاء الأثر ✓
سُلِّم التقرير ✓', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'ما الذي ينقص هذا التسليم؟', '["ملف بصيغة أخف من المضغوط","نسخة إضافية لفريق التطوير","قناة مؤمَّنة تليق بما تحمله","ملخص تنفيذي في أول الملف"]'::jsonb, 2, NULL, 'المرفق خارطة دخول كاملة، وإرسالها بلا تشفير يعيد إنتاج الخطر نفسه.', 'code', 'التقرير: أُرسل بالبريد
الأدلة : أُرفقت في ملف مضغوط
القناة : بريد عادي بلا تشفير', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'hard', 'ما الاستنتاج الخاطئ عن وحدة الدفع؟', '["أن وحدة الدفع لم تُختبَر","أن النافذة كانت قصيرة","أن الوحدة تحتاج اختباراً","أن وحدة الدفع سليمة"]'::jsonb, 3, NULL, 'صفر النتائج هنا يصف غياب الفحص لا غياب الثغرات.', 'code', 'النتائج: ٠ في وحدة الدفع
سبب عدم الاختبار: خارج النافذة المتفقة', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'ما الذي يستوجبه هذا الوضع؟', '["قبول مخاطرة موثّق بمالك ومدة","حذفها من التقرير النهائي","خفض درجتها لتناسب القرار","إعادة اختبارها الأسبوع القادم"]'::jsonb, 0, NULL, 'القرار مشروع، والتوثيق يمنعه من أن يصير تأجيلاً بلا نهاية.', 'code', 'ثغرة عالية · العميل قرر عدم إصلاحها الآن
السبب: تعارض مع إصدار قادم بعد شهرين', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'ما الذي يجب أن يلي هذي الحالة؟', '["إبقاؤه لإعادة الاختبار","سحبه فوراً وتوثيق سحبه","خفض صلاحيته وإبقاؤه","تغيير كلمته وإبقاؤه"]'::jsonb, 1, NULL, 'حساب حيّ بعد انتهاء الإذن وصول بلا سند، ولو لم يستعمله أحد.', 'code', 'حساب الفحص الممنوح للفاحص: ما زال عاملاً
الاختبار: انتهى قبل أسبوعين', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'medium', 'غاية ما بعد الاستغلال قياس أثر الوصول لا توسيعه.', '["صح","خطأ"]'::jsonb, 0, NULL, 'العميل يشتري فهماً لما يترتب على العيب لا برهاناً على المهارة.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'hard', 'قدرة الفاحص التقنية على بلوغ نظام تكفي إذناً ببلوغه.', '["صح","خطأ"]'::jsonb, 1, NULL, 'الاستطاعة ليست إذناً، والإذن بند مكتوب في الاتفاق.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'medium', 'الثبات بقاء الوصول بعد إعادة تشغيل النظام.', '["صح","خطأ"]'::jsonb, 0, NULL, 'وهو ما يحوّل وصولاً عابراً إلى باب دائم، فلا يُفعَل إلا بإذن خاص.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'الملخص التنفيذي يُكتب لمن يقرّر لا لمن يصلح.', '["صح","خطأ"]'::jsonb, 0, NULL, 'صفحة بلغة العمل، فمن يوقّع الميزانية لا يقرأ التفصيل التقني.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'hard', 'ترتيب النتائج بالدرجة القياسية أدق من ترتيبها بأثر العمل.', '["صح","خطأ"]'::jsonb, 1, NULL, 'الدرجة لا تعرف قيمة ما يحميه النظام ولا مدى انكشافه عندك.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'نتيجة بلا خطوات إعادة إنتاج لا تصلح للإصلاح.', '["صح","خطأ"]'::jsonb, 0, NULL, 'ما لا يستطيع المطوّر تكراره لا يستطيع التحقق من إصلاحه.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'hard', 'غياب ثغرة من التقرير يعني أنها غير قائمة.', '["صح","خطأ"]'::jsonb, 1, NULL, 'يعني أنها لم تُكتشَف، ولذلك يُصرَّح بحدود ما فُحِص.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'الأدلة تُسلَّم عبر قناة مؤمَّنة وتُتلَف بعد المدة المتفقة.', '["صح","خطأ"]'::jsonb, 0, NULL, 'تصف طريقاً صالحاً للدخول، فبقاؤها خطر يتحمّله العميل بلا فائدة.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'حذف سجلات الأنظمة بعد الاختبار من حسن الإغلاق.', '["صح","خطأ"]'::jsonb, 1, NULL, 'السجل دليل العميل، وإخفاء الأثر فعل مهاجم لا فاحص.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'إعادة الاختبار تثبت أن ما كان ينجح صار يفشل.', '["صح","خطأ"]'::jsonb, 0, NULL, 'وهذا وحده دليل الإصلاح، لا إغلاق التذكرة ولا اختفاء النتيجة.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'medium', 'صل كل مرحلة بمخرَجها', NULL, NULL, NULL, 'كل مرحلة تُغلَق بمخرَج محدد، وما لم يُثبَت لا يُبنى عليه ما بعده.', 'matching', NULL, '[{"left":"الفحص","right":"ثغرات مرشّحة"},{"left":"الاستغلال","right":"وصول مثبت"},{"left":"ما بعد الاستغلال","right":"أثر الوصول على العمل"},{"left":"التقرير","right":"قرار قابل للتنفيذ"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'hard', 'صل كل فعل بما يبيحه', NULL, NULL, NULL, 'أربعة أفعال بأربعة سقوف مختلفة، وخلطها أشيع سبب لتجاوز الإذن.', 'matching', NULL, '[{"left":"بلوغ نظام ثانٍ","right":"بند مكتوب في الاتفاق"},{"left":"تثبيت وصول","right":"إذن خاص وأثر يُزال"},{"left":"نسخ بيان حقيقي","right":"لا يُباح أصلاً"},{"left":"تنفيذ أمر للإثبات","right":"الإذن العام بالاختبار"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'صل كل قسم في التقرير بقارئه', NULL, NULL, NULL, 'تقرير بقارئ واحد في ذهن كاتبه لا يُقرأ إلا من ذلك القارئ.', 'matching', NULL, '[{"left":"الملخص التنفيذي","right":"من يقرّر"},{"left":"التفصيل الفني","right":"من يصلح"},{"left":"خطوات الإعادة","right":"من يتحقق"},{"left":"سجل المخاطر","right":"من يقبل المخاطرة"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'hard', 'صل كل عنصر في النتيجة بدوره', NULL, NULL, NULL, 'سقوط أي عنصر يترك سؤالاً بلا جواب فتتعطّل المعالجة عنده.', 'matching', NULL, '[{"left":"الوصف","right":"ما العيب"},{"left":"خطوات الإعادة","right":"كيف يُتحقَّق منه"},{"left":"أثر العمل","right":"لماذا يُعالَج الآن"},{"left":"التوصية","right":"ما الذي يُفعَل تحديداً"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'صل كل ما يُسلَّم بشرطه', NULL, NULL, NULL, 'الأخير ليس مما يُسلَّم أصلاً، وبقاؤه أشيع ما يُنسى في الإغلاق.', 'matching', NULL, '[{"left":"التقرير","right":"لغة قارئه"},{"left":"الأدلة","right":"قناة مؤمَّنة"},{"left":"خطوات الإعادة","right":"دقة تكفي للتكرار"},{"left":"حسابات الفحص","right":"تُسحَب لا تُسلَّم"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'صل كل خطأ في الإغلاق بضرره', NULL, NULL, NULL, 'أربعتها تقع بعد انتهاء العمل، وهي المرحلة التي يتساهل فيها الجميع.', 'matching', NULL, '[{"left":"حذف سجلات الأنظمة","right":"إتلاف دليل العميل"},{"left":"ترك حساب الفحص","right":"وصول بلا إذن قائم"},{"left":"الاحتفاظ بالأدلة بلا أجل","right":"خارطة دخول باقية"},{"left":"إغلاق بلا إعادة اختبار","right":"إصلاح غير مثبت"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'صل كل حالة نتيجة بما يُكتَب عنها', NULL, NULL, NULL, 'كل نتيجة تنتهي بحالة مكتوبة، فلا واحدة تسقط بلا أثر في التقرير.', 'matching', NULL, '[{"left":"أُصلِحت وأُعيد اختبارها","right":"مغلقة بدليل"},{"left":"لم تُصلَح بقرار","right":"قبول مخاطرة بمدة"},{"left":"لم تُختبَر","right":"سبب عدم اختبارها"},{"left":"إنذار كاذب","right":"مستبعدة بعد التحقق"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'صل كل مقياس بعد الاختبار بما يقيسه', NULL, NULL, NULL, 'الثالث يُعرَض كإنجاز وهو أقلها دلالة على تحسّن حقيقي.', 'matching', NULL, '[{"left":"زمن الإصلاح","right":"جدّية المعالجة"},{"left":"نسبة المعاد اختبارها","right":"اكتمال الدورة"},{"left":"عدد النتائج","right":"حجم العمل لا الأمان"},{"left":"تكرار النوع","right":"سبب جذري قائم"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'صل كل ما يُحذَف من التقرير بسببه', NULL, NULL, NULL, 'التقرير يُنسخ ويُتداوَل، فما فيه يصل أوسع بكثير مما يُظن.', 'matching', NULL, '[{"left":"الاعتماد المكتشف","right":"مفتاح صالح بعده"},{"left":"بيانات الأشخاص","right":"تسريب في مستند"},{"left":"مسارات داخلية زائدة","right":"تفصيل بلا فائدة"},{"left":"لقطات تحمل أسماء","right":"خصوصية بلا داعٍ"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'hard', 'صل كل سؤال بما يجيب عنه التقرير الجيد', NULL, NULL, NULL, 'السؤال الرابع أكثر ما يُهمَل، وإهماله يحوّل التقرير لشهادة سلامة.', 'matching', NULL, '[{"left":"ما الذي وُجِد؟","right":"النتائج ودليلها"},{"left":"ما أثره؟","right":"ما يخسره العمل"},{"left":"ما العمل؟","right":"توصية محددة"},{"left":"ما لم يُفحَص؟","right":"حدود الشهادة"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'medium', 'اكتب اسم بقاء الوصول بعد إعادة تشغيل النظام', NULL, NULL, NULL, 'يحوّل وصولاً عابراً إلى باب دائم، فلا يُفعَل إلا بإذن خاص.', 'terminal', NULL, NULL, '["الثبات","persistence","الاستمرارية","ثبات الوصول"]'::jsonb, 'المصطلح', 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'hard', 'اكتب اسم الانتقال من نظام مبلوغ إلى نظام آخر في الشبكة', NULL, NULL, NULL, 'لا تُباح إلا ببند مكتوب، فالاستطاعة ليست إذناً.', 'terminal', NULL, NULL, '["الحركة الجانبية","lateral movement","التنقل الجانبي","الحركة الأفقية","الانتقال الجانبي"]'::jsonb, 'المصطلح', 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'اكتب اسم القسم الذي يُكتب لمن يقرّر لا لمن يصلح', NULL, NULL, NULL, 'صفحة بلغة العمل، فمن يوقّع الميزانية لا يقرأ التفصيل التقني.', 'terminal', NULL, NULL, '["الملخص التنفيذي","executive summary","الملخص","ملخص تنفيذي"]'::jsonb, 'القسم', 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'اكتب اسم ما يمكّن غيرك من تكرار النتيجة بنفسه', NULL, NULL, NULL, 'ما لا يستطيع المطوّر تكراره لا يستطيع التحقق من إصلاحه.', 'terminal', NULL, NULL, '["خطوات إعادة الإنتاج","reproduction steps","خطوات الإعادة","إعادة الإنتاج","steps to reproduce"]'::jsonb, 'العنصر', 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'hard', 'اكتب المعيار الذي تُرتَّب به النتائج بدل الدرجة القياسية', NULL, NULL, NULL, 'الدرجة لا تعرف قيمة ما يحميه النظام ولا مدى انكشافه.', 'terminal', NULL, NULL, '["أثر العمل","الأثر على العمل","business impact","الأثر","أثر الأعمال"]'::jsonb, 'المعيار', 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'اكتب اسم التحقق من أن الإصلاح أزال الثغرة فعلاً', NULL, NULL, NULL, 'كثير من الإصلاحات تعالج الظاهر ويبقى الطريق سالكاً بصيغة أخرى.', 'terminal', NULL, NULL, '["إعادة الاختبار","retest","التحقق من الإصلاح","إعادة اختبار","إعادة الفحص"]'::jsonb, 'الإجراء', 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'اكتب ما يُوثَّق لثغرة قرر العميل عدم إصلاحها', NULL, NULL, NULL, 'بلا مالك ولا أجل يصير القرار المشروع نسياناً موثّقاً.', 'terminal', NULL, NULL, '["قبول المخاطرة","risk acceptance","قبول مخاطرة","قبول الخطر","قبول الخطورة"]'::jsonb, 'التوثيق', 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'اكتب ما يجب فعله بحساب الفحص بعد انتهاء الاختبار', NULL, NULL, NULL, 'حساب حيّ بعد انتهاء الإذن وصول بلا سند ولو لم يستعمله أحد.', 'terminal', NULL, NULL, '["سحبه","تعطيله","سحب الحساب","إلغاؤه","حذفه","إبطاله"]'::jsonb, 'الإجراء', 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'اكتب اسم الجلسة التي تراجع ما مكّن الثغرات من الظهور', NULL, NULL, NULL, 'إصلاح ثغرة يغلق باباً، ومعرفة سببها تغلق أبواباً لم تُفتَح بعد.', 'terminal', NULL, NULL, '["الدروس المستفادة","lessons learned","المراجعة البعدية","جلسة الدروس","الدروس المستفادة من الاختبار"]'::jsonb, 'الجلسة', 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'اكتب صفة القناة التي تُسلَّم بها الأدلة', NULL, NULL, NULL, 'المرفق خارطة دخول كاملة، وإرسالها مكشوفة يعيد إنتاج الخطر نفسه.', 'terminal', NULL, NULL, '["مؤمَّنة","مشفّرة","قناة مؤمنة","آمنة","مؤمنة","مشفرة"]'::jsonb, 'الصفة', 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'medium', 'أي مما يلي من ما بعد الاستغلال المأذون؟', '["قياس أثر الوصول على العمل","توسيع الوصول قدر الإمكان","توثيق كل نظام يُبلَغ","نسخ ما يمكن من بيانات"]'::jsonb, NULL, '[0,2]'::jsonb, 'التوسّع والنسخ يزيدان الضرر ولا يزيدان ما يفهمه العميل عن عيبه.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'hard', 'أي مما يلي شرط للحركة إلى نظام ثانٍ؟', '["قدرة الفاحص على بلوغه","بند مكتوب يسمح بها","وجود ثغرة قائمة فيه","كونه داخل النطاق المعتمد"]'::jsonb, NULL, '[1,3]'::jsonb, 'الاستطاعة ووجود الثغرة يصفان الإمكان، والإذن وحده يصف الجواز.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'أي مما يلي يجعل النتيجة قابلة للإصلاح؟', '["خطوات إعادة إنتاجها","درجتها القياسية المعلنة","اسم الأداة التي كشفتها","توصية تحدد ما يُفعَل"]'::jsonb, NULL, '[0,3]'::jsonb, 'الدرجة والأداة تصفان النتيجة ولا تقولان للمطوّر ما يكتبه غداً.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'hard', 'أي مما يلي يدخل في ترتيب النتائج؟', '["اسم الأداة التي كشفتها","أثر الاستغلال على العمل","انكشاف النظام المصاب","عدد أسطر الملف المتأثر"]'::jsonb, NULL, '[1,2]'::jsonb, 'الترتيب يصف موضع الثغرة في عمل العميل لا خصائص الملف ولا الأداة.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'أي مما يلي يُحذَف من التقرير قبل تسليمه؟', '["خطوات إعادة الإنتاج","حدود ما لم يُفحَص","اعتماد الحسابات المكتشفة","بيانات الأشخاص الحقيقية"]'::jsonb, NULL, '[2,3]'::jsonb, 'الأولان جوهر التقرير، والأخيران يحوّلانه إلى مستند تسريب.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'أي مما يلي من إغلاق سليم؟', '["إزالة كل ما زُرِع والتحقق","سحب حسابات الفحص","حذف سجلات الأنظمة","الاحتفاظ بالأدلة بلا أجل"]'::jsonb, NULL, '[0,1]'::jsonb, 'حذف السجل يتلف دليل العميل، وبقاء الأدلة يبقي خارطة دخول حيّة.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'أي مما يلي يُكتَب عن ثغرة لم تُصلَح؟', '["أنها غير قائمة أصلاً","مبرر تأجيل إصلاحها","أنها إنذار كاذب","مالك القبول ومدته"]'::jsonb, NULL, '[1,3]'::jsonb, 'وصفها بغير القائمة أو بالكاذب تزوير لحالتها، والقبول يُوثَّق بمالك وأجل.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'أي مما يلي يثبت نجاح الإصلاح؟', '["فشل ما كان ينجح قبله","إغلاق التذكرة من الفريق","إعادة اختبار موثّقة","ارتفاع رقم نسخة الخدمة"]'::jsonb, NULL, '[0,2]'::jsonb, 'الإغلاق ورقم النسخة ادعاءان، والتجربة وحدها تفصل.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'أي مما يلي يدل على اختبار شكلي؟', '["نتائج مرتّبة بأثر العمل","إعادة اختبار بعد الإصلاح","تقرير بلا خطوات إعادة","نتائج لا يتبعها تغيير"]'::jsonb, NULL, '[2,3]'::jsonb, 'الأولان علامتا نضج، والأخيران يجعلان الاختبار مستنداً لا تحسيناً.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'أي مما يلي يجب أن يبيّنه التقرير؟', '["حدود ما فُحِص فعلاً","سبب ما لم يُفحَص منه","أسماء موظفي العميل","اعتماد الحسابات المكتشفة"]'::jsonb, NULL, '[0,1]'::jsonb, 'بلا تصريح بالحدود يُقرأ التقرير شهادة سلامة لما لم يُفحَص أصلاً.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'medium', 'رتّب مراحل الاختبار من أوله لآخره', '["الاستطلاع وسطح الهجوم","الفحص وتحليل الثغرات","الاستغلال وإثبات الوصول","قياس الأثر ثم التقرير"]'::jsonb, NULL, NULL, 'كل مرحلة تستهلك مخرَج ما قبلها، فالقفز فيها يبني على غير مثبت.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'hard', 'رتّب خطوات بلوغ نظام ثانٍ بإذن', '["التحقق من شموله بالنطاق","طلب إذن خاص إن لزم","بلوغه بأقل أثر ممكن","توثيق ما بُلِغ فيه"]'::jsonb, NULL, NULL, 'التحقق قبل الطلب، فقد يكون مشمولاً أصلاً فلا يلزم إذن جديد.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'رتّب خطوات كتابة نتيجة في التقرير', '["وصف العيب","خطوات إعادة إنتاجه","أثره على العمل","التوصية المحددة"]'::jsonb, NULL, NULL, 'التوصية آخراً لأنها تُشتق من الأثر لا من العيب وحده.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Reporting', 'medium', 'رتّب أقسام التقرير', '["الملخص التنفيذي","نطاق الاختبار وحدوده","النتائج مرتّبة بأثرها","التوصيات وخطة المعالجة"]'::jsonb, NULL, NULL, 'النطاق قبل النتائج، ليُقرأ كل ما بعده داخل حدوده لا مطلقاً.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'رتّب خطوات تجهيز الأدلة للتسليم', '["جمع دليل كل نتيجة","حجب البيانات الحقيقية","التحقق من كفايته","إرساله بقناة مؤمَّنة"]'::jsonb, NULL, NULL, 'الحجب قبل التحقق، لئلا يُبنى الاعتماد على دليل سيُحذَف بعضه.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'رتّب خطوات إغلاق الاختبار', '["إزالة كل ما زُرِع","سحب حسابات الفحص","تسليم التقرير والأدلة","إتلاف الأدلة بعد المدة"]'::jsonb, NULL, NULL, 'لا يُسلَّم تقرير وعلى الأنظمة أثر باقٍ من أدوات الاختبار.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'رتّب خطوات إعادة الاختبار', '["استلام إشعار الإصلاح","إعادة تنفيذ ما نجح سابقاً","مقارنة النتيجة بالسابقة","توثيق الإغلاق أو بقاء الثغرة"]'::jsonb, NULL, NULL, 'يُعاد ما نجح بعينه لا اختبار جديد، وإلا لم تُقَس النتيجة بالسابقة.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'medium', 'رتّب خطوات التعامل مع ثغرة يرفض العميل إصلاحها', '["تبيان أثرها المحتمل","تسجيل قرار عدم الإصلاح","تحديد مالك للمخاطرة","تحديد أجل لمراجعتها"]'::jsonb, NULL, NULL, 'الأثر يُبيَّن أولاً، فالقرار بلا معرفة أثره ليس قراراً.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Closure and Retest', 'hard', 'رتّب خطوات جلسة الدروس المستفادة', '["عرض ما وُجِد من ثغرات","تحديد ما مكّنها من الظهور","اقتراح تغيير في الممارسة","متابعة أثر التغيير لاحقاً"]'::jsonb, NULL, NULL, 'المتابعة آخراً، وبلا شيء يفصل الجلسة النافعة عن اجتماع يُنسى.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Ethical Hacking and Penetration Testing', 5, 'Post-Exploitation Scope', 'medium', 'رتّب خطوات التوقف عند تجاوز النطاق', '["ملاحظة أن النظام خارجه","إيقاف العمل عليه فوراً","إبلاغ العميل عاجلاً","توثيق ما جرى في التقرير"]'::jsonb, NULL, NULL, 'الإيقاف قبل الإبلاغ، فكل دقيقة بعد الملاحظة تجاوز يُحسَب.', 'ordering', NULL, NULL, NULL, NULL, 60, true);

-- تحقق فوري بعد الإدخال
select level, type, count(*)
from public.questions
where track_id = 'CyberSecurity'
  and section_id = 'Ethical Hacking and Penetration Testing'
  and level = 5
  and is_active
group by level, type
order by type;

commit;
