-- الأمن السيبراني · S3 أمن الأنظمة · L4 تقوية الأنظمة
-- 90 سؤالاً · وُلِّد آلياً بعد اجتياز فحوصات عقد الجودة كاملة:
--   توزيع الأنواع 30/10×6 · مواضع الإجابة 8/8/7/7 · صفر فجوة طول ≥7
--   صفر تكرار داخل الدفعة وعبر المسار · كل الأنواع مكتملة البنية
-- التشغيل: لوحة Supabase ← SQL Editor ← الصق ونفّذ.

begin;

insert into public.questions
  (track_id, section_id, level, topic, difficulty, question, options, correct_answer, correct_answers, explanation, type, code_snippet, pairs, expected_answers, prompt_label, time_limit, is_active)
values
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'easy', 'ما المقصود بسطح الهجوم في نظام؟', '["مجموع ما يمكن للمهاجم بلوغه","عدد الثغرات المكتشفة فيه","حجم البيانات المخزّنة عليه","عدد المستخدمين المسجّلين فيه"]'::jsonb, 0, NULL, 'كل منفذ مفتوح وخدمة عاملة وحساب قائم يضيف إليه.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'لماذا تُعطَّل الخدمات غير المستخدمة؟', '["لتسريع إقلاع النظام وحده","لتقليل ما يمكن مهاجمته أصلاً","لتوفير مساحة على القرص","لتقليل عدد ملفات السجل"]'::jsonb, 1, NULL, 'الخدمة المعطّلة لا تُهاجَم ولا تحتاج ترقيعاً ولا مراقبة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'hard', 'لماذا تُفضَّل إزالة الحزمة على تعطيل خدمتها؟', '["الإزالة تحرّر مساحة أكبر بكثير","التعطيل يحذف ملفات الإعداد","الإزالة تمنع إعادة تشغيلها لاحقاً","التعطيل يمنع تحديث الحزمة"]'::jsonb, 2, NULL, 'الخدمة المعطّلة تبقى على القرص فيعيدها تحديث أو مهاجم ببساطة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'ما مبدأ أقل وظيفة؟', '["تشغيل الخدمات بحساب محدود","تقييد المستخدم بمهمة واحدة","منع تثبيت أي برنامج جديد","ألا يحمل النظام إلا ما يلزم دوره"]'::jsonb, 3, NULL, 'خادم قواعد بيانات لا يحتاج متصفحاً ولا خادم طباعة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'ما الخطر الأكبر في الحسابات الافتراضية للأجهزة؟', '["كلمات مرورها منشورة في الأدلة","صلاحياتها أقل من اللازم دائماً","تنتهي صلاحيتها بعد مدة قصيرة","لا يمكن تعطيلها بأي حال"]'::jsonb, 0, NULL, 'المهاجم يجرّبها أولاً لأنها موثّقة علناً لكل طراز.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'ما وظيفة معيار التقوية المنشور؟', '["يفحص النظام بحثاً عن اختراق","يعطي ضبطاً مرجعياً مُختبَراً","يستبدل الحاجة لتحديث النظام","يمنع تثبيت البرامج الخارجية"]'::jsonb, 1, NULL, 'يوفّر نقطة انطلاق مدروسة بدل اجتهاد كل مسؤول وحده.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'hard', 'لماذا لا يُطبَّق معيار التقوية كما هو دون مراجعة؟', '["المعيار يتغيّر كل أسبوع تقريباً","المعيار لا يشمل أنظمة التشغيل","بعض بنود المعيار تعطّل خدمة لازمة","المعيار يشترط ترخيصاً مدفوعاً"]'::jsonb, 2, NULL, 'يُطبَّق على بيئة اختبار أولاً ويُوثَّق كل استثناء بمبرره.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'hard', 'ما المقصود بانحراف الإعداد عن المرجع؟', '["فشل النظام في الإقلاع بعد التقوية","اختلاف المعيار بين إصدارين","تعطّل أداة إدارة الإعداد نفسها","ابتعاد الأنظمة تدريجياً عن ضبطها"]'::jsonb, 3, NULL, 'كل تعديل عاجل غير موثّق يبعد النظام عن مرجعه بصمت.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'ما فائدة النسخة المرجعية للنظام؟', '["تبني كل جهاز جديد مقوّى مسبقاً","تستعيد البيانات بعد فقدها","تراقب تغيّرات الملفات لحظياً","تشفّر القرص عند كل إقلاع"]'::jsonb, 0, NULL, 'التقوية مرة واحدة في الصورة خير من تكرارها على كل جهاز.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'لماذا يُغلَق المنفذ الذي لا تستمع عليه خدمة مطلوبة؟', '["ليقل استهلاك الذاكرة العشوائية","ليمنع بلوغ خدمة لا حاجة لها","ليسرّع استجابة الخدمات الأخرى","ليمنع تسجيل محاولات الاتصال"]'::jsonb, 1, NULL, 'ما لا يُسمع عليه لا يُهاجَم من الشبكة أصلاً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'easy', 'ما الذي تعالجه الترقيعات الأمنية؟', '["بطء النظام تحت الحمل","امتلاء مساحة القرص","ثغرات مكتشفة في البرمجية","أخطاء المستخدم في الإعداد"]'::jsonb, 2, NULL, 'الترقيع يغلق ثغرة معروفة، ولا علاقة له بالأداء ولا بالإعداد.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'لماذا يُختبَر الترقيع قبل نشره على الإنتاج؟', '["ليقل حجمه عند التوزيع","ليُسجَّل في قائمة الأصول","لأن نشره يحتاج إذناً أمنياً","لأنه قد يعطّل تطبيقاً قائماً"]'::jsonb, 3, NULL, 'الترقيع يغيّر سلوك البرمجية، فقد يكسر ما يعتمد عليها.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'hard', 'ما الذي يحدد أولوية ترقيع ثغرة بعينها؟', '["خطورتها وانكشاف النظام لها","تاريخ اكتشاف الثغرة وحده","حجم الترقيع ووقت تثبيته","عدد الأنظمة التي تحملها"]'::jsonb, 0, NULL, 'ثغرة خطيرة على خادم داخلي معزول أقل إلحاحاً من متوسطة على خادم منشور.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'hard', 'لماذا لا تكفي درجة خطورة الثغرة وحدها لترتيب الأولوية؟', '["الدرجة تتغيّر بعد نشرها بأيام","الدرجة لا تعرف بيئتك وضوابطها","الدرجة تُحسب للمهاجم لا للمدافع","الدرجة تخص التطبيقات لا الأنظمة"]'::jsonb, 1, NULL, 'الدرجة عامة، وسياقك يرفعها أو يخفضها بحسب انكشاف النظام.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'ما المقصود بترقيع طارئ خارج الدورة؟', '["ترقيع يُثبَّت بلا إعادة تشغيل","ترقيع يُختبَر على الإنتاج مباشرة","ترقيع يُنشر قبل موعده لخطورته","ترقيع يشمل كل الأنظمة دفعة"]'::jsonb, 2, NULL, 'انتظار الدورة الشهرية قد يكلّف أكثر من مخاطرة النشر العاجل.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'hard', 'ما الذي يميّز ثغرة اليوم صفر؟', '["تُكتشف في أول يوم من إطلاق النظام","تصيب الأنظمة المنتهي دعمها فقط","تُصلَح خلال يوم واحد من كشفها","لا ترقيع لها وقت استغلالها"]'::jsonb, 3, NULL, 'ولذلك تُعالَج بضوابط تعويضية كالعزل حتى يصدر الترقيع.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'hard', 'ما العلاج حين يتعذّر ترقيع نظام منتهي الدعم؟', '["عزله وتقييد ما يصل إليه","رفع صلاحياته لتعويض الضعف","إيقاف تسجيل أحداثه لتقليل الحمل","الاكتفاء بمضاد فيروسات حديث"]'::jsonb, 0, NULL, 'ما لا يُرقَّع يُحاط بضوابط تعويضية تقلّل انكشافه.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'لماذا يُنشر الترقيع على دفعات لا دفعة واحدة؟', '["لتقليل استهلاك عرض النطاق","ليظهر أثره قبل شمول الجميع","لأن الترخيص يحد عدد الأجهزة","لأن الخادم لا يحتمل الطلبات"]'::jsonb, 1, NULL, 'لو كسر الترقيع شيئاً، وقع الضرر على مجموعة لا على المؤسسة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'ما شرط النشر الآمن لأي ترقيع؟', '["موافقة كل مستخدمي النظام","تعطيل الجدار الناري أثناءه","خطة تراجع تعيد الحال السابقة","تثبيته خارج ساعات العمل حصراً"]'::jsonb, 2, NULL, 'ما لا يمكن التراجع عنه لا يُنشر على الإنتاج.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'hard', 'لماذا يبقى جرد الأصول شرطاً لإدارة التحديثات؟', '["يحدد كلفة تراخيص التحديث","يسرّع تحميل الترقيعات كثيراً","يمنع تثبيت ترقيع غير موقّع","لا يُرقَّع ما لا يُعرَف وجوده"]'::jsonb, 3, NULL, 'الجهاز المنسي يبقى بثغرته سنوات لأن أحداً لا يعرف أنه قائم.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'ما الذي يحميه تشفير القرص الكامل؟', '["البيانات عند فقد الجهاز أو سرقته","البيانات من مستخدم مسجّل دخوله","الجهاز من البرمجيات الخبيثة","الاتصال بين الجهاز والخادم"]'::jsonb, 0, NULL, 'بعد الإقلاع والدخول يصير القرص مفكوكاً أمام من دخل.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'hard', 'لماذا لا يحمي تشفير القرص من برمجية خبيثة عاملة؟', '["التشفير يعمل على الملفات فقط","التشفير يُفَك تلقائياً بعد الدخول","التشفير لا يشمل قسم النظام","التشفير يحتاج إذن المستخدم لكل ملف"]'::jsonb, 1, NULL, 'البرمجية تقرأ ما يقرؤه المستخدم لأنها تعمل في جلسته المفكوكة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'ما الذي يتحقق منه الإقلاع الآمن؟', '["هوية المستخدم قبل الدخول","سلامة الملفات على القرص","توقيع ما يُحمَّل قبل النظام","اتصال الجهاز بخادم الإدارة"]'::jsonb, 2, NULL, 'يمنع تحميل محمّل إقلاع أو نواة غير موقّعة بمفتاح موثوق.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'ما وظيفة وحدة النظام الموثوق في الجهاز؟', '["تشفّر حركة الشبكة الصادرة","تفحص الملفات بحثاً عن خبيث","تدير حسابات المستخدمين محلياً","تحفظ المفاتيح في عتاد منفصل"]'::jsonb, 3, NULL, 'حفظ المفتاح خارج القرص يمنع استخراجه بنسخ القرص وحده.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'ما فائدة الجدار الناري على المضيف نفسه؟', '["يقيّد ما يصل الجهاز من داخل الشبكة","يغني عن جدار الشبكة تماماً","يشفّر البيانات قبل إرسالها","يفحص الملفات المحمّلة تلقائياً"]'::jsonb, 0, NULL, 'جدار الشبكة لا يرى حركة تمر بين جهازين داخل الشبكة نفسها.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'ما الفرق بين قائمة السماح وقائمة المنع للبرامج؟', '["الأولى تمنع المعروف والثانية تسمح به","الأولى تمنع كل ما لم يُعتمد","الأولى للخوادم والثانية للمحطات","الأولى تحتاج تحديثاً يومياً دائماً"]'::jsonb, 1, NULL, 'المنع يلاحق ما عُرِف خطره، والسماح يمنع الجديد المجهول تلقائياً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'لماذا يعجز الكشف بالتواقيع عن البرمجيات الجديدة؟', '["التواقيع تحتاج اتصالاً دائماً","التواقيع تفحص الذاكرة دون القرص","التوقيع يُبنى بعد ظهور العيّنة","التوقيع يخص نظام تشغيل واحد"]'::jsonb, 2, NULL, 'ما لم تره العيّنة من قبل لا توقيع له، فيلزم كشف بالسلوك.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'على أي أساس يعمل الكشف السلوكي؟', '["على مطابقة بصمة الملف بقائمة","على مصدر تحميل الملف فقط","على حجم الملف ووقت إنشائه","على ما يفعله الملف لا على شكله"]'::jsonb, 3, NULL, 'تشفير آلاف الملفات فجأة سلوك مريب أياً كان اسم البرنامج.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'لماذا لا يكفي مضاد الفيروسات وحده لحماية المضيف؟', '["يكشف المعروف ويعجز عن الجديد","يستهلك موارد الجهاز بشدة","يعمل على ويندوز دون غيره","يحتاج صلاحية إدارية لتشغيله"]'::jsonb, 0, NULL, 'يبقى طبقة واحدة، ويكمّلها التقوية وقائمة السماح والترقيع.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'ما شرط النسخة الاحتياطية لتصمد أمام برامج الفدية؟', '["أن تُحفَظ على القرص نفسه","أن تكون خارج متناول الجهاز","أن تُشغَّل كل ساعة تقريباً","أن تُضغَط بأعلى نسبة ممكنة"]'::jsonb, 1, NULL, 'نسخة يصلها الجهاز المصاب تُشفَّر معه، فالعزل شرط لا تحسين.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'ما الخدمة التي يجب إيقافها في هذا المخرج؟', '["خدمة النقل النصي غير المشفّر","خدمة الإدارة عن بُعد المؤمَّنة","خدمة خادم الويب المنشور","خدمة جدولة المهام الدورية"]'::jsonb, 0, NULL, 'البروتوكول النصي ينقل الاعتماد مكشوفاً، وبديله المشفّر عامل أصلاً.', 'code', 'sshd.service      running
telnet.socket     running
nginx.service     running
cron.service      running', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'hard', 'ما الخلل في هذا الإعداد للإدارة عن بُعد؟', '["المنفذ الافتراضي يكشف الخدمة","دخول الجذر مباشرة بكلمة مرور","التوثيق بالمفتاح معطّل هنا","الخدمة تعمل بصلاحية محدودة"]'::jsonb, 1, NULL, 'يجمع أعلى صلاحية بأضعف توثيق، فتكفي كلمة مرور واحدة لبلوغ الجذر.', 'code', 'PermitRootLogin yes
PasswordAuthentication yes
Port 22', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'hard', 'ما الذي يكشفه هذا المخرج عن سطح الهجوم؟', '["الخدمتان محصورتان في الجهاز","مخزن الذاكرة مكشوف للشبكة","قاعدة البيانات مكشوفة لكل الشبكة","المنفذان مغلقان أمام الاتصالات"]'::jsonb, 2, NULL, 'العنوان الصفري يعني الاستماع على كل الواجهات، بخلاف عنوان الجهاز المحلي.', 'code', 'tcp  0.0.0.0:3306  LISTEN  mysqld
tcp  127.0.0.1:6379  LISTEN  redis', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'ما الذي يجب فعله بهذا الحساب قبل التشغيل؟', '["رفع صلاحياته لمستوى أعلى","نسخه لحساب احتياطي مماثل","إبقاؤه لتسهيل الدعم لاحقاً","تغيير اعتماده الافتراضي فوراً"]'::jsonb, 3, NULL, 'الاعتماد الافتراضي منشور لكل طراز، فهو أول ما يُجرَّب.', 'code', 'device: switch-core-01
account: admin
password: admin
status: enabled', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'hard', 'أي نظام يُرقَّع أولاً بحسب هذا التقرير؟', '["النظام الأول لاجتماع الخطورة والانكشاف","النظام الثاني لتساوي درجة الخطورة","النظام الثالث لأنه منشور أيضاً","الثلاثة معاً بلا ترتيب أولوية"]'::jsonb, 0, NULL, 'الأولوية حاصل الخطورة في الانكشاف، لا الدرجة وحدها.', 'code', 'A: خطورة 9.8 · خادم منشور للإنترنت
B: خطورة 9.8 · خادم داخلي معزول
C: خطورة 5.4 · خادم منشور للإنترنت', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'ما الذي يستوجب إجراءً عاجلاً في هذا السجل؟', '["النظام يحتاج إعادة تشغيل دورية","النظام لا يتلقى ترقيعات بعد اليوم","النظام يحتاج ترخيصاً جديداً فقط","النظام يعمل بإصدار قديم مقبول"]'::jsonb, 1, NULL, 'انتهاء الدعم يعني ثغرات مفتوحة للأبد، فيلزم العزل أو الترقية.', 'code', 'os: Windows Server 2012 R2
support ended: 2023-10-10
patches available: none', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'ما الخطأ في خطة النشر هذي؟', '["المراقبة تسبق التثبيت هنا","التراجع خطوة زائدة عن الحاجة","النشر شامل قبل التحقق من أثره","الخطة تفتقر لتحديد وقت النشر"]'::jsonb, 2, NULL, 'الترتيب يجعل الضرر شاملاً قبل اكتشافه، والصحيح دفعة صغيرة أولاً.', 'code', 'الخطوة ١: تثبيت الترقيع على كل الخوادم
الخطوة ٢: مراقبة النتيجة
الخطوة ٣: التراجع عند الفشل', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'hard', 'ما الخلل في قاعدة الجدار الناري هذي؟', '["تمنع الإدارة عن بُعد تماماً","تحصر الوصول في شبكة الإدارة","تسمح بالمنفذ للخوادم فقط","تفتح إدارة سطح المكتب للجميع"]'::jsonb, 3, NULL, 'منفذ الإدارة يُحصَر في شبكة الإدارة لا يُفتح لأي مصدر.', 'code', 'allow  from any  to any  port 3389', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'hard', 'ما الذي تكشفه سياسة تشغيل البرامج هذي؟', '["تسمح بأي برنامج جديد مجهول","تمنع كل ما لم يُعتمد صراحة","تحصر التشغيل في مجلد واحد","تمنع تشغيل البرامج الموقّعة"]'::jsonb, 0, NULL, 'الافتراضي سماح، فأي ملف لم يُدرَج في المنع يعمل بلا اعتراض.', 'code', 'policy: block-listed-only
blocked: known_malware.exe, bad_tool.exe
default: allow', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'hard', 'ما العيب في خطة النسخ الاحتياطي هذي؟', '["الوجهة أبطأ من المصدر بكثير","الوجهة يصلها ما يصيب المصدر","الوجهة تحتاج تشفيراً إضافياً","الوجهة تمتلئ قبل المصدر عادة"]'::jsonb, 1, NULL, 'فدية تصيب الجهاز تشفّر القرصين معاً، فالنسخة المتصلة ليست نجاة.', 'code', 'المصدر: D:\data
الوجهة: E:\backup
الجهاز نفسه · متصل دائماً', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'تعطيل خدمة غير مستخدمة يقلّل سطح الهجوم وعبء الترقيع معاً.', '["صح","خطأ"]'::jsonb, 0, NULL, 'ما لا يعمل لا يُهاجَم ولا يحتاج متابعة تحديثاته.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'hard', 'تطبيق معيار التقوية كاملاً على الإنتاج مباشرة ممارسة سليمة.', '["صح","خطأ"]'::jsonb, 1, NULL, 'بعض بنوده تعطّل خدمات يحتاجها العمل، فيسبقه اختبار وتوثيق استثناءات.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'الخدمة المعطّلة تبقى قابلة لإعادة التشغيل ما دامت مثبّتة.', '["صح","خطأ"]'::jsonb, 0, NULL, 'ولذلك تُفضَّل الإزالة على التعطيل حين لا يحتاجها النظام.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'النسخة المرجعية المقوّاة تغني عن مراجعة الأجهزة بعد نشرها.', '["صح","خطأ"]'::jsonb, 1, NULL, 'الإعداد ينحرف عن مرجعه مع كل تعديل عاجل غير موثّق.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'ثغرة عالية الخطورة على نظام معزول قد تتأخر عن متوسطة على نظام منشور.', '["صح","خطأ"]'::jsonb, 0, NULL, 'الأولوية تجمع الخطورة والانكشاف، لا الدرجة وحدها.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'ثغرة اليوم صفر يمكن إغلاقها بترقيع فور اكتشافها.', '["صح","خطأ"]'::jsonb, 1, NULL, 'لا ترقيع لها وقت الاستغلال، فتُعالَج بضوابط تعويضية مؤقتة.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'النظام غير المسجّل في جرد الأصول يبقى بثغراته بلا ترقيع.', '["صح","خطأ"]'::jsonb, 0, NULL, 'لا يُرقَّع ما لا يعرف أحد بوجوده أصلاً.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'hard', 'تشفير القرص يحمي الملفات من مستخدم فتح الجلسة فعلاً.', '["صح","خطأ"]'::jsonb, 1, NULL, 'القرص يُفَك عند الدخول، فيقرأ ما يقرؤه صاحب الجلسة.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'قائمة السماح تمنع البرنامج الجديد المجهول دون معرفة سابقة به.', '["صح","خطأ"]'::jsonb, 0, NULL, 'ما لم يُعتمد لا يعمل، بخلاف المنع الذي يلاحق المعروف فقط.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'النسخة الاحتياطية المتصلة دائماً بالجهاز كافية ضد برامج الفدية.', '["صح","خطأ"]'::jsonb, 1, NULL, 'ما يصله الجهاز المصاب يُشفَّر معه، فالعزل شرط لا تحسين.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'صل كل إجراء تقوية بما يقلّله', NULL, NULL, NULL, 'كل إجراء يغلق باباً مختلفاً، فلا يغني واحد عن الآخر.', 'matching', NULL, '[{"left":"إزالة الحزم الزائدة","right":"ما يمكن مهاجمته على النظام"},{"left":"إغلاق المنافذ","right":"ما يُبلَغ من الشبكة"},{"left":"تغيير الاعتماد الافتراضي","right":"ما يُجرَّب أول محاولة"},{"left":"تقييد الحسابات","right":"ما يُفعَل بعد الدخول"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'صل كل مصطلح تقوية بمعناه', NULL, NULL, NULL, 'الأربعة تصف دورة واحدة: قلّل ثم وحّد ثم راقب الانحراف.', 'matching', NULL, '[{"left":"سطح الهجوم","right":"مجموع ما يمكن بلوغه"},{"left":"أقل وظيفة","right":"ما يلزم الدور لا أكثر"},{"left":"النسخة المرجعية","right":"صورة مقوّاة يُبنى منها"},{"left":"انحراف الإعداد","right":"ابتعاد تدريجي عن المرجع"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'hard', 'صل كل ضبط خاطئ بأثره', NULL, NULL, NULL, 'ثلاثتها لا تحتاج ثغرة برمجية، وإنما إعداداً تُرك كما جاء.', 'matching', NULL, '[{"left":"دخول الجذر مباشرة","right":"أعلى صلاحية بأضعف توثيق"},{"left":"استماع على كل الواجهات","right":"خدمة داخلية مكشوفة للشبكة"},{"left":"اعتماد افتراضي باق","right":"دخول بلا استغلال ثغرة"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'صل كل حالة ترقيع بإجرائها', NULL, NULL, NULL, 'الإجراء يتبع حالة الترقيع لا خطورة الثغرة وحدها.', 'matching', NULL, '[{"left":"ثغرة حرجة منشورة","right":"ترقيع طارئ خارج الدورة"},{"left":"ثغرة متوسطة داخلية","right":"الدورة الدورية المعتادة"},{"left":"ثغرة بلا ترقيع بعد","right":"ضوابط تعويضية مؤقتة"},{"left":"نظام منتهي الدعم","right":"عزل أو ترقية كاملة"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'hard', 'صل كل عنصر في إدارة التحديثات بغرضه', NULL, NULL, NULL, 'إسقاط أي عنصر يحوّل الترقيع نفسه إلى مصدر عطل.', 'matching', NULL, '[{"left":"جرد الأصول","right":"معرفة ما يجب ترقيعه"},{"left":"بيئة الاختبار","right":"كشف ما يكسره الترقيع"},{"left":"النشر التدريجي","right":"حصر الضرر في مجموعة"},{"left":"خطة التراجع","right":"استعادة الحال قبل الفشل"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'صل كل ضابط حماية بما يواجهه', NULL, NULL, NULL, 'كل ضابط يواجه تهديداً بعينه ولا يغطي غيره.', 'matching', NULL, '[{"left":"تشفير القرص","right":"فقد الجهاز أو سرقته"},{"left":"الإقلاع الآمن","right":"تحميل نواة غير موقّعة"},{"left":"الجدار على المضيف","right":"حركة داخل الشبكة نفسها"},{"left":"قائمة السماح","right":"تشغيل برنامج غير معتمد"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'صل كل أسلوب كشف بأساسه', NULL, NULL, NULL, 'الأول يعجز عن الجديد، والثاني يخطئ أحياناً، والثالث يمنعه أصلاً.', 'matching', NULL, '[{"left":"الكشف بالتواقيع","right":"بصمة عيّنة معروفة سلفاً"},{"left":"الكشف السلوكي","right":"ما يفعله البرنامج فعلاً"},{"left":"قائمة السماح","right":"اعتماد مسبق للمسموح"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'hard', 'صل كل مكوّن حماية بموضعه', NULL, NULL, NULL, 'الحماية طبقات في مواضع مختلفة من دورة التشغيل.', 'matching', NULL, '[{"left":"وحدة النظام الموثوق","right":"عتاد منفصل يحفظ المفاتيح"},{"left":"الإقلاع الآمن","right":"مرحلة ما قبل تحميل النظام"},{"left":"مضاد البرمجيات","right":"نظام التشغيل أثناء عمله"},{"left":"النسخة المعزولة","right":"خارج متناول الجهاز"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'صل كل مصطلح تحديث بمعناه', NULL, NULL, NULL, 'ثلاثة منها تصف غياب الترقيع لا وجوده.', 'matching', NULL, '[{"left":"ثغرة اليوم صفر","right":"لا ترقيع لها وقت استغلالها"},{"left":"ترقيع طارئ","right":"يُنشر قبل موعد الدورة"},{"left":"ضابط تعويضي","right":"بديل مؤقت عن الترقيع"},{"left":"نهاية الدعم","right":"انقطاع الترقيعات نهائياً"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'hard', 'صل كل خيار بأثره على قابلية الاستعادة', NULL, NULL, NULL, 'كلما زاد الحسم قل التراجع، والاختيار بحسب حساسية النظام.', 'matching', NULL, '[{"left":"إزالة الحزمة","right":"يلزم تثبيتها لإعادتها"},{"left":"تعطيل الخدمة","right":"تعود بأمر واحد"},{"left":"حذف الحساب","right":"يفقد الأثر مع الوصول"},{"left":"تعطيل الحساب","right":"يقطع الوصول ويبقي الأثر"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'اكتب المصطلح الذي يصف مجموع ما يستطيع المهاجم بلوغه في النظام', NULL, NULL, NULL, 'كل منفذ وخدمة وحساب قائم يضيف إليه.', 'terminal', NULL, NULL, '["سطح الهجوم","attack surface","مساحة الهجوم","سطح الهجوم للنظام"]'::jsonb, 'المصطلح', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'اكتب اسم المبدأ الذي يمنع تحميل النظام ما لا يلزم دوره', NULL, NULL, NULL, 'خادم قواعد بيانات لا يحتاج متصفحاً ولا خادم طباعة.', 'terminal', NULL, NULL, '["أقل وظيفة","مبدأ أقل وظيفة","least functionality","الحد الأدنى من الوظائف"]'::jsonb, 'المبدأ', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'hard', 'اكتب المصطلح الذي يصف ابتعاد الأنظمة تدريجياً عن ضبطها المرجعي', NULL, NULL, NULL, 'كل تعديل عاجل غير موثّق يبعد النظام عن مرجعه بصمت.', 'terminal', NULL, NULL, '["انحراف الإعداد","configuration drift","انحراف التهيئة","الانحراف عن المرجع","زحف الإعداد"]'::jsonb, 'المصطلح', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'اكتب اسم الثغرة التي لا يوجد لها ترقيع وقت استغلالها', NULL, NULL, NULL, 'تُعالَج بضوابط تعويضية حتى يصدر الترقيع.', 'terminal', NULL, NULL, '["ثغرة اليوم صفر","يوم صفر","zero day","zero-day","ثغرة صفرية"]'::jsonb, 'المصطلح', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'hard', 'اكتب اسم الضابط البديل المؤقت حين يتعذّر ترقيع النظام', NULL, NULL, NULL, 'العزل وتقييد الوصول يقلّلان انكشاف ما لا يُرقَّع.', 'terminal', NULL, NULL, '["ضابط تعويضي","الضوابط التعويضية","compensating control","ضابط بديل","ضوابط تعويضية"]'::jsonb, 'الضابط', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'اكتب اسم الخطة التي تعيد النظام لحاله قبل الترقيع عند فشله', NULL, NULL, NULL, 'ما لا يمكن التراجع عنه لا يُنشر على الإنتاج.', 'terminal', NULL, NULL, '["خطة التراجع","التراجع","rollback","خطة الرجوع","خطة الاستعادة"]'::jsonb, 'الخطة', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'اكتب اسم القائمة التي بدونها يبقى الجهاز المنسي بلا ترقيع', NULL, NULL, NULL, 'لا يُرقَّع ما لا يعرف أحد بوجوده أصلاً.', 'terminal', NULL, NULL, '["جرد الأصول","قائمة الأصول","asset inventory","سجل الأصول","حصر الأصول"]'::jsonb, 'الشرط', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'اكتب اسم الآلية التي تتحقق من توقيع ما يُحمَّل عند الإقلاع', NULL, NULL, NULL, 'تمنع تحميل محمّل إقلاع أو نواة غير موقّعة بمفتاح موثوق.', 'terminal', NULL, NULL, '["الإقلاع الآمن","secure boot","التمهيد الآمن","الإقلاع الموثوق"]'::jsonb, 'الآلية', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'اكتب اسم الأسلوب الذي يمنع تشغيل كل برنامج لم يُعتمد مسبقاً', NULL, NULL, NULL, 'يمنع الجديد المجهول تلقائياً بخلاف قائمة المنع.', 'terminal', NULL, NULL, '["قائمة السماح","القائمة البيضاء","allowlisting","whitelisting","قوائم السماح"]'::jsonb, 'الأسلوب', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'اكتب اسم الكشف الذي يعتمد على ما يفعله البرنامج لا على بصمته', NULL, NULL, NULL, 'تشفير آلاف الملفات فجأة سلوك مريب أياً كان اسم البرنامج.', 'terminal', NULL, NULL, '["الكشف السلوكي","التحليل السلوكي","behavioral detection","الكشف بالسلوك","كشف سلوكي"]'::jsonb, 'الأساس', 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'أي مما يلي يقلّل سطح الهجوم؟', '["إزالة الحزم التي لا يحتاجها الدور","إغلاق المنافذ غير المستخدمة","إضافة حساب إداري احتياطي","تثبيت أدوات إدارة إضافية"]'::jsonb, NULL, '[0,1]'::jsonb, 'الإضافة توسّع السطح، والحذف وحده يقلّصه.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'hard', 'أي مما يلي صحيح عن معايير التقوية المنشورة؟', '["تُطبَّق حرفياً بلا مراجعة","تحل محل تحديث النظام","تعطي ضبطاً مرجعياً مُختبَراً","قد تعطّل خدمة يحتاجها العمل"]'::jsonb, NULL, '[2,3]'::jsonb, 'مرجع نافع يسبقه اختبار وتُوثَّق استثناءاته.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'أي مما يلي يدخل في ترتيب أولوية الترقيع؟', '["درجة خطورة الثغرة","انكشاف النظام لها","حجم ملف الترقيع","لون واجهة النظام"]'::jsonb, NULL, '[0,1]'::jsonb, 'الأولوية حاصل الخطورة في الانكشاف لا خصائص الملف.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'hard', 'أي مما يلي شرط لنشر ترقيع بأمان؟', '["تعطيل الجدار الناري أثناء النشر","اختباره على بيئة مماثلة","نشره على الجميع دفعة واحدة","خطة تراجع جاهزة قبل البدء"]'::jsonb, NULL, '[1,3]'::jsonb, 'النشر الشامل يعمّم الضرر، وتعطيل الجدار يفتح باباً بلا داعٍ.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'hard', 'أي مما يلي يصلح لنظام منتهي الدعم؟', '["عزله عن بقية الشبكة","رفع صلاحياته لتعويض ضعفه","تقييد ما يصل إليه بدقة","إبقاؤه منشوراً كما هو"]'::jsonb, NULL, '[0,2]'::jsonb, 'ما لا يُرقَّع يُحاط بضوابط تعويضية تقلّل انكشافه.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'أي مما يلي يحميه تشفير القرص الكامل؟', '["الجهاز المسروق من قراءة قرصه","الجلسة المفتوحة من برمجية خبيثة","القرص المنزوع من قراءته بجهاز آخر","الشبكة من اعتراض الحركة"]'::jsonb, NULL, '[0,2]'::jsonb, 'الحماية للبيانات ساكنة، وتزول بفكّ القرص عند الدخول.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'hard', 'أي مما يلي صحيح عن قائمة السماح؟', '["تمنع كل ما لم يُعتمد مسبقاً","تحتاج تحديث تواقيع يومياً","تحتاج جرداً دقيقاً للبرامج المستخدمة","تسمح بالبرامج الجديدة تلقائياً"]'::jsonb, NULL, '[0,2]'::jsonb, 'قوتها في المنع الافتراضي، وكلفتها في إدارة قائمة المعتمد.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'hard', 'أي مما يلي شرط في النسخة الاحتياطية الصامدة؟', '["أن تكون على القرص نفسه","أن تُختبَر استعادتها فعلاً","أن تُشغَّل بحساب إداري دائم","أن تكون خارج متناول الجهاز"]'::jsonb, NULL, '[1,3]'::jsonb, 'نسخة متصلة تُشفَّر مع الجهاز، وغير المختبَرة افتراض لا نسخة.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'hard', 'أي مما يلي من مخاطر ترك الإعداد الافتراضي؟', '["اعتماد منشور يُجرَّب أولاً","خدمات عاملة لا يحتاجها الدور","تشفير أقوى من اللازم","سجلات مفصّلة أكثر من اللازم"]'::jsonb, NULL, '[0,1]'::jsonb, 'الافتراضي مصمَّم للتشغيل السهل لا للتشغيل الآمن.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'أي مما يلي يعالجه الجدار الناري على المضيف؟', '["حركة قادمة من جهاز في الشبكة نفسها","تشفير الملفات على القرص","حصر المنافذ المستمعة على الجهاز","التحقق من توقيع النواة"]'::jsonb, NULL, '[0,2]'::jsonb, 'جدار الشبكة لا يرى ما يمر بين جهازين داخلها.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'medium', 'رتّب مراحل إدارة التحديثات', '["جرد الأنظمة القائمة","تحديد الترقيعات اللازمة","اختبارها على بيئة مماثلة","نشرها تدريجياً على الإنتاج"]'::jsonb, NULL, NULL, 'الجرد أولاً لأن ما لا يُعرَف لا يُرقَّع.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'hard', 'رتّب خطوات التعامل مع ثغرة حرجة معلنة', '["تحديد الأنظمة المتأثرة","تقدير الانكشاف والأولوية","تطبيق ضابط تعويضي فوراً","ترقيع الأنظمة بعد الاختبار"]'::jsonb, NULL, NULL, 'الضابط التعويضي يسبق الترقيع لأنه يعمل في ساعته.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Patch Management', 'hard', 'رتّب خطوات التراجع عن ترقيع كسر خدمة', '["رصد العطل بعد النشر","إيقاف نشره على الباقي","إعادة الحال على المتأثر","إبلاغ المزوّد بالمشكلة"]'::jsonb, NULL, NULL, 'إيقاف النشر يسبق الإصلاح لأنه يمنع اتساع الضرر.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'رتّب خطوات تقوية خادم جديد', '["تثبيت النظام بأقل حزم","تغيير الاعتماد الافتراضي","تعطيل الخدمات الزائدة","تطبيق معيار التقوية المعتمد"]'::jsonb, NULL, NULL, 'الاعتماد الافتراضي يُغيَّر مبكراً لأنه أسهل طريق للدخول.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'hard', 'رتّب خطوات معالجة انحراف الإعداد عن المرجع', '["مقارنة الجهاز بالمرجع","حصر الفروق ومبرراتها","إعادة الضبط أو توثيق الاستثناء","إعادة الفحص للتأكد"]'::jsonb, NULL, NULL, 'بعض الفروق مبرر فعلي فيُوثَّق استثناءً لا يُلغى.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'medium', 'رتّب خطوات بناء نسخة مرجعية مقوّاة', '["تثبيت النظام الأساسي","تطبيق التقوية والترقيعات","اختبار عمل التطبيقات عليها","اعتمادها لبناء الأجهزة"]'::jsonb, NULL, NULL, 'الاعتماد آخر خطوة لأن الصورة تُنسَخ على كل جهاز بعده.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'رتّب طبقات الحماية بحسب لحظة عملها', '["الإقلاع الآمن قبل تحميل النظام","تشفير القرص عند فكّه","قائمة السماح عند التشغيل","الكشف السلوكي أثناء العمل"]'::jsonb, NULL, NULL, 'كل طبقة تعمل في لحظة مختلفة من دورة التشغيل.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'medium', 'رتّب خطوات تأمين النسخ الاحتياطي', '["تحديد ما يجب نسخه","جدولة النسخ الدوري","عزل النسخة عن الجهاز","اختبار الاستعادة فعلياً"]'::jsonb, NULL, NULL, 'الاختبار آخراً لأنه ما يحوّل النسخة من افتراض إلى نجاة.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'Host Protection', 'hard', 'رتّب خطوات تطبيق قائمة السماح تدريجياً', '["حصر البرامج المستخدمة فعلاً","تشغيلها في وضع المراقبة","مراجعة ما كان سيُمنَع","تفعيل المنع بعد الضبط"]'::jsonb, NULL, NULL, 'التفعيل قبل المراقبة يوقف عمل المؤسسة في ساعته.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'System and Operating System Security', 4, 'System Hardening', 'hard', 'رتّب خطوات إيقاف خدمة غير لازمة بأمان', '["التحقق من عدم اعتماد غيرها عليها","إيقافها ومراقبة الأثر","منع تشغيلها عند الإقلاع","إزالة حزمتها إن لم تُحتَج"]'::jsonb, NULL, NULL, 'الإزالة آخراً لأنها الأصعب تراجعاً عند اكتشاف اعتماد خفي.', 'ordering', NULL, NULL, NULL, NULL, 60, true);

-- تحقق فوري بعد الإدخال
select level, type, count(*)
from public.questions
where track_id = 'CyberSecurity'
  and section_id = 'System and Operating System Security'
  and level = 4
  and is_active
group by level, type
order by type;

commit;
