-- الأمن السيبراني · S4 أمن التطبيقات · L4 البرمجة الآمنة
-- 90 سؤالاً · وُلِّد آلياً بعد اجتياز فحوصات عقد الجودة كاملة:
--   توزيع الأنواع 30/10×6 · مواضع الإجابة 8/8/7/7 · صفر فجوة طول ≥7
--   صفر تكرار داخل الدفعة وعبر المسار · كل الأنواع مكتملة البنية
-- التشغيل: لوحة Supabase ← SQL Editor ← الصق ونفّذ.

begin;

insert into public.questions
  (track_id, section_id, level, topic, difficulty, question, options, correct_answer, correct_answers, explanation, type, code_snippet, pairs, expected_answers, prompt_label, time_limit, is_active)
values
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'ما الغرض من نمذجة التهديدات قبل الكتابة؟', '["حصر ما قد يُهاجَم قبل بنائه","قياس أداء التطبيق تحت الحمل","توثيق واجهات التطبيق للفريق","تقدير كلفة تطوير المشروع"]'::jsonb, 0, NULL, 'إصلاح تصميم على الورق أرخص من إصلاحه بعد النشر بكثير.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'hard', 'ما حدّ الثقة في التطبيق؟', '["الحد الأقصى لعدد المستخدمين الموثوقين","الموضع الذي تنتقل فيه البيانات لطبقة أوثق","مدة بقاء الجلسة قبل انتهائها","عدد الخدمات التي يثق بها التطبيق"]'::jsonb, 1, NULL, 'عنده يقع الفحص، فما عبره بلا تحقق دخل وهو غير موثوق.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'ما معنى أن يفشل التطبيق مغلقاً؟', '["يتوقف عن العمل عند أي خطأ","يغلق الاتصال بقاعدة البيانات","يمنع العملية عند تعذّر التحقق","يعيد المستخدم لصفحة الدخول"]'::jsonb, 2, NULL, 'انقطاع خدمة التحقق يجب أن يعني منعاً لا سماحاً افتراضياً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'لماذا تُفضَّل قائمة المسموح على قائمة الممنوع في التحقق؟', '["تُكتب بأسطر أقل في الكود","تعمل أسرع عند الفحص","تقبل مدخلات أكثر تنوّعاً","تمنع ما لم يُتوقَّع من صيغ"]'::jsonb, 3, NULL, 'قائمة الممنوع تلاحق ما عُرِف، والمهاجم يبحث عمّا لم يخطر ببال كاتبها.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'ما المقصود بالإعداد الافتراضي الآمن؟', '["أن يُشحن التطبيق مقيّداً لا مفتوحاً","أن يعمل التطبيق بلا إعداد إضافي","أن يمنع تغيير الإعدادات لاحقاً","أن يستخدم كلمة مرور موحّدة"]'::jsonb, 0, NULL, 'من يحتاج التوسعة يطلبها واعياً، بخلاف من ورث انفتاحاً لم ينتبه له.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'لماذا يُنصح بعدم كتابة خوارزميات التشفير محلياً؟', '["تستهلك وقت تطوير أطول من اللازم","أخطاؤها الدقيقة لا تظهر بالاختبار","تحتاج صلاحيات نظام مرتفعة","لا تعمل على كل أنظمة التشغيل"]'::jsonb, 1, NULL, 'التشفير المكسور يعمل ويعطي ناتجاً يبدو سليماً، فلا يكشفه اختبار وظيفي.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'hard', 'ما ثغرة الفارق بين وقت الفحص ووقت الاستخدام؟', '["استغراق الفحص وقتاً أطول من اللازم","تعطّل الفحص عند تعدد الطلبات","تغيّر الحالة بعد الفحص وقبل التنفيذ","تكرار الفحص مرتين بلا داعٍ"]'::jsonb, 2, NULL, 'يُفحص الملف ثم يُستبدل قبل استخدامه، فينفَّذ غير ما فُحص.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'أين يجب أن يقع التحقق من صحة المدخل؟', '["في العميل لتقليل الطلبات","في قاعدة البيانات وحدها","في الجدار الناري أمام التطبيق","في الخادم مهما تحقق العميل"]'::jsonb, 3, NULL, 'فحص العميل تحسين للتجربة، ويُتجاوَز بإرسال الطلب مباشرة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'hard', 'ما مبدأ أقل صلاحية في اتصال التطبيق بقاعدة البيانات؟', '["حساب يقرأ ويكتب ما يلزمه فقط","حساب واحد لكل خدمات التطبيق","حساب إداري لتفادي أخطاء الصلاحية","حساب يتغيّر مع كل نشر جديد"]'::jsonb, 0, NULL, 'حقن ناجح على حساب قارئ لا يحذف جدولاً ولا يغيّر بنية.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'ما فائدة الفصل بين المكوّنات في التصميم؟', '["يقلّل عدد أسطر الكود المكتوبة","يحصر أثر اختراق مكوّن واحد","يسرّع بناء التطبيق ونشره","يلغي الحاجة لفحص المدخلات"]'::jsonb, 1, NULL, 'ما لا يصل غيره لا ينقل إليه ما أصابه.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'لماذا تُعد ثغرة المكتبة الخارجية ثغرة عندك؟', '["كودها يُنسخ داخل ملفاتك","كودها يُراجَع مع كودك دائماً","كودها يعمل بصلاحيات تطبيقك","كودها يعمل على خادم منفصل"]'::jsonb, 2, NULL, 'المستخدم يُصاب من تطبيقك لا من المكتبة، والمسؤولية عليك.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'ما الاعتمادية غير المباشرة؟', '["مكتبة تُحمَّل وقت التشغيل فقط","مكتبة اختيارية يمكن تعطيلها","مكتبة مكتوبة بلغة مختلفة","مكتبة تجلبها مكتبة أخرى معها"]'::jsonb, 3, NULL, 'أغلب ما يعمل في التطبيق لم يُختَر مباشرة، وثغراته تصيبك كذلك.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'ما وظيفة ملف تثبيت الإصدارات؟', '["يضمن تركيب المكتبات نفسها دائماً","يمنع تحديث المكتبات نهائياً","يقلّل حجم المكتبات المحمّلة","يفحص المكتبات بحثاً عن ثغرات"]'::jsonb, 0, NULL, 'بلا تثبيت قد يعمل الاختبار على نسخة والإنتاج على أخرى.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'ما خطر مكتبة توقّف صاحبها عن صيانتها؟', '["حجمها يكبر مع كل إصدار","ثغراتها تبقى بلا ترقيع","ترخيصها ينتهي بعد مدة","أداؤها يتراجع مع الوقت"]'::jsonb, 1, NULL, 'الاكتشاف يستمر بعد توقف الصيانة، فيصير الاستخدام مخاطرة متراكمة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'hard', 'ما هجوم التشابه في اسم الحزمة؟', '["تعديل حزمة قائمة بعد نشرها","حذف حزمة يعتمد عليها الجميع","نشر حزمة باسم قريب من الشائعة","رفع نسخة قديمة برقم أعلى"]'::jsonb, 2, NULL, 'خطأ حرف واحد في التركيب يجلب كوداً خبيثاً بصلاحيات المطوّر.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'ما وظيفة أداة فحص الاعتماديات؟', '["تحدّث المكتبات تلقائياً","تحذف المكتبات غير المستخدمة","تقيس أداء كل مكتبة","تطابق نسخك بثغرات معلنة"]'::jsonb, 3, NULL, 'تكشف ما تحمله من ثغرات معروفة دون قراءة كودها كله.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'لماذا لا يكفي تحديث المكتبات مرة واحدة؟', '["الثغرات تُكتشف بعد الإطلاق باستمرار","المكتبات تفقد توافقها مع الوقت","الترخيص يتغيّر بين الإصدارات","حجم المكتبات يزيد تدريجياً"]'::jsonb, 0, NULL, 'الكود لم يتغيّر، وما تغيّر معرفتنا بما فيه.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'ما الذي يجب فحصه قبل إضافة مكتبة جديدة؟', '["عدد التنزيلات في اليوم الأول","نشاط صيانتها وحجم اعتمادياتها","لغة كتابة توثيقها الرسمي","اسم الشركة الراعية لها"]'::jsonb, 1, NULL, 'مكتبة مهجورة تجرّ عشرين مكتبة معها ثلاثة أضعاف المخاطرة.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'ما فائدة قائمة مكوّنات البرمجية؟', '["تقلّل حجم حزمة النشر النهائية","تمنع تركيب مكتبات غير معتمدة","تُظهر ما يحمله التطبيق فعلاً","تسرّع بناء التطبيق عند النشر"]'::jsonb, 2, NULL, 'حين تُعلن ثغرة في مكتبة، السؤال الأول: هل نحملها؟', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'ما خطر تركيب المكتبات من مصدر غير موثوق؟', '["قد تكون نسختها أقدم من الرسمية","قد يكون توثيقها ناقصاً","قد تحتاج إعداداً إضافياً","قد تحمل كوداً خبيثاً يعمل بصلاحياتك"]'::jsonb, 3, NULL, 'التركيب ينفّذ نصوصاً، فالمصدر جزء من سطح الهجوم لا تفصيل إداري.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'أين تُحفظ مفاتيح التطبيق واعتماداته؟', '["في مخزن أسرار خارج الكود","في ملف إعداد داخل المستودع","في تعليق أعلى ملف الاتصال","في متغيّر ثابت داخل الكود"]'::jsonb, 0, NULL, 'ما يدخل المستودع يصل كل من له وصول للكود ونسخه.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'hard', 'ما الذي يجب فعله بمفتاح دخل المستودع ثم حُذِف؟', '["الاكتفاء بحذفه من آخر نسخة","تدويره لأنه باقٍ في التاريخ","نقله لملف مستبعد من الرفع","تشفيره داخل الملف نفسه"]'::jsonb, 1, NULL, 'الحذف يزيله من الحاضر لا من السجل، ومن نسخ المستودع يملكه.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'ما الذي يكشفه أثر الخطأ الكامل للمستخدم؟', '["كلمات مرور المستخدمين الآخرين","مفاتيح التشفير المستخدمة","مسارات الملفات وإصدارات المكتبات","سجل عمليات قاعدة البيانات"]'::jsonb, 2, NULL, 'خريطة داخلية مجانية تختصر على المهاجم مرحلة الاستطلاع.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'كيف تُصاغ رسالة الخطأ للمستخدم؟', '["مفصّلة له ليبلّغ الدعم بدقة","مخفية تماماً بلا أي رسالة","موحّدة في السجل والواجهة","عامة له ومفصّلة في السجل"]'::jsonb, 3, NULL, 'المستخدم يحتاج ما يفعله، والمطوّر يحتاج التفصيل في مكان آمن.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'لماذا يخطر تسجيل جسم الطلب كاملاً في السجل؟', '["قد يحوي اعتماداً أو بيانات شخصية","قد يبطئ كتابة السجل كثيراً","قد يغيّر ترتيب الأحداث","قد يمنع تدوير ملف السجل"]'::jsonb, 0, NULL, 'السجل يُقرأ على نطاق أوسع من قاعدة البيانات ويُنسخ أكثر منها.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'ما فائدة فصل الأسرار عن الكود في بيئات مختلفة؟', '["ألا يتغيّر الكود بين البيئات","ألا يبلغ سر الإنتاج بيئة الاختبار","ألا يحتاج النشر إعداداً يدوياً","ألا يتكرر الاتصال بقاعدة البيانات"]'::jsonb, 1, NULL, 'بيئة الاختبار أضعف حماية ونسخها تُشارَك، فسرّها يجب أن يكون غيره.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'hard', 'ما الذي يميّز التدوير الدوري للأسرار؟', '["يمنع تسرّب السر أصلاً","يقوّي خوارزمية التشفير","يحدّ نافذة استغلال سر تسرّب","يقلّل عدد الأسرار المستخدمة"]'::jsonb, 2, NULL, 'لا يمنع التسرّب، وإنما يجعل المسروق ينتهي قبل أن يُستغَل غالباً.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'ما الذي يجب أن يحدث عند خطأ غير متوقّع أثناء التنفيذ؟', '["إتمامها وتسجيل تحذير فقط","إعادة المحاولة بلا حد","تجاهل الخطأ ومتابعة التنفيذ","إلغاء العملية وتسجيل التفصيل"]'::jsonb, 3, NULL, 'المتابعة على حالة غير معروفة أخطر من التوقف الصريح.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'hard', 'لماذا يخطر إظهار سبب فشل التحقق بدقة؟', '["يرشد المهاجم لما ينقص محاولته","يطيل زمن معالجة الطلب","يمنع المستخدم من إعادة المحاولة","يزيد حجم الرد المرسل"]'::jsonb, 0, NULL, 'الدقة نافعة في السجل، ومضرّة في الرد الذي يقرؤه المهاجم.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'ما الذي يمنع رفع الأسرار للمستودع أصلاً؟', '["مراجعة الكود قبل الدمج فقط","فحص آلي يرفض الدفع عند اكتشافها","تسمية الملفات بأسماء غير واضحة","تشفير المستودع كاملاً"]'::jsonb, 1, NULL, 'المراجعة البشرية تسهو، والفحص الآلي يقف عند كل دفعة بلا استثناء.', 'multiple-choice', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'ما الخلل في هذا المقطع؟', '["السر مكتوب داخل الكود نفسه","الاتصال يتم قبل التحقق منه","المتغيّر يجب أن يكون متغيّراً","المفتاح أقصر من المطلوب"]'::jsonb, 0, NULL, 'كل من له وصول للمستودع أو نسخة منه يملك المفتاح.', 'code', 'const API_KEY = "sk_live_9f2a4c8e1b";
const db = connect(API_KEY);', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'hard', 'ما الخلل في معالجة الخطأ هذي؟', '["الاستثناء لا يُسجَّل في السجل","فشل التحقق ينتهي بالسماح","الدالة لا تعيد أي قيمة","الفحص يقع خارج الكتلة"]'::jsonb, 1, NULL, 'التطبيق يفشل مفتوحاً، والصحيح أن يمنع عند تعذّر التحقق.', 'code', 'try {
  checkPermission(user, file);
} catch (e) {
  allowAccess();
}', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'hard', 'ما الذي يكشفه هذا الرد للمستخدم؟', '["كلمات مرور مستخدمي التطبيق","مفاتيح الاتصال بقاعدة البيانات","بنية الخادم وإصداراته وأسماء جداوله","عناوين المستخدمين المتصلين"]'::jsonb, 2, NULL, 'الرد يعطي المهاجم خريطة كان سيقضي وقتاً لبنائها.', 'code', 'HTTP 500
SQLException at /var/www/app/db/query.php:142
MySQL 5.7.31 · table: users_private', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'hard', 'ما الذي يستوجب إجراءً في هذا التقرير؟', '["مكتبة حديثة تحتاج ترقية دورية","مكتبة بلا اعتماديات فرعية","مكتبة بترخيص غير واضح","مكتبة مهجورة بثغرة وشجرة واسعة"]'::jsonb, 3, NULL, 'الهجر يعني ألا ترقيع، والشجرة الواسعة توسّع ما تحمله معها.', 'code', 'lib-parse@1.2.0  · آخر تحديث: قبل ٤ سنوات
                 · ثغرة معلنة: نعم
                 · اعتماديات فرعية: ١٧', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'hard', 'ما الثغرة في هذا التسلسل؟', '["قد يتغيّر المسار قبل القراءة","الفحص يقع بعد القراءة هنا","المسار لا يُتحقق من صيغته","الملف يُقرأ مرتين بلا داعٍ"]'::jsonb, 0, NULL, 'استبدال الهدف بعد الفحص يجعل المقروء غير المفحوص.', 'code', 'if (isAllowed(path)) {
   // فاصل زمني
   readFile(path);
}', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'ما العيب في هذا التحقق من المدخل؟', '["الشرط يقبل القيمة الفارغة","قائمة ممنوع تلاحق صيغة واحدة","المقارنة حساسة لحالة الأحرف","الدالة لا تتعامل مع الأرقام"]'::jsonb, 1, NULL, 'صيغ كثيرة تؤدي الغرض نفسه، والصحيح تحديد المسموح لا مطاردة الممنوع.', 'code', 'if (input.includes("<script>")) reject();
else accept();', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'ما الذي يمنعه هذا السطر في ملف الاعتماديات؟', '["تحميل المكتبة من مصدر آخر","استخدام المكتبة في الاختبار","تركيب نسخة أحدث دون قصد","ظهور المكتبة في قائمة المكوّنات"]'::jsonb, 2, NULL, 'التثبيت الدقيق يجعل كل بيئة تركّب ما رُوجِع واختُبِر بعينه.', 'code', '"lib-auth": "2.4.1"   بدل   "lib-auth": "^2.4.1"', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'hard', 'ما الخلل في سطر التسجيل هذا؟', '["يسجّل بمستوى معلومات لا خطأ","يحوّل الكائن لنص بلا داعٍ","يفتقر للطابع الزمني","يسجّل الجسم كاملاً ببياناته"]'::jsonb, 3, NULL, 'جسم طلب الدفع يحمل بيانات بطاقة وهوية لا يجوز أن تصل السجل.', 'code', 'logger.info("payment request: " + JSON.stringify(req.body));', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'ما الخلل في حساب اتصال التطبيق هذا؟', '["صلاحيات أوسع بكثير مما يحتاجه","اسم الحساب يكشف وظيفته","الحساب بلا كلمة مرور محددة","الحساب يعمل على قاعدة واحدة"]'::jsonb, 0, NULL, 'حقن ناجح على هذا الحساب يحذف قواعد كاملة لا صفوفاً.', 'code', 'db_user: app_service
grants: ALL PRIVILEGES ON *.*', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'hard', 'ما الخطر في أمر التركيب هذا؟', '["الأمر يفتقر لتحديد النسخة","اسم قريب من مكتبة شائعة","الخيار المستخدم لم يعد لازماً","التركيب يحتاج صلاحية إدارية"]'::jsonb, 1, NULL, 'حرفان مقلوبان يجلبان حزمة أخرى تنفّذ نصوصاً بصلاحيات المطوّر.', 'code', 'npm install lodahs --save', NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'التطبيق يجب أن يمنع العملية عند تعذّر التحقق لا أن يسمح بها.', '["صح","خطأ"]'::jsonb, 0, NULL, 'الفشل المغلق يجعل انقطاع الخدمة منعاً لا انفتاحاً.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'التحقق في المتصفح يغني عن التحقق في الخادم إن كان دقيقاً.', '["صح","خطأ"]'::jsonb, 1, NULL, 'الطلب يُرسل مباشرة دون المتصفح، فيسقط كل فحص فيه.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'قائمة المسموح تمنع صيغاً لم تخطر ببال كاتب القاعدة.', '["صح","خطأ"]'::jsonb, 0, NULL, 'ما لم يُذكر مرفوض، بخلاف قائمة الممنوع التي تلاحق المعروف.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'ثغرة في اعتمادية غير مباشرة لا تخص تطبيقك.', '["صح","خطأ"]'::jsonb, 1, NULL, 'كودها يعمل بصلاحيات تطبيقك، والمستخدم يُصاب منه لا منها.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'تحديث المكتبات عند الإطلاق وحده يكفي طوال عمر التطبيق.', '["صح","خطأ"]'::jsonb, 1, NULL, 'الثغرات تُكتشف لاحقاً في كود لم يتغيّر، فالمتغيّر معرفتنا به.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'تثبيت النسخة بدقة يجعل كل البيئات تركّب ما جرى اختباره.', '["صح","خطأ"]'::jsonb, 0, NULL, 'بلا تثبيت قد يعمل الاختبار على نسخة والإنتاج على أخرى.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'حذف المفتاح من آخر نسخة يكفي إن كان قد دخل المستودع.', '["صح","خطأ"]'::jsonb, 1, NULL, 'يبقى في التاريخ ومع كل من نسخ المستودع، فالتدوير لازم.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'رسالة الخطأ العامة للمستخدم مع تفصيل في السجل ممارسة سليمة.', '["صح","خطأ"]'::jsonb, 0, NULL, 'المستخدم يحتاج ما يفعله، والتفصيل يبقى في مكان محمي.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'hard', 'تدوير الأسرار يمنع تسرّبها من الأساس.', '["صح","خطأ"]'::jsonb, 1, NULL, 'لا يمنع التسرّب وإنما يحدّ نافذة استغلال ما تسرّب.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'الفحص الآلي عند الدفع يمسك أسراراً تسهو عنها مراجعة الكود.', '["صح","خطأ"]'::jsonb, 0, NULL, 'المراجعة البشرية تتعب، والفحص يقف عند كل دفعة بلا استثناء.', 'true-false', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'صل كل مبدأ تصميم بأثره', NULL, NULL, NULL, 'أربعتها تقلّل الضرر لا احتمال وقوعه، ولذلك تُطبَّق مجتمعة.', 'matching', NULL, '[{"left":"الفشل المغلق","right":"المنع عند تعذّر التحقق"},{"left":"الإعداد الافتراضي الآمن","right":"شحن مقيّد لا مفتوح"},{"left":"أقل صلاحية","right":"حساب يفعل ما يلزمه فقط"},{"left":"الفصل بين المكوّنات","right":"حصر أثر اختراق واحد"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'hard', 'صل كل مصطلح في التصميم الآمن بمعناه', NULL, NULL, NULL, 'الأربعة تقع قبل كتابة السطر الأول لا بعده.', 'matching', NULL, '[{"left":"حدّ الثقة","right":"موضع انتقال البيانات لطبقة أوثق"},{"left":"نمذجة التهديدات","right":"حصر ما قد يُهاجَم قبل البناء"},{"left":"فارق الفحص والاستخدام","right":"تغيّر الحالة بين التحقق والتنفيذ"},{"left":"قائمة المسموح","right":"رفض ما لم يُذكر صراحة"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'صل كل أداة أو ملف بوظيفته', NULL, NULL, NULL, 'كل واحد يجيب سؤالاً مختلفاً عن الكود الذي لم يكتبه فريقك.', 'matching', NULL, '[{"left":"ملف تثبيت الإصدارات","right":"توحيد النسخ بين البيئات"},{"left":"أداة فحص الاعتماديات","right":"مطابقة النسخ بثغرات معلنة"},{"left":"قائمة مكوّنات البرمجية","right":"معرفة ما يحمله التطبيق"},{"left":"مصدر التركيب الموثوق","right":"منع جلب كود مجهول"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'صل كل خطر في الاعتماديات بوصفه', NULL, NULL, NULL, 'أربعتها تدخل التطبيق دون أن يكتب أحد سطراً منها.', 'matching', NULL, '[{"left":"مكتبة مهجورة","right":"ثغراتها تبقى بلا ترقيع"},{"left":"اسم مشابه للشائع","right":"خطأ حرف يجلب كوداً خبيثاً"},{"left":"شجرة اعتماديات واسعة","right":"كود كثير لم يُختَر مباشرة"},{"left":"نسخة غير مثبّتة","right":"اختلاف الإنتاج عن الاختبار"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'صل كل معلومة بموضعها الصحيح', NULL, NULL, NULL, 'الخطأ الشائع خلط ما يُعرَض بما يُسجَّل بما لا يُحفَظ أصلاً.', 'matching', NULL, '[{"left":"أثر الخطأ الكامل","right":"السجل المحمي"},{"left":"رسالة عامة للمستخدم","right":"واجهة التطبيق"},{"left":"مفتاح الاتصال","right":"مخزن الأسرار"},{"left":"بيانات البطاقة","right":"لا تُسجَّل إطلاقاً"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'صل كل حالة تسرّب سر بإجرائها', NULL, NULL, NULL, 'الحذف يعالج الظاهر، والتدوير وحده يبطل المسروق.', 'matching', NULL, '[{"left":"مفتاح دخل المستودع","right":"تدويره فوراً لا حذفه"},{"left":"سر في متغيّر بيئة اختبار","right":"فصله عن سر الإنتاج"},{"left":"سر ظهر في سجل","right":"تدويره وتنقية السجل"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'hard', 'صل كل قرار بالطبقة التي يقع فيها', NULL, NULL, NULL, 'ما يقع في العميل تحسين، وما يقع في الخادم ضمانة.', 'matching', NULL, '[{"left":"التحقق من صحة المدخل","right":"الخادم دائماً"},{"left":"تحسين تجربة الإدخال","right":"العميل للراحة"},{"left":"صلاحية حساب الاتصال","right":"قاعدة البيانات"},{"left":"حصر أثر الاختراق","right":"بنية المكوّنات"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'صل كل سؤال بما يجيب عنه قبل إضافة مكتبة', NULL, NULL, NULL, 'أربع دقائق قبل الإضافة توفّر ترقيعاً عاجلاً بعد سنة.', 'matching', NULL, '[{"left":"متى آخر تحديث لها؟","right":"هل ما زالت تُصان"},{"left":"كم اعتمادية تجرّها؟","right":"كم كوداً تضيفه فعلاً"},{"left":"هل لها ثغرات معلنة؟","right":"ما تحمله اليوم"},{"left":"ما مصدر تركيبها؟","right":"من كتب ما سيُنفَّذ"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'hard', 'صل كل ممارسة بما تحدّه', NULL, NULL, NULL, 'لا واحدة منها تمنع الخطأ، وكلها تقلّص ما يترتب عليه.', 'matching', NULL, '[{"left":"تدوير الأسرار","right":"نافذة استغلال ما تسرّب"},{"left":"الفحص عند الدفع","right":"دخول السر للمستودع"},{"left":"فصل أسرار البيئات","right":"وصول سر الإنتاج للاختبار"},{"left":"رسالة الخطأ العامة","right":"ما يعرفه المهاجم عن الداخل"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'صل كل خلل برمجي بعلاجه', NULL, NULL, NULL, 'كل علاج يبدّل قراراً في الكود لا يضيف أداة فوقه.', 'matching', NULL, '[{"left":"الفشل مفتوحاً عند الخطأ","right":"المنع افتراضياً في المعالجة"},{"left":"ملاحقة صيغ ممنوعة","right":"تحديد المسموح صراحة"},{"left":"حساب اتصال واسع الصلاحية","right":"حصره بما تحتاجه العملية"},{"left":"تشفير مكتوب محلياً","right":"مكتبة معتمدة مراجَعة"}]'::jsonb, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'اكتب اسم تحليل ما قد يُهاجَم في التطبيق قبل بنائه', NULL, NULL, NULL, 'إصلاح التصميم على الورق أرخص من إصلاحه بعد النشر.', 'terminal', NULL, NULL, '["نمذجة التهديدات","threat modeling","نمذجة التهديد","تحليل التهديدات","نموذج التهديدات"]'::jsonb, 'الممارسة', 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'hard', 'اكتب اسم المبدأ الذي يجعل التطبيق يمنع العملية عند تعذّر التحقق', NULL, NULL, NULL, 'انقطاع خدمة التحقق يجب أن يعني منعاً لا سماحاً.', 'terminal', NULL, NULL, '["الفشل المغلق","fail closed","fail secure","الفشل الآمن","الإغلاق عند الفشل"]'::jsonb, 'المبدأ', 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'hard', 'اكتب اسم الموضع الذي تنتقل عنده البيانات من طبقة أقل ثقة لأوثق', NULL, NULL, NULL, 'عنده يقع الفحص، فما عبره بلا تحقق دخل وهو غير موثوق.', 'terminal', NULL, NULL, '["حد الثقة","حدّ الثقة","trust boundary","حدود الثقة","الحد الموثوق"]'::jsonb, 'الموضع', 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'hard', 'اكتب اسم الثغرة التي تتغيّر فيها الحالة بين لحظة الفحص ولحظة الاستخدام', NULL, NULL, NULL, 'يُفحص الملف ثم يُستبدل قبل استخدامه فينفَّذ غير ما فُحص.', 'terminal', NULL, NULL, '["فارق وقت الفحص والاستخدام","TOCTOU","toctou","ثغرة التوقيت","time of check time of use"]'::jsonb, 'الثغرة', 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'اكتب وصف المكتبة التي تجلبها مكتبة أخرى معها دون اختيار مباشر', NULL, NULL, NULL, 'أغلب ما يعمل في التطبيق لم يُختَر مباشرة.', 'terminal', NULL, NULL, '["اعتمادية غير مباشرة","transitive dependency","اعتمادية فرعية","تبعية غير مباشرة","اعتمادية متعدية"]'::jsonb, 'الوصف', 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'اكتب اسم نشر حزمة باسم قريب من اسم حزمة شائعة', NULL, NULL, NULL, 'خطأ حرف واحد يجلب كوداً خبيثاً بصلاحيات المطوّر.', 'terminal', NULL, NULL, '["التشابه في الاسم","typosquatting","انتحال الاسم","الاسم المشابه","تشابه الأسماء"]'::jsonb, 'الهجوم', 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'اكتب اسم القائمة التي تبيّن كل مكوّنات البرمجية واعتمادياتها', NULL, NULL, NULL, 'حين تُعلن ثغرة في مكتبة، السؤال الأول: هل نحملها؟', 'terminal', NULL, NULL, '["قائمة مكوّنات البرمجية","SBOM","sbom","قائمة المكوّنات","فاتورة مكونات البرمجيات"]'::jsonb, 'القائمة', 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'اكتب الإجراء اللازم لمفتاح دخل المستودع ولو حُذِف بعدها', NULL, NULL, NULL, 'يبقى في التاريخ ومع كل من نسخ المستودع.', 'terminal', NULL, NULL, '["تدويره","التدوير","rotation","تغييره","تدوير المفتاح","استبداله"]'::jsonb, 'الإجراء', 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'اكتب اسم كشف تفاصيل داخلية للمستخدم عبر رسائل الخطأ', NULL, NULL, NULL, 'أثر الخطأ الكامل خريطة داخلية مجانية للمهاجم.', 'terminal', NULL, NULL, '["كشف المعلومات","information disclosure","تسريب المعلومات","إفشاء المعلومات","كشف معلومات"]'::jsonb, 'الخطر', 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'اكتب اسم الموضع الصحيح لحفظ مفاتيح التطبيق خارج الكود', NULL, NULL, NULL, 'ما يدخل المستودع يصل كل من له وصول للكود ونسخه.', 'terminal', NULL, NULL, '["مخزن الأسرار","secret manager","مدير الأسرار","خزنة الأسرار","vault","مخزن أسرار"]'::jsonb, 'الموضع', 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'أي مما يلي من مبادئ التصميم الآمن؟', '["الفشل مغلقاً عند تعذّر التحقق","السماح افتراضياً لتسهيل الاستخدام","الإعداد الافتراضي المقيّد","منح الاتصال صلاحية كاملة"]'::jsonb, NULL, '[0,2]'::jsonb, 'الخياران الآخران يوسّعان الضرر بدل حصره.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'أي مما يلي صحيح عن موضع التحقق من المدخلات؟', '["فحص العميل يغني عن فحص الخادم","قائمة المسموح أقوى من قائمة الممنوع","الفحص في الخادم لازم دائماً","الفحص في العميل بلا أي فائدة"]'::jsonb, NULL, '[1,2]'::jsonb, 'فحص العميل نافع للتجربة ولا يُعتمد عليه ضمانةً.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'أي مما يلي يجب فحصه قبل إضافة مكتبة؟', '["تاريخ آخر تحديث لها","عدد نجوم مستودعها فقط","عدد اعتمادياتها الفرعية","طول اسم المكتبة"]'::jsonb, NULL, '[0,2]'::jsonb, 'الشعبية لا تعني الصيانة، والشجرة الواسعة تضاعف ما تحمله.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'hard', 'أي مما يلي يعالج مخاطر الاعتماديات؟', '["تثبيت النسخ بدقة","التحديث عند الإطلاق فقط","فحص دوري بأداة اعتماديات","التركيب من أي مصدر متاح"]'::jsonb, NULL, '[0,2]'::jsonb, 'الثغرات تُكتشف بعد الإطلاق، والمصدر جزء من سطح الهجوم.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'أي مما يلي لا يجوز أن يدخل السجل؟', '["كلمة المرور المدخلة","رقم البطاقة كاملاً","وقت وقوع الحدث","معرّف المستخدم"]'::jsonb, NULL, '[0,1]'::jsonb, 'السجل يُقرأ ويُنسخ على نطاق أوسع من قاعدة البيانات.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'hard', 'أي مما يلي لازم عند تسرّب مفتاح للمستودع؟', '["تدوير المفتاح فوراً","حذفه من آخر نسخة فقط","مراجعة استخدامه في المدة الماضية","إعادة تسمية الملف الذي حواه"]'::jsonb, NULL, '[0,2]'::jsonb, 'الحذف لا يزيله من التاريخ، والمراجعة تكشف إن استُغِل فعلاً.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'hard', 'أي مما يلي صحيح عن رسائل الخطأ؟', '["العامة للمستخدم والمفصّلة للسجل","التفصيل للمستخدم يسرّع الدعم","أثر الخطأ الكامل يكشف بنية الخادم","إخفاء كل رسالة أفضل ممارسة"]'::jsonb, NULL, '[0,2]'::jsonb, 'الإخفاء التام يربك المستخدم، والتفصيل له يخدم المهاجم.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'hard', 'أي مما يلي يحدّ أثر حقن ناجح؟', '["حساب اتصال بأقل صلاحية","حساب اتصال إداري واحد","فصل المكوّنات عن بعضها","تجميع الخدمات في مكوّن واحد"]'::jsonb, NULL, '[0,2]'::jsonb, 'الحدّ يقع بعد نجاح الهجوم، فيقلّل ما يبلغه المهاجم.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'أي مما يلي من علامات مكتبة عالية المخاطرة؟', '["توقف صيانتها منذ سنوات","وجود توثيق مفصّل لها","ثغرات معلنة بلا ترقيع","إصدارات دورية منتظمة"]'::jsonb, NULL, '[0,2]'::jsonb, 'التوثيق والانتظام علامتا صحة لا خطر.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'hard', 'أي مما يلي يقع قبل كتابة السطر الأول؟', '["نمذجة التهديدات","مراجعة أثر الخطأ في الإنتاج","تحديد حدود الثقة","تحليل سجلات الحوادث"]'::jsonb, NULL, '[0,2]'::jsonb, 'الاثنان الآخران يقعان بعد التشغيل لا في التصميم.', 'multi-select', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'رتّب خطوات نمذجة التهديدات', '["وصف ما يبنيه التطبيق","تحديد حدود الثقة فيه","حصر التهديدات المحتملة","تحديد الضوابط لكل تهديد"]'::jsonb, NULL, NULL, 'الضوابط آخراً لأنها تتبع التهديد لا تسبقه.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'رتّب معالجة مدخل وارد من المستخدم', '["استلامه في الخادم","التحقق منه بقائمة مسموح","رفضه أو تمريره للمعالجة","تسجيل الرفض عند وقوعه"]'::jsonb, NULL, NULL, 'التسجيل بعد القرار لأنه يوثّق ما جرى لا ما سيجري.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'medium', 'رتّب خطوات إضافة مكتبة جديدة بأمان', '["فحص صيانتها وثغراتها","تثبيت نسختها بدقة","تركيبها من مصدر موثوق","إضافتها لقائمة المكوّنات"]'::jsonb, NULL, NULL, 'الفحص قبل التثبيت لأن نتيجته قد تعني ألا تُضاف أصلاً.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'hard', 'رتّب خطوات التعامل مع ثغرة معلنة في مكتبة', '["مراجعة قائمة المكوّنات","تحديد النسخ المتأثرة عندك","اختبار الترقية على بيئة مماثلة","نشرها بعد التحقق"]'::jsonb, NULL, NULL, 'قائمة المكوّنات أولاً لأنها تجيب: هل نحملها أصلاً؟', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'hard', 'رتّب خطوات معالجة مفتاح تسرّب للمستودع', '["تدوير المفتاح فوراً","مراجعة استخدامه السابق","نقله لمخزن أسرار","إضافة فحص يمنع تكراره"]'::jsonb, NULL, NULL, 'التدوير أولاً لأنه يبطل المسروق في ساعته.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'رتّب معالجة خطأ غير متوقّع في عملية حساسة', '["التقاط الاستثناء","إلغاء العملية كاملة","تسجيل التفصيل في السجل","إعادة رسالة عامة للمستخدم"]'::jsonb, NULL, NULL, 'الإلغاء قبل التسجيل لأن المتابعة على حالة مجهولة أخطر.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'hard', 'رتّب طبقات الحدّ من أثر الحقن', '["التحقق من المدخل","استعلام بمعاملات محدّدة","حساب اتصال بأقل صلاحية","فصل المكوّنات عن بعضها"]'::jsonb, NULL, NULL, 'الطبقتان الأخيرتان تعملان بعد نجاح الهجوم لا قبله.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secrets and Error Handling', 'medium', 'رتّب خطوات إخراج سر من الكود', '["حصر مواضعه في المستودع","نقله لمخزن أسرار","تدوير قيمته القديمة","منع رفعه بفحص آلي"]'::jsonb, NULL, NULL, 'الفحص الآلي آخراً لأنه يحرس ما بعد التنظيف.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Dependency Security', 'hard', 'رتّب خطوات مراجعة دورية للاعتماديات', '["تشغيل أداة الفحص","ترتيب النتائج بالخطورة","ترقية المتأثر واختباره","توثيق ما تعذّرت ترقيته"]'::jsonb, NULL, NULL, 'ما تعذّرت ترقيته يُوثَّق ليُحاط بضابط تعويضي لا ليُنسى.', 'ordering', NULL, NULL, NULL, NULL, 60, true),
  ('CyberSecurity', 'Application and Web Security', 4, 'Secure Design', 'medium', 'رتّب مراحل إدخال ميزة جديدة بأمان', '["نمذجة تهديداتها","كتابتها بمبادئ آمنة","مراجعة كودها","مراقبة أثرها بعد النشر"]'::jsonb, NULL, NULL, 'المراقبة بعد النشر تكشف ما لم تكشفه المراجعة.', 'ordering', NULL, NULL, NULL, NULL, 60, true);

-- تحقق فوري بعد الإدخال
select level, type, count(*)
from public.questions
where track_id = 'CyberSecurity'
  and section_id = 'Application and Web Security'
  and level = 4
  and is_active
group by level, type
order by type;

commit;
